### ISSUE TITLE
ajenti suddenly stopped working

### ISSUE THREAD

**Issue by saadamin** [ajenti/ajenti#1007]
# sudo service ajenti restart
Stopping Ajenti:
 * not running
Starting Ajenti:
/etc/init.d/ajenti: 52: /etc/init.d/ajenti: /usr/bin/ajenti-panel: not found
 * failed

my ubuntu version is
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by Ghost4255** [comment]
Failed to restart ajenti.service: Unit ajenti.service not found.

**Comment by timlaughlin** [comment]
Having the exact same problem.. what happened ?

**Comment by Ghost4255** [comment]
With me it is since the update 5 hours ago!

**Comment by Ghost4255** [comment]
update-rc.d: error: unable to read /etc/init.d/ajenti
/var/lib/dpkg/info/ajenti.postinst: 4: /var/lib/dpkg/info/ajenti.postinst: ajenti-ssl-gen: not found

**Comment by dinho-afsn** [comment]
Stopped my servers that updated today, has been unlocked for hours.
Does anyone know how to install previous version manually?

**Comment by timlaughlin** [comment]
dinho-afsn: Did your actual websites go down or just the ajenti interface. My actual sites are still but put the ajenti interface is not working. I run a NGINX host server.

**Comment by dinho-afsn** [comment]
Thanks for the answer. Is there any way to manually install a previous version?

**Comment by dinho-afsn** [comment]
I'm trying to but I only found a repository with packages here, but without any hassle in the installation. Http://realrepo.ajenti.org:8888/debian/

**Comment by timlaughlin** [comment]
On Ubuntu... Run the following to roll back to the last version:

In your home directory.

1. wget http://realrepo.ajenti.org:8888/ng/debian/ajenti_1.2.23.8_all.deb
2. dpkg -i ajenti_1.2.23.8_all.deb

**Comment by dinho-afsn** [comment]
here result https://postimg.org/image/k35a11u6p/

here solve dependences 

wget http://realrepo.ajenti.org:8888/ng/debian/ajenti_1.2.23.8_all.deb
dpkg -i ajenti_1.2.23.8_all.deb

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -f install

I appreciate the attention and the help. Thank you!

**Comment by Eugeny** [comment]
I've updated the package, please `apt-get update` and `apt-get install ajenti` again.

**Comment by timlaughlin** [comment]
Still not working @Eugeny

**Comment by timlaughlin** [comment]
Looks like the deb isn't the right size..

ajenti_1.2.23.2_all.deb                            21-Dec-2015 11:17             1072550
ajenti_1.2.23.3_all.deb                            04-Jan-2016 19:46             1072678
ajenti_1.2.23.4_all.deb                            24-Feb-2016 11:14             1722378
ajenti_1.2.23.6_all.deb                            25-Feb-2016 14:56             1722872
ajenti_1.2.23.7_all.deb                            26-Feb-2016 22:50             1722588
ajenti_1.2.23.8_all.deb                            02-Mar-2016 19:09             1722292
ajenti_1.2.23.9_all.deb                            12-Jan-2017 15:29                1966

**Comment by Eugeny** [comment]
Fixed in #1008
