### ISSUE TITLE
Help please, after update does not work !!!!!

### ISSUE THREAD

**Issue by dinho-afsn** [ajenti/ajenti#1009]
I am more than 3 hours trying to solve this problem, what happened, I have some servers with ajenti and all stopped working.
Will I have to change all servers?

**Comment by Eugeny** [comment]
I've updated the package, please `apt-get update` and `apt-get install ajenti` again.

**Comment by bahadirdogru** [comment]
Hi, eugeny for debian repos is that updated as well?

**Comment by Eugeny** [comment]
Fixed in #1008
