### ISSUE TITLE
"Invalid URL" error

### ISSUE THREAD

**Issue by zabszk** [ajenti/ajenti#1012]
After installing ajenti on raspbian I had error "Invalid URL" on port 8000 using HTTPS.

After ajenti-panel -v:

14.01.2017 18:57 ajenti-panel:105              INFO  Using config file /etc/ajenti/config.json
14.01.2017 18:57 ajenti-panel:130              INFO  Ajenti starting in foreground
14.01.2017 18:58 registry.py:280               DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
14.01.2017 18:58 compat.py:20                  DEBUG Popen: git describe --tags 2> /dev/null
14.01.2017 18:58 compat.py:20                  DEBUG Popen: ['lsb_release', '-sd']
14.01.2017 18:58 core.py:60                    INFO  Ajenti 1.2.23.10 running on platform: debian
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin ctdb
14.01.2017 18:58 __init__.py:286               DEBUG Preloading plugin dependency: main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin main
14.01.2017 18:58 __init__.py:342               WARN   *** [main] Plugin crashed: crashed: No module named coros
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 328, in load
    info.init()
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/__init__.py", line 15, in init
    import main
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 4, in <module>
    import gevent.coros
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named coros

14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin samba
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: samba -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin git
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: git -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin ajenti_org
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: ajenti_org -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin packages
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: packages -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin nginx
14.01.2017 18:58 __init__.py:286               DEBUG Preloading plugin dependency: webserver_common
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin webserver_common
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: webserver_common -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin power
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: power -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin apcups
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: apcups -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin sensors
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: sensors -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin services
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: services -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin supervisor
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: supervisor -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin fstab
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: fstab -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin psql
14.01.2017 18:58 __init__.py:286               DEBUG Preloading plugin dependency: db_common
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin db_common
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: db_common -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin iptables
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: iptables -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin plugins
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: plugins -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin dhcpd
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: dhcpd -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin codemirror
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: codemirror -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin apache
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: apache -> webserver_common
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin lm_sensors
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: lm_sensors -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin fm
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: fm -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin fail2ban
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: fail2ban -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin configurator
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: configurator -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin resolv
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: resolv -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin openvpn
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: openvpn -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin hosts
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: hosts -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin tasks
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: tasks -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin taskmgr
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: taskmgr -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin ntpd
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: ntpd -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin ipmi
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: ipmi -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin smartctl
14.01.2017 18:58 __init__.py:286               DEBUG Preloading plugin dependency: dashboard
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin dashboard
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: dashboard -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin rethink
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: rethink -> db_common
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin mysql
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: mysql -> db_common
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin csf
14.01.2017 18:58 compat.py:20                  DEBUG Popen: ['which', 'csf']
14.01.2017 18:58 __init__.py:346               DEBUG  *** [csf] skipping due to BinaryDependency (csf)
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin resources
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin squid
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: squid -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin logs
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: logs -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin uname
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: uname -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin cron
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: cron -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin notepad
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: notepad -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin hddtemp
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: hddtemp -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin munin
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: munin -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin terminal
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: terminal -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin bind9
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: bind9 -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin nsd
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: nsd -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin exports
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: exports -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin mongo
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: mongo -> db_common
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin raid
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: raid -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin snmpd
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: snmpd -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin network
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: network -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin megaraid
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: megaraid -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin users
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: users -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin memcache
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: memcache -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin netatalk
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: netatalk -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin scripts
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: scripts -> main
14.01.2017 18:58 __init__.py:297               DEBUG Loading plugin hdparm
14.01.2017 18:58 __init__.py:283               WARN   *** Plugin dependency unsatisfied: hdparm -> main
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0x75733f30>
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [UI] <ajenti.ui.UI object at 0x76100130>
14.01.2017 18:58 core.py:99                    INFO  Starting server on (u'0.0.0.0', 8000)
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [SessionMiddleware] <ajenti.middleware.SessionMiddleware object at 0x75748650>
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [AuthenticationMiddleware] <ajenti.middleware.AuthenticationMiddleware object at 0x756e4470>
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [CentralDispatcher] <ajenti.routing.CentralDispatcher object at 0x756e46d0>
14.01.2017 18:58 core.py:135                   INFO  SSL enabled: /home/pi/ssl/mixed.pem
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [IPCServer] <ajenti.ipc.IPCServer object at 0x756e4990>
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [Licensing] <ajenti.licensing.Licensing object at 0x756e4a90>
14.01.2017 18:58 feedback.py:30                DEBUG Feedback >> ping ({'edition': 'vanilla', 'version': '1.2.23.10', 'os': 'debian', 'id': 261778})
14.01.2017 18:58 connectionpool.py:188         INFO  Starting new HTTP connection (1): meta.ajenti.org
14.01.2017 18:58 connectionpool.py:362         DEBUG "POST /api/v2/ping HTTP/1.1" 200 36
14.01.2017 18:58 feedback.py:35                DEBUG Feedback << {"status": "ok"}
14.01.2017 18:58 __init__.py:207               DEBUG Root context instantiated [ContentServer] <ajenti.plugins.resources.server.ContentServer object at 0x74e131f0>

**Comment by SerhiyRomanov** [comment]
Hello. Try to update you gevent package
This maybe help:
```
apt-get install python-setuptools python-dev gcc 
easy_install -U gevent==1.1b3
```

**Comment by zabszk** [comment]
I tried this already, but not working.

root@pi:/root# apt-get install python-setuptools python-dev gcc 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version.
python-dev is already the newest version.
python-setuptools is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 58 not upgraded.
root@pi:/root# easy_install -U gevent==1.1b3
Searching for gevent==1.1b3
Reading https://pypi.python.org/simple/gevent/
Best match: gevent 1.1b3
Processing gevent-1.1b3-py2.7-linux-armv7l.egg
gevent 1.1b3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/gevent-1.1b3-py2.7-linux-armv7l.egg
Processing dependencies for gevent==1.1b3
Finished processing dependencies for gevent==1.1b3

**Comment by cyberesprit** [comment]
Hi,

Same problem here, with version 1.x (no problem with 2).

My problem is on debian jessie 8.7, normal pc.

**Comment by underdoeg** [comment]
I have the same issue. Also with jessie 8.7

**Comment by zabszk** [comment]
@cyberesprit What is version 2? I can't see it on github?

**Comment by cyberesprit** [comment]
@zabszk http://ajenti.org/ by default is Ajenti 2 (LightWeight admin panel), Install instructions here -> http://docs.ajenti.org/en/latest/man/install.html

**Comment by ranyyy** [comment]
#1002

**Comment by ghost** [comment]
@zabszk https://github.com/ajenti/ajenti/issues/1002#issuecomment-270422805 (possible solution 1)

**Comment by ghost** [comment]
@zabszk https://github.com/ajenti/ajenti/issues/1002#issuecomment-271574322 (possible solution 2)

**Comment by cyberesprit** [comment]
This is good for me :
https://github.com/ajenti/ajenti/issues/1002#issuecomment-271574322

Thanks !

**Comment by ghost** [comment]
Version 2.x isn't the same as version 1.x .

 1.x is more advanced than 2.x

**Comment by zabszk** [comment]
@ranyyy Method 1 tested before posting this issue, doesn't work. Method 2 - can't find "plugins" directory.

**Comment by zabszk** [comment]
During installation of ajenti 2:

Successfully built ajenti.plugin.core psutil
Installing collected packages: psutil, pyyaml, setproctitle, python-daemon-3k, termcolor, ptyprocess, pexpect, aj, ajenti-panel, ajenti.plugin.core, ajenti.plugin.filesystem, ajenti.plugin.passwd, ajenti.plugin.settings, ajenti.plugin.dashboard, ajenti.plugin.plugins, ajenti.plugin.ace, ajenti.plugin.notepad, pyte, ajenti.plugin.terminal, ajenti.plugin.filemanager, ajenti.plugin.packages, upstart-new, ajenti.plugin.services
  Found existing installation: psutil 2.1.1
    DEPRECATION: Uninstalling a distutils installed project (psutil) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.


and still the same error.

**Comment by ghost** [comment]
@zabszk You can't use both at the same time; choose one. This solution might work for ajenti1.

**Comment by zabszk** [comment]
@ranyyy Solution didn't work for ajenti1, so I uninstalled it and tried to install ajenti2. There was en error during installation and there is the same error.
