### ISSUE TITLE
User not having sudo access

### ISSUE THREAD

**Issue by osfast** [ajenti/ajenti#1013]
hey, 

I have a fresh install of Ubuntu 16.04.1 LTS, used the auto-installer to install Ajenti 2
I can login but it seems my (only) user does not have root privileges (super user access) in Ajenti.
During installation pip seemed to have some trouble getting stuff in /home/myuser/.cache but I dont understand why. 

It's a reoccurring problem since I have tried it multiple times (reinstalling the VM), some advice in how to solve this problem would be appreciated.

**Comment by muotaz** [comment]
Check @sylvanaar comment here:  https://github.com/ajenti/ajenti/issues/933

**Comment by osfast** [comment]
well that might have just solved it for me
