### ISSUE TITLE
Failed to get D-Bus connection

### ISSUE THREAD

**Issue by TreHack** [ajenti/ajenti#1022]
I get the below error message when install finished，How can I fix it?

Successfully built ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins ajenti.plugin.notepad ajenti.plugin.terminal ajenti.plugin.filemanager ajenti.plugin.packages ajenti.plugin.services aj ajenti.plugin.core ajenti.plugin.filesystem ajenti.plugin.passwd ajenti.plugin.ace pyte jadi upstart-new gevent-socketio-master gipc python-daemon-3k setproctitle termcolor
Installing collected packages: cookies, gevent-socketio-master, gipc, jadi, passlib, lockfile, python-daemon-3k, setproctitle, termcolor, aj, ajenti-panel, ajenti.plugin.core, ajenti.plugin.filesystem, ajenti.plugin.passwd, ajenti.plugin.settings, ajenti.plugin.dashboard, ajenti.plugin.plugins, ajenti.plugin.ace, ajenti.plugin.notepad, pyte, ajenti.plugin.terminal, ajenti.plugin.filemanager, ajenti.plugin.packages, upstart-new, ajenti.plugin.services
Successfully installed aj-2.1.17 ajenti-panel-2.1.17 ajenti.plugin.ace-0.25 ajenti.plugin.core-0.82 ajenti.plugin.dashboard-0.35 ajenti.plugin.filemanager-0.22 ajenti.plugin.filesystem-0.38 ajenti.plugin.notepad-0.24 ajenti.plugin.packages-0.27 ajenti.plugin.passwd-0.21 ajenti.plugin.plugins-0.41 ajenti.plugin.services-0.26 ajenti.plugin.settings-0.23 ajenti.plugin.terminal-0.34 cookies-2.2.1 gevent-socketio-master-0.3.6.99 gipc-0.6.0 jadi-1.0.3 lockfile-0.12.2 passlib-1.7.1 pyte-0.4.9 python-daemon-3k-1.5.8 setproctitle-1.1.10 termcolor-1.1.0 upstart-new-0.3.4
:: Installing initscript
/bin/systemctl
Failed to get D-Bus connection: Unknown error -1
Created symlink from /etc/systemd/system/multi-user.target.wants/ajenti.service to /lib/systemd/system/ajenti.service.
Failed to get D-Bus connection: Unknown error -1
:: Complete

Ajenti will be listening at HTTP port 8000
Log in with your root password or another OS user

**Comment by JacobDB** [comment]
Did you ever get this sorted? I'm running in to the same problem trying to install in WSL.
