### ISSUE TITLE
Can't update Ajenti core/panel

### ISSUE THREAD

**Issue by osfast** [ajenti/ajenti#1026]
I seem not to be able to update Ajenti.
tried apt-get update/upgrade, 
tried running installer again, 
tried reading the docs.
my question would be: How does one upgrade Ajenti?

![image](https://cloud.githubusercontent.com/assets/11271476/22977170/dcde7c5e-f38d-11e6-9120-aa9fdbd1a6ae.png)

**Comment by Eugeny** [comment]
2.1.17 is the latest version currently available. Once there's an update, an "Update" button will be available on that page. You can also update it through the `pip` package manager.
