### ISSUE TITLE
[DIY FIX] Cant open / edit .json files with the notepad plugin, Ajenti core 2.1.17

### ISSUE THREAD

**Issue by bbassie** [ajenti/ajenti#1038]
all.vendor.js:13433 Guessing mode for <filename>.json
all.js:726 Unhandled exception occured
all.js:727 Consider sending this error to https://github.com/ajenti/ajenti/issues/new
(anonymous) @ all.js:727
$digest @ all.vendor.js:17051
$apply @ all.vendor.js:17297
done @ all.vendor.js:11460
completeRequest @ all.vendor.js:11658
requestLoaded @ all.vendor.js:11599
all.vendor.js:13433 Error: ui-ace cannot use an object or an array as a model
    at Array.<anonymous> (all.vendor.js:36431)
    at ngModelWatch (all.vendor.js:26901)
    at Scope.$digest (all.vendor.js:17024)
    at Scope.$apply (all.vendor.js:17297)
    at done (all.vendor.js:11460)
    at completeRequest (all.vendor.js:11658)
    at XMLHttpRequest.requestLoaded (all.vendor.js:11599)
(anonymous) @ all.vendor.js:13433
(anonymous) @ all.js:728
$digest @ all.vendor.js:17051
$apply @ all.vendor.js:17297
done @ all.vendor.js:11460
completeRequest @ all.vendor.js:11658
requestLoaded @ all.vendor.js:11599

**Comment by badgamernl** [comment]
I edited the notepad code to stringify the json.
The path to the file i fixed:
ajenti_plugin_notepad/recources/build/all.js
I replaced line 52:
```
$scope.content = content;
```
With:
```
var filename = $scope.path.split('/');
var type = filename[filename.length - 1].substr(filename[filename.length - 1].lastIndexOf('.')+1);
if (type == "json") {
	$scope.content = JSON.stringify(content, null, 2);
} else {
	$scope.content = content;
}
```

**Comment by bbassie** [comment]
I wrote a quick little fix to open / edit json files. The file changed is:
```<python package folder>/ajenti_plugin_notepad/resources/build/all.js```
Line 52:
```
$scope.content = content;
```
With:
```
var filename = $scope.path.split('/');
var type = filename[filename.length - 1].substr(filename[filename.length - 1].lastIndexOf('.')+1);
if (type == "json") {
	$scope.content = JSON.stringify(content, null, 2);
} else {
	$scope.content = content;
}
```
NOTE:
This does change the spacing..

**Comment by Eugeny** [comment]
Please update your `filesystem` plugin
