### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by endermrn2** [ajenti/ajenti#1039]
the user manager dont work and i reinstall but later give this how to fix
Authentication failed
{"data":"Internal Server Error","status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"/api/core/auth","data":{"username":"root","password":"liF1973qoG","mode":"normal"},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"cached":false},"statusText":"Internal Server Error"}

**Comment by okaragoz** [comment]
Hi @endermrn2  Please try to install python- dev with this command`aptitude install python-dev`
if you have a chance to make fresh install which could be better!
GoodLuck!
