### ISSUE TITLE
i have empty screen after login

### ISSUE THREAD

**Issue by m1s3rys1gn4l** [ajenti/ajenti#1049]
i m using it on debian, with banana pro,

http://i66.tinypic.com/f1h2k8.jpg

**Comment by SerhiyRomanov** [comment]
Try
`sudo apt-get install python-setuptools python-dev gcc`
`sudo easy_install -U gevent==1.1b3`

**Comment by llucenic** [comment]
It worked for me to install these additional packages. Please include these steps in the installer. Ajenti installed on a fresh Debian 8.8 (jessie) using the automated installer ends up being useless without these tweaks.

**Comment by m1s3rys1gn4l** [comment]
Thanks @SerhiyRomanov  my problem solved :)

**Comment by Bxnnet** [comment]
thanks a lot @SerhiyRomanov
