### ISSUE TITLE
Remove ajenti 2 service from ubuntu

### ISSUE THREAD

**Issue by nerijunior** [ajenti/ajenti#1051]
I've installed the ajenti v2 but I need the version 1, I runned all the `pip uninstall` for all ajenti packages, `apt-get remove ajenti`, purge, clean, reboot, etc.

But the service still installed, at `/etc/init.d/` doesn't exists any file called `%ajenti%`.

How can I uninstall it completely?

**Comment by nerijunior** [comment]
I found the file `ajenti.service` at `/lib/systemd/system/` can simple delete it?

**Comment by ValkiryXDA** [comment]
Use
"whereis ajenti"

**Comment by fab4x** [comment]
> 
> 
> I found the file `ajenti.service` at `/lib/systemd/system/` can simple delete it?

I removed the file from my Debian Server and it's still running without any problems. Just make sure you have a backup if anything goes wrong. Better safe than sorry.
