### ISSUE TITLE
Error when trying to load systemd services in Ubuntu 14.04 in elevated mode

### ISSUE THREAD

**Issue by OdinWynd** [ajenti/ajenti#1052]
Request

> GET /api/services/list/systemd

Type

> CalledProcessError

Message

> Command '['systemctl', 'list-unit-files', '--no-legend', '--no-pager', '-la']' returned non-zero exit status 1

Traceback

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
>     result = fx(self, context, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_services/views.py", line 36, in handle_api_list
>     return [self.__service_to_json(svc) for svc in self.managers[manager_id].list()]
>   File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_services/managers/systemd_manager.py", line 21, in list
>     units = [x.split()[0] for x in subprocess.check_output(['systemctl', 'list-unit-files', '--no-legend', '--no-pager', '-la']).splitlines() if x]
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 333, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['systemctl', 'list-unit-files', '--no-legend', '--no-pager', '-la']' returned non-zero exit status 1

**Comment by bytetip2024** [comment]
me too.
