### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by dreamatic** [ajenti/ajenti#1060]
Dear Ajenti Team/Github community,

Installed a clean instance of Ubuntu 16.04.2 LTS on AWS EC2. After following both the automatic and manual install approaches by the letter on clean instances, Ajenti is failing to authenticate when logging in.

Error output is as follows.

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/views/api.py", line 63, in handle_api_auth
    body_data = json.loads(http_context.body)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
`
Please may we have some feedback regarding this? This issue seems to relate to that experienced by others.

![authentication failed](https://cloud.githubusercontent.com/assets/29188392/26767738/f0f09534-49e5-11e7-83af-fb7a9ed67dae.png)

**Comment by NekoTiki** [comment]
Same Problem don't know why, i've test everything (Update python, etc) nothing works pls that's a gobal problem ...

**Comment by alaarihan** [comment]
+1

**Comment by KravtsovVG** [comment]
+1

**Comment by shpigunov** [comment]
+1

**Comment by sitchi** [comment]
+1

**Comment by shuriban** [comment]
+1

**Comment by Eugeny** [comment]
Fixed in 2.1.20
