### ISSUE TITLE
Installing Ajenti 1.X on Debian Stretch fix

### ISSUE THREAD

**Issue by shoujii** [ajenti/ajenti#1062]
Ajenti 1.x doesnt install on Debian Stretch due to missing dependencies.

I figured out how to fix it:
wget -q http://ftp.de.debian.org/debian/pool/main/p/python-reconfigure/python-reconfigure_0.1.74+git49a20890-3_all.deb
wget -q http://ftp.de.debian.org/debian/pool/main/p/python-support/python-support_1.0.15_all.deb

sudo dpkg -i python-reconfigure_0.1.74+git49a20890-3_all.deb 
sudo dpkg -i python-support_1.0.15_all.deb 

apt -y --fix-broken install 
	
wget -q http://repo.ajenti.org/debian/key -O- | apt-key add -
echo "deb http://repo.ajenti.org/debian main main debian" >> /etc/apt/sources.list
apt-get -qq update && apt-get -q -y --assume-yes install ajenti

Hopefully it's working for you too :)

**Comment by gabboman** [comment]
It seems to work in a clean vps with debian stretch, thank you!

EDIT: the panel doesnt seem to work in stretch :(

**Comment by gabboman** [comment]
ok, this works: http://support.ajenti.org/topics/86-resolve-ajenti-blank-screen-on-panel-after-log/

I got it on debian 9!

**Comment by Manuel-Jesus** [comment]
Yeah!!! me too!!
