### ISSUE TITLE
Ajenti Website Stuck On Maintenance Mode?

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#1076]
Hey all, 

I have been trying to setup a website with Ajenti, and they seem to be stuck on maintenance mode, and it's not switched on.  All the checks have passed (NGINX Conf and all the others).  I've tried rebooting, and restarting the websites, though it won't turn off...

Any help?

Liam

**Comment by ghost** [comment]
NVM Fixed it myself.  Something happened with NGINX, IDK what it was, but I did something and it worked haha!

**Comment by CElysee** [comment]
i'm having same issues! what did you do to fix it?

**Comment by ghost** [comment]
@CElysee I'm sorry, but it's been so long since this happened, I can't remember!
