### ISSUE TITLE
installing on a live server

### ISSUE THREAD

**Issue by MarcovanMaanen** [ajenti/ajenti#1080]
Best,

I whant to install Ajenti on a already running server (with websites, databases,etc)
This is a CentOS 7 with Apache 2.4.27 (64), PHP 7 and Varnish and Mariadb 10, memcache.

There is no control panel now and i would like to use Ajenti.
So the question is: Can it be installed on a running server ? or can it only be set-up on a new server.

Does anyone know this ?

Greeting,
Marco.

**Comment by lehthanis** [comment]
I'd like to know this too.  I'm in the same boat.  Also curious abotu Ajenti versus AjentiV differences?

**Comment by c0fe** [comment]
@Marco-PHPJunky It can be installed on a running server, keep in mind this project is abandoned with limited to no support whatsoever.

@lehthanis Ajenti is a basic control panel for the server and Ajenti-V is a web host version of Ajenti, meaning it supports webserver, email server, ftp server and other things in relation to web hosting.

But again this is a dead project and while being open source, it's license is not clear.
