### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by pedromorgan** [ajenti/ajenti#1083]
The MIT license file is absent.

**Comment by alfredocdmiranda** [comment]
Wouldn't be this file? https://github.com/ajenti/ajenti/blob/master/LICENSE

**Comment by lupoDharkael** [comment]
what about this https://github.com/ajenti/ajenti/blob/master/docs/LICENSE ? 
This is confusing.

**Comment by pedromorgan** [comment]
I expect the Licence to be in the "root" of project..
