### ISSUE TITLE
"SSL: WRONG_VERSION_NUMBER" when trying to access admin page (Agenti 1.x) and not work

### ISSUE THREAD

**Issue by jiangshenghui000** [ajenti/ajenti#1097]
======START=========================================================
08.12.2017 10:43 ajenti-panel:105              INFO  Using config file /etc/ajenti/config.json
08.12.2017 10:43 ajenti-panel:130              INFO  Ajenti starting in foreground
08.12.2017 10:43 registry.py:280               DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
08.12.2017 10:43 compat.py:20                  DEBUG Popen: git describe --tags 2> /dev/null
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['lsb_release', '-sd']
08.12.2017 10:43 core.py:60                    INFO  Ajenti 1.2.23.11 running on platform: debian
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin ajenti_org
08.12.2017 10:43 __init__.py:286               DEBUG Preloading plugin dependency: main
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin main
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin ajenti_org
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin apache
08.12.2017 10:43 __init__.py:286               DEBUG Preloading plugin dependency: webserver_common
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin webserver_common
08.12.2017 10:43 __init__.py:286               DEBUG Preloading plugin dependency: services
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin services
08.12.2017 10:43 __init__.py:286               DEBUG Preloading plugin dependency: dashboard
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin dashboard
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin services
08.12.2017 10:43 sm_upstart.py:49              INFO  Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'systemctl']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin webserver_common
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin apache
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'apache2']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin apcups
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'apcaccess']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [apcups] skipping due to BinaryDependency (apcaccess)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin bind9
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'named']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [bind9] skipping due to BinaryDependency (named)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin codemirror
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin configurator
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin cron
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'crontab']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin csf
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'csf']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [csf] skipping due to BinaryDependency (csf)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin ctdb
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'ctdb']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [ctdb] skipping due to BinaryDependency (ctdb)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin db_common
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin dhcpd
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'dhcpd']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin exports
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'nfsstat']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [exports] skipping due to BinaryDependency (nfsstat)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin fail2ban
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'fail2ban-client']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [fail2ban] skipping due to BinaryDependency (fail2ban-client)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin fm
08.12.2017 10:43 __init__.py:286               DEBUG Preloading plugin dependency: tasks
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin tasks
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin fm
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin fstab
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin git
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'git']
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'gitolite']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [git] skipping due to BinaryDependency (gitolite)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin hddtemp
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'hddtemp']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [hddtemp] skipping due to BinaryDependency (hddtemp)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin hdparm
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'hdparm']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [hdparm] skipping due to BinaryDependency (hdparm)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin hosts
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin ipmi
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'ipmitool']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [ipmi] skipping due to BinaryDependency (ipmitool)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin iptables
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'ip6tables']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin lm_sensors
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'sensors']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [lm_sensors] skipping due to BinaryDependency (sensors)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin logs
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin megaraid
08.12.2017 10:43 __init__.py:346               DEBUG  *** [megaraid] skipping due to FileDependency (/opt/MegaRAID/MegaCli/MegaCli)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin memcache
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'memcached']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [memcache] skipping due to BinaryDependency (memcached)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin mongo
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'mongod']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [mongo] skipping due to BinaryDependency (mongod)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin munin
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'munin-cron']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [munin] skipping due to BinaryDependency (munin-cron)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin mysql
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'mysql']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [mysql] skipping due to BinaryDependency (mysql)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin netatalk
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'afpd']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [netatalk] skipping due to BinaryDependency (afpd)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin network
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin nginx
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'nginx']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [nginx] skipping due to BinaryDependency (nginx)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin notepad
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin nsd
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'nsd']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [nsd] skipping due to BinaryDependency (nsd)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin ntpd
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'ntpd']
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [SystemdServiceManager] <ajenti.plugins.services.sm_systemd.SystemdServiceManager object at 0xb4f09d90>
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [SysVInitServiceManager] <ajenti.plugins.services.sm_sysvinit.SysVInitServiceManager object at 0xb4f094b0>
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [ServiceMultiplexor] <ajenti.plugins.services.api.ServiceMultiplexor object at 0xb4f09db0>
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin openvpn
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'openvpn']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [openvpn] skipping due to BinaryDependency (openvpn)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin packages
08.12.2017 10:43 __init__.py:286               DEBUG Preloading plugin dependency: terminal
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin terminal
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin packages
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin plugins
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin power
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'systemctl']
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'pm-hibernate']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin psql
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'psql']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [psql] skipping due to BinaryDependency (psql)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin raid
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'mdadm']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [raid] skipping due to BinaryDependency (mdadm)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin resolv
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin resources
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin rethink
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'rethinkdb']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [rethink] skipping due to BinaryDependency (rethinkdb)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin samba
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'smbd']
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'smbstatus']
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin scripts
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin sensors
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin smartctl
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'smartctl']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [smartctl] skipping due to BinaryDependency (smartctl)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin snmpd
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'snmpd']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [snmpd] skipping due to BinaryDependency (snmpd)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin squid
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'squid3']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [squid] skipping due to BinaryDependency (squid3)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin supervisor
08.12.2017 10:43 compat.py:20                  DEBUG Popen: ['which', 'supervisord']
08.12.2017 10:43 __init__.py:346               DEBUG  *** [supervisor] skipping due to BinaryDependency (supervisord)
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin taskmgr
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin uname
08.12.2017 10:43 __init__.py:297               DEBUG Loading plugin users
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0xb5250590>
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [UI] <ajenti.ui.UI object at 0xb4d768b0>
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout main:file-dialog-save
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout main:file-dialog
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout main:input-dialog
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout main:passwd-main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout ajenti_org:config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout ajenti_org:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout dashboard:dash
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout dashboard:text
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout dashboard:welcome
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout services:bar
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout services:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout services:widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout webserver_common:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout configurator:ad-sync-config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout configurator:ldap-sync-config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout configurator:licensing
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout configurator:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout cron:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout db_common:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout dhcpd:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout dhcpd:options
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout dhcpd:ranges
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout tasks:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout tasks:params-copydir
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout tasks:params-deletedir
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout tasks:params-execute
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout tasks:params-rsync
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout fm:config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout fm:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout fstab:free-widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout fstab:iio-widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout fstab:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout fstab:widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout hosts:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-address
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-custom
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-interface
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-match
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-port
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-ports
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-protocol
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-reject-with
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option-state
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout iptables:option
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout logs:config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout logs:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout network:bit-linux-basic
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout network:bit-linux-dhcp
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout network:bit-linux-ifupdown
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout network:bit-linux-ipv4
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout network:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout network:widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout notepad:config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout notepad:listitem
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout notepad:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout ntpd:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout terminal:config
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout terminal:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout packages:headers
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout packages:installer
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout packages:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout packages:row
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout plugins:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout power:widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout resolv:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout samba:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout scripts:widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout sensors:cpu-line
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout sensors:cpu-widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout sensors:progressbar-widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout sensors:value-widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout taskmgr:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout uname:widget
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout users:main
08.12.2017 10:43 inflater.py:38                DEBUG Precaching layout users:user-list
08.12.2017 10:43 core.py:99                    INFO  Starting server on (u'0.0.0.0', 28000)
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [SessionMiddleware] <ajenti.middleware.SessionMiddleware object at 0xb4acfa70>
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [AuthenticationMiddleware] <ajenti.middleware.AuthenticationMiddleware object at 0xb4a657f0>
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [CentralDispatcher] <ajenti.routing.CentralDispatcher object at 0xb4a658f0>
08.12.2017 10:43 core.py:135                   INFO  SSL enabled: /etc/ajenti/ajenti.pem
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [IPCServer] <ajenti.ipc.IPCServer object at 0xb4a65b70>
08.12.2017 10:43 __init__.py:207               DEBUG Root context instantiated [Licensing] <ajenti.licensing.Licensing object at 0xb4a65c70>
08.12.2017 10:43 feedback.py:30                DEBUG Feedback >> ping ({'edition': 'vanilla', 'version': '1.2.23.11', 'os': 'debian', 'id': 293639})
08.12.2017 10:43 connectionpool.py:188         INFO  Starting new HTTP connection (1): meta.ajenti.org
08.12.2017 10:43 connectionpool.py:362         DEBUG "POST /api/v2/ping HTTP/1.1" 200 36
08.12.2017 10:43 feedback.py:35                DEBUG Feedback << {"status": "ok"}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
<Greenlet at 0xb4a9e120L: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0xb4a7b810L fileno=[Errno 9] Bad file )> failed with SSLError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
<Greenlet at 0xb4a9e170L: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0xb4af1230L fileno=[Errno 9] Bad file )> failed with SSLError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
<Greenlet at 0xb4a9e170L: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0xb4a7b810L fileno=[Errno 9] Bad file )> failed with SSLError
======END==========================================================
Please help me !!!

**Comment by arustler** [comment]
I had the same issue.
If you you binding ajenti to a socket like /var/run/ajenti.sock and requesting the Page via a Proxy then you can turn off SSL in ajenti.

Browser --SSL--> NGinX (listens to 443 SSL) --proxy_pass http://unix:/var/run/ajenti.sock--> ajenti.sock

See [Ajenti behind NGinX](http://support.ajenti.org/forums/5-kb/topics/1129-ajenti-behind-nginx/)

Worked for me
