### ISSUE TITLE
Ajenti v2 and ajenti v

### ISSUE THREAD

**Issue by digitalit** [ajenti/ajenti#1101]
Hi,

Is it possible to use version 2 and ajenti v or do i have to use version 1?

I could do without ajenti v as long as i can get mysql, ngingx, supervisor and lets encrypt to work but i haven't so far.

I really like the v2 responsiveness. 

I don't want any apache or php since im running node.js and only start separate node processes for each site and then use nginx proxy to point the domain to right process.

Any tip on this?

**Comment by ThienNTran73** [comment]
You need Ajenti 1.
