### ISSUE TITLE
Problems in Ubuntu 17.10

### ISSUE THREAD

**Issue by valmynd** [ajenti/ajenti#1110]
Hello,

I followed your instructions ([1](http://docs.ajenti.org/en/latest/man/install.html),[2](http://docs.ajenti.org/en/latest/man/run.html)) closely and any way I tried to run it did have problems.

## running it via `service ajenti restart`

> $ service ajenti restart
> Failed to restart ajenti.service: Unit ajenti.service not found.

## running it via `ajenti-panel -v` (with or without "-v")

... when I open localhost:8000 in the browser it loads forever. 
Output in console:

> $ sudo ajenti-panel -v
> [sudo] password for ...: 
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
> 01.02.2018 14:41  [...     2705]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
> 01.02.2018 14:41  [...     2705]        compat.py:19    DEBUG    Popen: git describe --tags 2> /dev/null
> 01.02.2018 14:41  [...     2705]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
> 01.02.2018 14:41  [master  2705]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
> 01.02.2018 14:41  [master  2705]          core.py:77    WARN   Debug mode
> 01.02.2018 14:41  [master  2705]          core.py:90    INFO   Ajenti Core 2.1.24
> 01.02.2018 14:41  [master  2705]          core.py:91    INFO   Detected platform: debian / Ubuntu 17.10
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/bin
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python2.7
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python2.7/plat-x86_64-linux-gnu
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python2.7/lib-tk
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python2.7/lib-dynload
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/lib/python2.7/dist-packages
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python2.7/dist-packages
> 01.02.2018 14:41  [master  2705]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python2.7/dist-packages/gtk-2.0
> 01.02.2018 14:41  [master  2705]       plugins.py:277   INFO   Discovered 12 plugins
> 01.02.2018 14:41  [master  2705]       plugins.py:325   DEBUG  Resolved load order for 12 plugins: ['core', 'passwd', 'plugins', 'dashboard', 'services', 'ace', 'terminal', 'packages', 'filesystem', 'settings', 'notepad', 'filemanager']
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "core"
> 01.02.2018 14:41  [master  2705]          jadi.py:136   DEBUG  Registering [aj.plugins.core.api.sidebar.SidebarItemProvider] (interface)
> 01.02.2018 14:41  [master  2705]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.sidebar.Sidebar] (service)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.main.Permissions] (implementation of [aj.auth.PermissionProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.navbox.Navbox] (service)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.api.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.config.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.main.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.resource_server.ResourcesHandler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.push.Push] (service)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.push.PushSocket] (implementation of [aj.api.http.SocketEndpoint])
> 01.02.2018 14:41  [master  2705]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.tasks.TasksService] (service)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.core.views.tasks.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "passwd"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.passwd.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "plugins"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.plugins.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]        compat.py:19    DEBUG  Popen: ['/sbin/ldconfig', '-p']
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.plugins.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "dashboard"
> 01.02.2018 14:41  [master  2705]          jadi.py:136   DEBUG  Registering [aj.plugins.dashboard.api.Widget] (interface)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.cpu.CPUWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.hostname.HostnameWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.loadavg.LoadAverageWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.memory.MemoryWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.dashboard.widgets.uptime.UptimeWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "services"
> 01.02.2018 14:41  [master  2705]          jadi.py:136   DEBUG  Registering [aj.plugins.services.api.ServiceManager] (interface)
> 01.02.2018 14:41  [master  2705]        compat.py:19    DEBUG  Popen: ['which', 'systemctl']
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.services.managers.systemd_manager.SystemdServiceManager] (implementation of [aj.plugins.services.api.ServiceManager])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.services.managers.sysv_manager.SysVServiceManager] (implementation of [aj.plugins.services.api.ServiceManager])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.services.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.services.main.Permissions] (implementation of [aj.auth.PermissionProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.services.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "ace"
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "terminal"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.terminal.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.terminal.main.Permissions] (implementation of [aj.auth.PermissionProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:70    DEBUG  Registering [aj.plugins.terminal.manager.TerminalManager] (service)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.terminal.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.terminal.views.Socket] (implementation of [aj.api.http.SocketEndpoint])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "packages"
> 01.02.2018 14:41  [master  2705]          jadi.py:136   DEBUG  Registering [aj.plugins.packages.api.PackageManager] (interface)
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.packages.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.packages.main.Permissions] (implementation of [aj.auth.PermissionProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.packages.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]        compat.py:19    DEBUG  Popen: lsb_release -a
> 01.02.2018 14:41  [master  2705]      __init__.py:70    DEBUG  lzma module is not available
> 01.02.2018 14:41  [master  2705]      __init__.py:60    DEBUG  Registered VCS backend: git
> 01.02.2018 14:41  [master  2705]      __init__.py:60    DEBUG  Registered VCS backend: hg
> 01.02.2018 14:41  [master  2705]      __init__.py:60    DEBUG  Registered VCS backend: svn
> 01.02.2018 14:41  [master  2705]      __init__.py:60    DEBUG  Registered VCS backend: bzr
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.packages.managers.pip_manager.PIPPackageManager] (implementation of [aj.plugins.packages.api.PackageManager])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "filesystem"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.filesystem.main.Permissions] (implementation of [aj.auth.PermissionProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.filesystem.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "settings"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.settings.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.settings.views.Handler] (implementation of [aj.api.http.HttpPlugin])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "notepad"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.notepad.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]       plugins.py:348   DEBUG  Importing plugin "filemanager"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.filemanager.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "core"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "passwd"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "plugins"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "dashboard"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "services"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.services.widget.ServiceWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "ace"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "terminal"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.terminal.widget.ScriptWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "packages"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "filesystem"
> 01.02.2018 14:41  [master  2705]          jadi.py:164   DEBUG  Registering [aj.plugins.filesystem.widget.DiskWidget] (implementation of [aj.plugins.dashboard.api.Widget])
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "settings"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "notepad"
> 01.02.2018 14:41  [master  2705]       plugins.py:358   DEBUG  Initializing plugin "filemanager"
> 01.02.2018 14:41  [master  2705]       plugins.py:345   INFO   Loaded 12 plugins
> 01.02.2018 14:41  [master  2705]          core.py:121   INFO   Binding to [0.0.0.0]:8000
> 01.02.2018 14:41  [master  2705]          gipc.py:271   DEBUG  Invoke target `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7f4d06edd5d0>>` in child process.
> 01.02.2018 14:41  [master  2705]          gipc.py:449   DEBUG  SIGCHLD watcher for 2717 started.
> 01.02.2018 14:41  [master  2705]          gipc.py:289   DEBUG  Invalidate <_GIPCWriter_f478a2 fd: 10> in parent.
> 01.02.2018 14:41  [master  2705]          gipc.py:583   DEBUG  Invalidating <_GIPCWriter_f478a2 fd: 10> ...
> 01.02.2018 14:41  [master  2705]          gipc.py:289   DEBUG  Invalidate <_GIPCReader_fa08b9 fd: 11> in parent.
> 01.02.2018 14:41  [master  2705]          gipc.py:583   DEBUG  Invalidating <_GIPCReader_fa08b9 fd: 11> ...
> 01.02.2018 14:41  [master  2705]          gate.py:47    DEBUG  Started child process 2717
> 01.02.2018 14:41  [master  2705]          core.py:184   INFO   SSL enabled
> 01.02.2018 14:41  [...     2717]          gipc.py:308   DEBUG    _child start. target: `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7f4d06edd5d0>>`
> 01.02.2018 14:41  [...     2717]          gipc.py:320   DEBUG    Delete current hub's threadpool.
> 01.02.2018 14:41  [...     2717]          gipc.py:329   DEBUG    Destroy hub and default loop.
> 01.02.2018 14:41  [...     2717]          gipc.py:334   DEBUG    Created new hub and default event loop.
> 01.02.2018 14:41  [...     2717]          gipc.py:341   DEBUG    Invalidate <_GIPCReader_98eeaf fd: 7> in child.
> 01.02.2018 14:41  [...     2717]          gipc.py:594   DEBUG    Legitimate <_GIPCReader_98eeaf fd: 7> for current process.
> 01.02.2018 14:41  [...     2717]          gipc.py:583   DEBUG    Invalidating <_GIPCReader_98eeaf fd: 7> ...
> 01.02.2018 14:41  [...     2717]          gipc.py:341   DEBUG    Invalidate <_GIPCWriter_bf89fd fd: 12> in child.
> 01.02.2018 14:41  [...     2717]          gipc.py:594   DEBUG    Legitimate <_GIPCWriter_bf89fd fd: 12> for current process.
> 01.02.2018 14:41  [...     2717]          gipc.py:583   DEBUG    Invalidating <_GIPCWriter_bf89fd fd: 12> ...
> 01.02.2018 14:41  [...     2717]          gipc.py:594   DEBUG    Legitimate <_GIPCWriter_f478a2 fd: 10> for current process.
> 01.02.2018 14:41  [...     2717]          gipc.py:359   DEBUG    Handle `<_GIPCWriter_f478a2 fd: 10>` is now valid in child.
> 01.02.2018 14:41  [...     2717]          gipc.py:594   DEBUG    Legitimate <_GIPCReader_fa08b9 fd: 11> for current process.
> 01.02.2018 14:41  [...     2717]          gipc.py:359   DEBUG    Handle `<_GIPCReader_fa08b9 fd: 11>` is now valid in child.
> 01.02.2018 14:41  [rstrct  2717]          gate.py:110   INFO     New worker "restricted session" PID 2717, EUID 0, EGID 0
> 01.02.2018 14:41  [rstrct  2717]          gate.py:110   INFO     Worker 2717 is demoting to UID 65534 / GID 65534...
> 01.02.2018 14:41  [rstrct  2717]          gate.py:110   INFO     ...done, new EUID 65534 EGID 65534
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
>     result = self._run(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
>     return handle(*args_tuple)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 175, in wrap_socket_and_handle
>     return self.handle(ssl_socket, address)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
>     handler.handle()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 454, in handle
>     result = self.handle_one_request()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 637, in handle_one_request
>     self.requestline = self.read_requestline()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 585, in read_requestline
>     line = self.rfile.readline(MAX_REQUEST_LINE)
>   File "/usr/lib/python2.7/socket.py", line 480, in readline
>     data = self._sock.recv(self._rbufsize)
>   File "/usr/local/lib/python2.7/dist-packages/aj/util/sslsocket.py", line 103, in recv
>     return self.__iowait(self._connection.recv, bufsiz, flags)
>   File "/usr/local/lib/python2.7/dist-packages/aj/util/sslsocket.py", line 50, in __iowait
>     data = io_func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1684, in recv
>     self._raise_ssl_error(self._ssl, result)
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
>     _raise_current_error()
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
>     raise exception_type(errors)
> Error: [('SSL routines', 'ssl3_get_record', 'http request')]
> Thu Feb  1 14:47:14 2018 <Greenlet at 0x7f4d070a4410: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f4d07d005d0 fileno=[Errno 9] Bad fi)> failed with Error
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
>     result = self._run(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
>     return handle(*args_tuple)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 175, in wrap_socket_and_handle
>     return self.handle(ssl_socket, address)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
>     handler.handle()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 454, in handle
>     result = self.handle_one_request()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 637, in handle_one_request
>     self.requestline = self.read_requestline()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 585, in read_requestline
>     line = self.rfile.readline(MAX_REQUEST_LINE)
>   File "/usr/lib/python2.7/socket.py", line 480, in readline
>     data = self._sock.recv(self._rbufsize)
>   File "/usr/local/lib/python2.7/dist-packages/aj/util/sslsocket.py", line 103, in recv
>     return self.__iowait(self._connection.recv, bufsiz, flags)
>   File "/usr/local/lib/python2.7/dist-packages/aj/util/sslsocket.py", line 50, in __iowait
>     data = io_func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1684, in recv
>     self._raise_ssl_error(self._ssl, result)
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
>     _raise_current_error()
>   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
>     raise exception_type(errors)
> Error: [('SSL routines', 'ssl3_get_record', 'http request')]
> Thu Feb  1 14:47:18 2018 <Greenlet at 0x7f4d070a4410: _handle_and_close_when_done(<bound method SocketIOServer.wrap_socket_and_handl, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f4d06f05950 fileno=[Errno 9] Bad fi)> failed with Error

My recent bash_history (the installation went fine):

> sudo apt-get install build-essential python-pip python-dev python-lxml libffi-dev libssl-dev libjpeg-dev libpng-dev uuid-dev python-dbus
> sudo pip3 install ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins
> sudo pip install 'setuptools>=0.6rc11' 'pip>=6' wheel
> sudo pip install ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins
> sudo pip install ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins ajenti.plugin.filemanager ajenti.plugin.notepad ajenti.plugin.packages ajenti.plugin.services ajenti.plugin.terminal
> service ajenti restart
> python -c "import gevent.ssl"

**Comment by jonatino** [comment]
@valmynd did you fix this issue? I have the same thing.
