### ISSUE TITLE
How to uninstall Ajenti???

### ISSUE THREAD

**Issue by f5Qz** [ajenti/ajenti#1113]
I tried:
https://support.ajenti.org/forums/1-general/topics/1399-how-to-uninstall-ajenti-on-ubuntu-1604/

And:
https://support.ajenti.org/forums/1-general/topics/529-uninstall/

And:
https://github.com/ajenti/ajenti/issues/1051

No mention whatsoever in the documentation:
http://docs.ajenti.org/en/latest/search.html?q=uninstall&check_keywords=yes&area=default

The panels keeps running, feels like my system is polluted now a shitload of unwanted stuff. Isnt there an official Docker or SNAP?

**Comment by codenull** [comment]
You can use:
```
pip freeze | grep aj
pip uninstall
```

Some traces will still remain. But I did not find another way to remove it.

**Comment by PWNYYY** [comment]
#!/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

DISTRO=
OS=

if grep 'Debian' /etc/issue > /dev/null 2>&1 ; then
    OS=debian
    DISTRO=debian
fi

if grep 'Ubuntu' /etc/issue > /dev/null 2>&1 ; then
    OS=debian
    DISTRO=ubuntu
fi

if grep 'ubuntu' /etc/os-release > /dev/null 2>&1 ; then
    OS=debian
    DISTRO=ubuntu
fi

echo ":: OS: $OS"
echo ":: Distro: $DISTRO"

/etc/init.d/ajenti stop
systemctl stop ajenti

echo ":: Uninstalling Ajenti"
/usr/bin/yes | `which pip` uninstall ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins ajenti.plugin.notepad ajenti.plugin.terminal ajenti.plugin.filemanager ajenti.plugin.packages ajenti.plugin.services || exit 1

# ----------------

echo ":: Uninstalling initscript"

if [ -f /etc/init/ajenti.conf ] ; then
    rm /etc/init/ajenti.conf /lib/systemd/system/ajenti.service /etc/init.d/ajenti /var/run/ajenti.pid 2>/dev/null
    rm -fr /etc/ajenti /var/log/ajenti /sys/fs/cgroup/pids/system.slice/ajenti.service /sys/fs/cgroup/devices/system.slice/ajenti.service /sys/fs/cgroup/systemd/system.slice/ajenti.service 2>/dev/null
fi

echo ':: Ajenti Uninstalled.'
