### ISSUE TITLE
Package reconfigure-0.1.81-1.noarch.rpm is not signed

### ISSUE THREAD

**Issue by XjSv** [ajenti/ajenti#1114]
When I try to update the reconfigure package I always get the same error, saying that the package is not signed. 

![console-output](https://user-images.githubusercontent.com/107681/35933068-8831e7c0-0c07-11e8-9563-8def0aa138d9.png)

**Comment by eGeekster** [comment]
Just add --nogpgcheck and it will proceed just fine.

**Comment by NCC-Lykos** [comment]
While the above works....It isn't really proper....

**Comment by gdwnet** [comment]
Absolutely right. yum remove reconfigure ajenti worked for me, I will not use an application that cannot take security seriously.
