### ISSUE TITLE
Is this project DEAD? 

### ISSUE THREAD

**Issue by nabtron** [ajenti/ajenti#1116]
Why isn't there any progress on this project for last many years? it was an amazing project!

**Comment by wrrr** [comment]
If  you see there is now Version 2 (ajenti.org) and constant updates to core in back end. I think maybe the  updates are not always published immediately on Git, we are currently at v1.2.23.11 and using Ajenti -V as web hosting control panel for 3 years.

**Comment by briankb** [comment]
I installed it a few days ago from the "Install Instructions" which installs from MASER branch and not from v1.x branch and the initial control panel was minimal and I uninstalled. I'm back today after trying a few other panels and this one keeps coming up as good but I think the layout and Install Instructions on ajenti.org is confusing. The screenshots shown on /ajenti/ajenti look like they are from Ajenti V for 1.x. (as shown on the site).

**So does Ajenti V for 1.x also work on Ajenti 2?**

**Comment by baoang** [comment]
Really confusing. There are Ajenti 1,2,V,Core. I just want find a panel, similar thing to Vesta, CentiminMod, etc to install and manage my websites. So, where should I start exactly?

**Comment by c0fe** [comment]
@Eugeny can you provide some clarification on this?

**Comment by c0fe** [comment]
@Eugeny if I can give my two cents (if they matter), this project is unique in that it was not a hosting panel. It was an administrative panel, I would have loved it more if it would provide one stop management for multiple servers and docker/kubernetes.

**Comment by imdevine** [comment]
@Eugeny are the following issues fixed?
https://medium.com/stolabs/security-issues-on-ajenti-d2b7526eaeee

**Comment by aalfiann** [comment]
Ajenti is not dead. Ajenti still updated, but the dev is not publishing to github anymore.

You can see the updated version is here >> http://realrepo.ajenti.org:8888/debian/

**Comment by aalfiann** [comment]
@Eugeny create update only to fix critical issues is enough bro. It doesn't make this project dead. I really appreciated.

**Comment by aalfiann** [comment]
@imdevine, that issues are from ajenti UI. Im not worry about it, just change default port for ajenti, install fail2ban and add cors also csp.

**Comment by papatistos** [comment]
Any suggestions regarding alternatives that are similar to Ajenti?

**Comment by pjz** [comment]
If this were more lively, I think it could give webmin a run for its money.

**Comment by afidegnum** [comment]
@Eugeny don't give up on this project. so far that's the top admin panel I have come across so far. what does it need to become live again?

**Comment by Eugeny** [comment]
@afidegnum developers. @kiarn is the only one right now, trying to bring the project up to date with Python 3.

**Comment by afidegnum** [comment]
Ah, i m really happy for the response, i am also going to put all my effort to it. what are the available milestones to accomplish so i can follow along and commit ?

**Comment by Eugeny** [comment]
There is no specific roadmap, but the issues list might be a good starting point

**Comment by afidegnum** [comment]
ok
