### ISSUE TITLE
Ubuntu 16.04 install fails due pip uninstall confirmation

### ISSUE THREAD

**Issue by BlackWiCKED** [ajenti/ajenti#1119]
When using the automatic installation script on an Ubuntu 16.04 system:

`curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -`

It arrives to a part when it tries to uninstall a package called **_gevent-socketio_** and fails, because that command requires a confirmation before it could continue: `Proceed (y/n)?`

So practically the whole bash script goes crazy after this step. There is a solution though - manually removing this package and re-run the script.

Another solution is to fix the automatic installation script itself by adding a **-y** flag to that command, see [this](https://stackoverflow.com/a/33557016) comment. I can create a PR if needed.

**Comment by Eugeny** [comment]
Thanks for looking into this, a PR would be much appreciated!
