### ISSUE TITLE
Question about Ajenti 2 plugins

### ISSUE THREAD

**Issue by ZaLiTHkA** [ajenti/ajenti#1123]
Just out of curiosity, are the plugins for Ajenti 1.x going to be ported over to 2.x?

I installed it this evening as per the instructions I got from the main website (with great difficulty, I must add - the default script doesn't like Ubuntu 16.04 when Upstart *is* available), in the hopes of using it to manage a few of the services on my local home server.

One of the services *I'd like* to manage is Samba, but I can't seem to find any information on a plugin for this in Ajenti 2.. Version 1 has this, so am I missing something here?

**Comment by ZaLiTHkA** [comment]
right, I suspected something along those lines... nice to have confirmation at least, thanks for letting me know. :)

**Comment by ovizii** [comment]
Is there a list of features or plugins of v2 available somewhere? The website has very minimal information :-/
