### ISSUE TITLE
Ajenti 1.x on Ubuntu 18.04

### ISSUE THREAD

**Issue by dkuzmenchuk** [ajenti/ajenti#1125]
Unable to install Ajenti 1.x on Ubuntu 18.04

Terminal output:
> Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation
The following packages have unmet dependencies:
 ajenti : Depends: python-imaging but it is not installable
E: Unable to correct problems, you have held broken packages.

What can we do to install Ajenti 1.x on Ubuntu 18.04?
Can we install ajenti from sources?

**Comment by Goten87** [comment]
this is becose of the package python-imaging is having a new name on 18.04
its now python-pil
i think they need to look into this to fix it sins the old package is gone

**Comment by ohot2015** [comment]
up

**Comment by ghost** [comment]
Having this exact same issue. up

**Comment by ValkiryXDA** [comment]
Same issue, wish they would get around to re-naming the package and releasing it...

**Comment by markdegrootnl** [comment]
Same issue. Here is a workaround:
```
sudo apt-get install python python-support python-lxml python-gevent openssl python-gevent-socketio python-psutil python-reconfigure python-daemon python-passlib python-requests python-dbus apt-show-versions python-catcher python-exconsole python-ldap python-pil

wget http://realrepo.ajenti.org:8888/ng/debian/pool/main/a/ajenti/ajenti_1.2.23.13_all.deb

sudo dpkg --ignore-depends=python-imaging -i ajenti_1.2.23.13_all.deb
```

**Comment by gb-123** [comment]
> sudo apt-get install python python-support python-lxml python-gevent openssl python-gevent-socketio python-psutil python-reconfigure python-daemon python-passlib python-requests python-dbus apt-show-versions python-catcher python-exconsole python-ldap python-pil

> wget http://realrepo.ajenti.org:8888/ng/debian/pool/main/a/ajenti/ajenti_1.2.23.13_all.deb

> sudo  dpkg --ignore-depends=python-imaging -i ajenti_1.2.23.13_all.deb


The above doesn't seem to work.

**Comment by markdegrootnl** [comment]
What error did you get?

**Comment by dkuzmenchuk** [comment]
Hi, guys
I found a way to install Ajenti 1.x on Ubuntu 18.04.

```
apt upgrade
apt-get install python-pillow
wget http://security.ubuntu.com/ubuntu/pool/universe/p/pillow/python-imaging_4.1.1-3build2_all.deb
dpkg -i python-imaging_4.1.1-3build2_all.deb
wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh
```


Hope, it'll be helpful

**Comment by gb-123** [comment]
Thanks. I can confirm that dkuzmenchuk's method works.

Thanks again.

@markdegrootnl : I dont remember the error correctly, but your method has something to do with packages. Doesn't seem to install on my VPS.

**Comment by bjornbouetsmith** [comment]
Yeah @dkuzmenchuk 's method works, but if you have had ajenti2 installed first, then you need to remove the service script and run a reconfigure, i.e. 
sudo rm /lib/systemd/system/ajenti.service
sudo dpkg-reconfigure ajenti
sudo service ajenti restart

**Comment by jmutai** [comment]
I finally got it to work on Ubuntu 18.04 using the following guide:

https://computingforgeeks.com/how-to-install-ajenti-control-panel-on-ubuntu-18-04-lts/

**Comment by redukr** [comment]
Apr 24 16:02:13 backend systemd[1]: Starting Ajenti panel...
Apr 24 16:02:13 backend python[9543]: Traceback (most recent call last):
Apr 24 16:02:13 backend python[9543]:   File "/usr/local/bin/ajenti-panel", line 112, in <module>
Apr 24 16:02:13 backend python[9543]:     if not os.path.exists(config_path):
Apr 24 16:02:13 backend python[9543]:   File "/usr/lib/python2.7/genericpath.py", line 26, in exists
Apr 24 16:02:13 backend python[9543]:     os.stat(path)
Apr 24 16:02:13 backend python[9543]: TypeError: coercing to Unicode: need string or buffer, NoneType found
Apr 24 16:02:13 backend systemd[1]: ajenti.service: Control process exited, code=exited status=1
Apr 24 16:02:13 backend systemd[1]: ajenti.service: Failed with result 'exit-code'.
Apr 24 16:02:13 backend systemd[1]: Failed to start Ajenti panel.

**Comment by wahyurc** [comment]
> python-imaging_4.1.1-3build2_all.deb


> Hi, guys
> I found a way to install Ajenti 1.x on Ubuntu 18.04.
> 
> ```
> apt upgrade
> apt-get install python-pillow
> wget http://security.ubuntu.com/ubuntu/pool/universe/p/pillow/python-imaging_4.1.1-3build2_all.deb
> dpkg -i python-imaging_4.1.1-3build2_all.deb
> wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh
> ```
> 
> Hope, it'll be helpful

not work anymore... that **python-imaging_4.1.1-3build2_all.deb** has been deleted.

**Comment by splaquet** [comment]
i found references to the older files here:
[https://launchpad.net/ubuntu/+source/pillow/4.1.1-3build2/+build/13243580](https://launchpad.net/ubuntu/+source/pillow/4.1.1-3build2/+build/13243580)

direct link/download:
[https://launchpad.net/ubuntu/+source/pillow/4.1.1-3build2/+build/13243580/+files/python-imaging_4.1.1-3build2_all.deb](https://launchpad.net/ubuntu/+source/pillow/4.1.1-3build2/+build/13243580/+files/python-imaging_4.1.1-3build2_all.deb)

**Comment by Ranp007** [comment]
Hi, guys
I was able to install with the help of "splaquet"

I changed the file path...

apt upgrade
apt-get install python-pillow
wget https://launchpad.net/ubuntu/+source/pillow/4.1.1-3build2/+build/13243580/+files/python-imaging_4.1.1-3build2_all.deb
dpkg -i python-imaging_4.1.1-3build2_all.deb
wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh

Thanks splaquet
Running on Ubuntu 18.04.3 LTS

**Comment by fernandoc2021** [comment]
> I finally got it to work on Ubuntu 18.04 using the following guide:
> 
> https://computingforgeeks.com/how-to-install-ajenti-control-panel-on-ubuntu-18-04-lts/

No longer!! that python-imaging version is not available.

**Comment by koraysels** [comment]
i was able to do this with `http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/p/pillow/python-imaging_3.1.2-0ubuntu1.1_all.deb`

**Comment by alphacentauri82** [comment]
How do you uninstall it though?

**Comment by relnofollow** [comment]
> i was able to do this with `http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/p/pillow/python-imaging_3.1.2-0ubuntu1.1_all.deb`

Thank you, it worked. I used updated @dkuzmenchuk script:
```
apt upgrade
apt-get install python-pillow
wget http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/p/pillow/python-imaging_3.1.2-0ubuntu1.1_all.deb
dpkg -i python-imaging_3.1.2-0ubuntu1.1_all.deb
wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh
```

**Comment by zohooriandotcom** [comment]
**Please try this: (step by step)**
`apt-get install python-pillow`
`wget http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/p/pillow/python-imaging_3.1.2-0ubuntu1.1_all.deb`
`dpkg -i python-imaging_3.1.2-0ubuntu1.3_all.deb`
`wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh`

Good Luck!

**Comment by bakdakonusuruz** [comment]
> **Updated URL for python imaging since the previous posts didn't work**
> 
> **Please try this: (step by step)**
> `apt-get install python-pillow`
> ~`wget http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/p/pillow/python-imaging_3.1.2-0ubuntu1.1_all.deb`~
> `wget http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/p/pillow/python-imaging_3.1.2-0ubuntu1.3_all.deb`
> `dpkg -i python-imaging_3.1.2-0ubuntu1.3_all.deb`
> `wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh`

It gave some dependency errors and I run "apt --fix-broken install" command. Than I run installation command and it works.
(Ubuntu 18.04.3)

**Comment by bmelim** [comment]
Add deb http://security.ubuntu.com/ubuntu xenial-security main universe to your sources.list
echo "deb http://security.ubuntu.com/ubuntu xenial-security main universe" | sudo tee -a /etc/apt/sources.list

Then 
sudo apt-get update && sudo apt-get install ajenti

Worked just fine for me
