### ISSUE TITLE
clean centOS7,can't login ,user name or passwd fail

### ISSUE THREAD

**Issue by WXpiero** [ajenti/ajenti#1128]
Ajenti will be listening at HTTP port 8000
Log in with your root password or another OS user

this is what ajenti1.X installation told me,but my centos root passwd failed.and i've try root/admin,still not work.
I entered /etc/ajenti/ directory,but did not see config.json,only a file named config.yml,and there is no place marked about username or password to replace.
i try to use "ajenti-panel -v --autologin" command,in the end it show's:"08.05.2018 16:53  [master 11529]          core.py:125   ERROR  Could not bind: [Errno 98],address is taken"
somebody help me plz

**Comment by armnetworking** [comment]
I have encountered a similar issue, on CentOS 6.10 but worked out with the username and password:
root
admin

Apparently those are the default ones... sad they are not referenced anywhere

**Comment by sheldonl3** [comment]
I using ubuntu 18.04,have same problem

**Comment by wrrr** [comment]
If you don't see see config.json in /etc/ajenti your installation failed. We use Ubuntu 18.04 with an NGINX webserver never an issue like this.

**Comment by WXpiero** [comment]
> If you don't see see config.json in /etc/ajenti your installation failed. We use Ubuntu 18.04 with an NGINX webserver never an issue like this.

If NGINX preinstall is mandatory required,this sentence should change on feature highlights description:"Picks up your current configuration and works on your existing system as-is, without any preparation."

**Comment by wrrr** [comment]
I did not say NGINX is mandatory, just our experience. NGINX is excellent webserver for reverse proxy, speed and ease of use IMO
