### ISSUE TITLE
project death?

### ISSUE THREAD

**Issue by Goten87** [ajenti/ajenti#1129]
is ajenti death or somthing sins there are no new updates for like 2 months ?

**Comment by Fenny** [comment]
Ajenti is outdated and not safe for production anymore

**Comment by Goten87** [comment]
Do u have a alternative?

**Comment by ohkeenan** [comment]
There really is nothing as good as Ajenti + V available AFAIK (open source). Really sad and tbh with the rise of SaaS it's not much of a surprise either. Best of luck.

**Comment by aalfiann** [comment]
Ajenti is not dead. Ajenti still updated, but the dev is not publishing to github anymore. 

You can see the updated version is here >> http://realrepo.ajenti.org:8888/debian/

**Comment by Goten87** [comment]
why is he not publishing to git ? is that not what opensource means working on it together

**Comment by Eugeny** [comment]
This is the one and only code repo for Ajenti itself. Ajenti V code is located at https://github.com/eugeny/ajenti-v

**Comment by Eugeny** [comment]
The project itself is in a maintenance mode, with only security issues being fixed.

**Comment by mammuthus** [comment]
Rest in peace, sweet prince.
There is no other panel like Ajenti now.

**Comment by samayo** [comment]
So what is the conclusion of this debate? It seems like Ajenti doesn't seem to be quite dead yet, but on the other hand the author is keeping his activity behind the curtain, and only to maintain security fixes. It's like if Ajenti was a person who has a disease with 50% mortality.
