### ISSUE TITLE
site not run

### ISSUE THREAD

**Issue by spinnerthisar** [ajenti/ajenti#1137]
some sites are no running ....wordpress says install me .. after that dont show any information

**Comment by wrrr** [comment]
That a WordPress error not Ajenti. You probably have a broken theme in the /wp-content/theme folder.

**Comment by MaximKiselev** [comment]
@spinnerthisar 1) check your database access, 2) check that folder of site has right read/write rules (click set privs on folder on site tab in ajenti panel). 3) check that you have wp-config.php in root folder of site
Good luck! 🤞
