### ISSUE TITLE
Ajenti 2 no file create or upload

### ISSUE THREAD

**Issue by aikajee** [ajenti/ajenti#1144]
Ajenti 2 on Debian 8 (Jessie) and Debian 9 (Stretch). Clicking on Upload link in File Manager does nothing - upload dialog box does not open.  On file create, dialog box does popup, but no file is created. I am able to create file using terminal window.

**Comment by Shihira** [comment]
Confirmed on Archlinux, using manual build of latest master branch. So it seemed not implemented?

**Comment by Shihira** [comment]
The uploading issue is yet another easy to fix problem. Just modify again the `index.html`, changing:
```
<a flow-btn class="btn btn-default btn-flat" test-bind="uploadButton" translate>Upload</a>
```
to
```
<span flow-btn class="btn btn-default btn-flat" test-bind="uploadButton" translate>Upload</span>
```
to enable ng-flow.
