### ISSUE TITLE
ajenti not forwarding to node.js port

### ISSUE THREAD

**Issue by cryptopool-builders** [ajenti/ajenti#1157]
I came across this control panel and was hoping that I can use it to host multiple node.js each with their own sub domain on a single server. But I am seem to be having and issue. 

So I installed the required components and followed the guide https://support.ajenti.org/knowledge-bases/5/articles/1123-setting-up-a-nodejs-website-with-ajenti-v-keystone-example

the issue is when i go to my.domain.com i get a 503 Service Unavailable error. 

when I go to my.domain.com:3001 the app loads fine. 

the site is enabled maintenance mode is off im not sure where the issue is

**Comment by wrrr** [comment]
Did you point an A record for the subdomain to your server IP and/or a CNAME for www. I would imagine you did if the port is working but just to be sure why I asked.

**Comment by cryptopool-builders** [comment]
yes it is pointed, like i said in the setup if I go to my.domain.com I get the ajenti 503 message that the site is in maintenance mode. If I go to my.domain.com:3001 the site loads just fine.

**Comment by wrrr** [comment]
Ok, that's why I asked, to be double sure. There is a maintenance mode tickbox in the Ajenti -v panel (-v = website(s) plugin). Are you using -v too?

**Comment by cryptopool-builders** [comment]
Yes the tick box is removed,

**Comment by wrrr** [comment]
I'm using Ubuntu (16.04.x) - I know you said you put your domains in your dns. So in Ajenti you have the sub-domain identified similar to:
![image](https://user-images.githubusercontent.com/4523993/53178222-71748c80-35bf-11e9-9766-7b2e4b1b763b.png)

And at your authoritative DNS provider your sub-domains pointing to your server too. (obviously mine don't match.

![image](https://user-images.githubusercontent.com/4523993/53178290-9406a580-35bf-11e9-8a1e-74fec1ddebbb.png)
