### ISSUE TITLE
Cannot retrieve aviable plugins, JSON error

### ISSUE THREAD

**Issue by wirehack7** [ajenti/ajenti#1160]
I installed Ajenti on a fresh **Ubuntu 18.04.2 LTS** server (automatic install). Whenever I open the plugins page and the system is trying to retrieve the JSON file for the aviable plugins list, I'll get that error in log:

```2019-02-25 16:41:57,115 WARNING : Endpoint error at /api/plugins/repo/list: No JSON object could be decoded```

Is this a common problem? I disabled any firewall for testing purposes, the error persists. Connection facing outside works, tested via curl to several targets.

**Comment by DarkAxi0m** [comment]
Me to, getting 502 Bad Gateway on http://ajenti.org/plugins/list

Update: https://ajenti.org/plugins/list has a ssl error

**Comment by Eugeny** [comment]
It's back up
