### ISSUE TITLE
Nginx Conf now writing TLSv1.3 ??

### ISSUE THREAD

**Issue by wrrr** [ajenti/ajenti#1167]
I wrote the same ticket on Ajenti support. Why on one machine (now I don't want other machines to take sites down I have 10 on this one).

nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/nginx.conf:50

Just on one machine? I have 2 other installs no insertion into nginx.conf

Ajenti  v1.2.23.13 - nginx/1.10.3 - (Ubuntu) 16.04.6

**Comment by wrrr** [comment]
﻿I fixed this in /var/lib/ajenti/plugins/vh-nginx/nginx_templates.py
﻿
﻿How did it get changed is the question. I'm up for 1.3 but need more info.

thx
stu

**Comment by w-biggs** [comment]
This change breaks the default stable version of nginx on Ubuntu and requires users to install the newest stable version from nginx's PPA. This should be opt-in, sites shouldn't break when updating Ajenti...

**Comment by cacingpita** [comment]
![Screenshot from 2019-04-30 14-07-48](https://user-images.githubusercontent.com/50132698/56945440-6dca2c80-6b51-11e9-937e-0e0c7851766e.png)

Help me how to fix this

**Comment by lucaslcode** [comment]
To clarify @wrrr in the file /var/lib/ajenti/plugins/vh-nginx/nginx_templates.py there is a line 
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;`
Remove TLSv1.3, restart ajenti with `services ajenti restart` and then go Websites->Restart Websites.

**Comment by assaneonline** [comment]
> services ajenti restart

service ajenti restart

**Comment by wrrr** [comment]
I built a new server with Ubuntu 18.04 and PHP7.2, same release of Ajenti and I do not have to alter the .py file, it all works out of the box. So now I will investigate how to implement the TLS 1.3 ciphers if possible. The ciphers I put in for TLS 1, 1.1 and 1.2 were: EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5

This works with a free COMODO ECC CA2 cert from Cloudflare.

**Comment by wrrr** [comment]
I built a new server with Ubuntu 18.04 and PHP7.2, same release of Ajenti and I do not have to alter the .py file, it all works out of the box. So now I will investigate how to implement the TLS 1.3 ciphers if possible. The ciphers I put in for TLS 1, 1.1 and 1.2 were: EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5

This works with a free COMODO ECC CA2 cert from Cloudflare.

**Comment by theonlyfoxy** [comment]
Best solution is to install nginx from latest ppa.

**Comment by hrm143** [comment]
> install nginx from latest ppa

i have 3-4websites running Ajenti v1.2.23.13 - nginx/1.10.3 - (Ubuntu) 16.04.6; how to upgrade only Nginx to latest version without reinstalling ajenti?

**Comment by theonlyfoxy** [comment]
@hrm143 Just add the ppa and do apt-get upgrade
