### ISSUE TITLE
nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/nginx.conf:50

### ISSUE THREAD

**Issue by cacingpita** [ajenti/ajenti#1170]
Help me guys How to fix this, my nginx error when i configure website in ajenti V
![Screenshot from 2019-04-30 14-07-48](https://user-images.githubusercontent.com/50132698/56945551-c39ed480-6b51-11e9-88a9-d1b0cb8da9bb.png)

**Comment by lucaslcode** [comment]
In the file /var/lib/ajenti/plugins/vh-nginx/nginx_templates.py there is a line 
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;`
Remove TLSv1.3, restart ajenti with `services ajenti restart` and then go Websites->Restart Websites.
