### ISSUE TITLE
Split terminals?

### ISSUE THREAD

**Issue by linuxd3v** [ajenti/ajenti#1187]
Without installing ajenti - could someone tell me if it's possible to do split terminals or terminal tabs or run multiple terminal sessions?

**Comment by lukruh** [comment]
I've no experience with ajenti, but on screenshots it looks like u can start multiple terminals.
However you could have a look at `GNU screen` or `tmux` this commandline tools can be used to have tabs/sessions/splitview/persistence inside the terminal..
