### ISSUE TITLE
Reporting security issues

### ISSUE THREAD

**Issue by retpoline** [ajenti/ajenti#1195]
Hi,

What's the best way to report security bugs in the Ajenti platform?

Thanks!

**Comment by kiarn** [comment]
Hello @inthenets ,

I don't know if there's a security@ email for the ajenti domain, so I would say, just email @Eugeny  ( see email in profile ) and me ( arnaud@ + see domain in my profile ) for reporting security issues in private. We are only working on Ajenti 2, when we have free time for this, but your help is appreciated.

Cheers,

Arnaud

**Comment by retpoline** [comment]
Thanks kiarn-- yes, I didn't see a security@ email, but I have reached out to Eugeny directly but will add you to the thread as well.
