### ISSUE TITLE
Ajenti script doesn't work

### ISSUE THREAD

**Issue by velascode64** [ajenti/ajenti#1215]
# In [docs](http://docs.ajenti.org/en/latest/man/install.html):

**With the script:**
curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -

## Ubuntu 20.04
**Isntalation Done**
Ajenti will be listening at HTTP port 8000
Log in with your root password or another OS user
gdesign@genesisL502XLubuntu ~/ajenti_server> sudo systemctl start ajenti

**Systemctl tell me fails**
feb 19 01:04:11 genesisL502XLubuntu systemd[1]: Starting Ajenti panel...
feb 19 01:04:11 genesisL502XLubuntu systemd[1]: ajenti.service: Can't open PID file /var/run/ajenti.pid (yet?) after star
feb 19 01:04:11 genesisL502XLubuntu systemd[1]: Started Ajenti panel.
feb 19 01:04:12 genesisL502XLubuntu systemd[1]: ajenti.service: Main process exited, code=exited, status=1/FAILURE
feb 19 01:04:12 genesisL502XLubuntu systemd[1]: ajenti.service: Failed with result 'exit-code'.

**Comment by velascode64** [comment]
Why any one attend this issue, I saw a lot of people having the same.

**Comment by kiarn** [comment]
Hello @Provoo 

I have tested the install script again yesterday on Ubuntu 20.04 without problem.
You don't need to start the systemctl service after the install, it should already run.

Is there something in `/var/log/ajenti/ajenti.log` which could help to debug ?
I can reopen the issue if it's still relevant, but we need more informations.

Arnaud
