### ISSUE TITLE
Install on Ubuntu 18.04-19.10: python-imaging dependency can't be installed

### ISSUE THREAD

**Issue by noraj** [ajenti/ajenti#1221]
Following the [install steps](http://docs1.ajenti.org/en/latest/man/install.html#ubuntu-packages) for Ubuntu on a freshly installed Ubuntu Server 19.10 results in this error:

![image](https://user-images.githubusercontent.com/16578570/75894014-e36aed00-5e33-11ea-976c-2a309fddeea3.png)

python-imaging dependency can't be installed.

![image](https://user-images.githubusercontent.com/16578570/75894557-a521fd80-5e34-11ea-810f-f22ef4f36b1d.png)

**Comment by noraj** [comment]
maybe similar to #778

**Comment by noraj** [comment]
Not installable on Ubuntu 18.04 LTS either:

![image](https://user-images.githubusercontent.com/16578570/75996471-301afa80-5efe-11ea-98a2-a090a53c7ac4.png)

**Comment by lotharthesavior** [comment]
This is the best solution that I could find: Install the imaging from the source:

Step 1: download the package:

```shell
wget http://security.debian.org/debian-security/pool/updates/main/p/pillow/python-imaging_2.6.1-2+deb8u4_all.deb
```
Step 2: install the package

```shell
sudo dpkg -i python-imaging_2.6.1-2+deb8u4_all.deb
```

Step 3: install ajenti with apt

```shell
sudo apt-get install ajenti
```

I hope that help!

**Comment by noraj** [comment]
unstale

**Comment by kiarn** [comment]
Hi, it looks like your issue is related to Ajenti v1.

Ajenti v1 has reached its end of life and although we gladly accept fixes and PRs, there isn't any new development happening.

As a non-profit project, we don't have the manpower available to provide support for v1 related issues. Thank you for your understanding.

**Comment by noraj** [comment]
Ok there is a new doc http://docs.ajenti.org/en/latest/man/install.html that replace the old v1 doc: http://docs1.ajenti.org/en/latest/man/install.html#ubuntu-packages
