### ISSUE TITLE
Ajenti Panel doesn't run on a clean Ubuntu 18.04

### ISSUE THREAD

**Issue by codecat** [ajenti/ajenti#1232]
Ajenti bug report
--------------------
See crash log below. It seems like `gevent.signal` is a `module` type rather than a function. Possibly a problem in locking a dependency version?

Info | Value
----- | -----
Ajenti | 2.1.33
Platform | debian / ubuntu / Ubuntu 18.04.4 LTS
Architecture | x86_64 x86_64
Python | 2.7.17
Debug | True
Loaded plugins | ace, core, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settings, terminal

Library | Version
------- | -------
gevent | 1.5.0
greenlet | 0.4.15
psutil | 5.7.0

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 37, in start
        aj.core.run(**kwargs)
      File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 208, in run
        gevent.signal(signal.SIGINT, signal_handler)
    TypeError: 'module' object is not callable

**Comment by kiarn** [comment]
Hello codecat,

Thanks for your report : I didn't try to run Ajenti 2 with gevent 1.5.0, only with gevent 1.3.7.
The update to gevent 1.5.0 breaks ajenti-core, I will have a look at this.

**Comment by codecat** [comment]
Thanks for the quick fix. I see another error in my log during installation which may be relevant:

```
ERROR: gipc 1.1.0 has requirement gevent<1.5,>=1.2, but you'll have gevent 1.5.0 which is incompatible.
```

**Comment by kiarn** [comment]
The quick fix doesn't work yet, there's still some problems with gevent 1.5.
If you want to use it now, the simplest way is to downgrade gevent to 1.3.7, I will fix the rest later.
