### ISSUE TITLE
Implicit requirement of python >=3.6?

### ISSUE THREAD

**Issue by mjray** [ajenti/ajenti#1245]
Thank you for the interesting software which I've been testing in a few ways.

Running on a fresh debian 9.12, many places in ajenti 2.1.34 display an error with a traceback concluding in 
TypeError: the JSON object must be str, not 'bytes'
(not least in ajenti_plugin_core/views/api.py function handle_api_auth which means no-one can log in).

https://docs.python.org/3/whatsnew/3.6.html#json makes me suspect that this would not happen on debian 10 which uses python3.7 while debian 9 uses python3.5. I will test this.

Should ajenti 2.x docs be updated to state python 3.6 or above is required, or should all the json.loads payloads have decode() calls appended, or have I lost the plot somehow?

**Comment by kiarn** [comment]
Hello @mjray 

I'm currently updating the documentation for Ajenti 2 with a few new hints : https://github.com/kiarn/ajenti/commit/b8fb6c2ddb609c36a2d411004beb4d5cae608beb

For the TypeError, I think replacing json module through simplejson would solve it : https://github.com/kiarn/ajenti/commit/f115cd6cc48069f9bc2ecdb8bcdcb72c52af9d9b

**Comment by mjray** [comment]
Hi @kiarn - thanks for the prompt reply.

I'd figured out the documentation hints already and that similar to what I thought.

Replacing as in kiarn@f115cd6 gets login working, but then adding a filesystem widget to the dashboard failed with a similar-looking error from another file. I found import json in the following:

ajenti_plugin_core/views/tasks.py
ajenti_plugin_core/views/main.py
ajenti_plugin_core/views/resource_server.py
ajenti_plugin_dashboard/views.py
ajenti_plugin_filesystem/views.py
ajenti_plugin_packages/views.py
ajenti_plugin_settings/views.py

Do you think it would be safe to switch all to simplejson? I've now got agreement to upgrade that server to Debian 10 anyway, but I think there's another Debian 9 server around that I could test on if it helps.

**Comment by kiarn** [comment]
Hi @mjray 

`simplejson` and `json` are quite the same. The only big difference in our case is that `simplejson` can handle the `bytes`. So replacing it should work.

**Comment by mjray** [comment]
I fear the carpet may have popped up in another corner! After changing all those imports, more of it works, but now creating a directory in the file manager returns an almost-blank error while the dev server displays:

Traceback (most recent call last):
  File "/usr/local/share/ajenti/.venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/share/ajenti/.venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/share/ajenti/.venv/lib/python3.5/site-packages/aj/http.py", line 44, in dispatch
    http_context = HttpContext(env, start_response)
  File "/usr/local/share/ajenti/.venv/lib/python3.5/site-packages/aj/http.py", line 139, in __init__
    fp=six.StringIO(self.body),
TypeError: initial_value must be str or None, not bytes

**Comment by mjray** [comment]
so I also updated these:
aj/auth.py:import json                                            
aj/gate/stream.py:import json                                     
aj/gate/worker.py:import json                                     
aj/api/endpoint.py:import json

which I didn't mention before. Still the error remains.

**Comment by kiarn** [comment]
For the error above, please see : https://github.com/kiarn/ajenti/commit/baccf5ecbb203aa3bcef27101fd1520588200613

We will soon publish a new version, I'm just collecting the max of fixs to include in the next package.

**Comment by kiarn** [comment]
Ajenti 2.1.35 is out, and I was able to install it via automated script on a fresh Debian 9, please try it.
