### ISSUE TITLE
Package Requirement Errors in Ajenti Install Script for RHEL / CentOS

### ISSUE THREAD

**Issue by darkmoon2** [ajenti/ajenti#1246]
Platform:  CentOS 8.1.1911
OS Minimum Install
Downloaded your latest Ajenti Script Install file and it had two issues at the end when it tried to install the packages.
Package 01:  dbus-python
This is now installed with python3-dbus just like you had it for Ubuntu
Package 02:  ntpdate
Redhat replaced ntpdate with chrony when they released version 8 so will Ajenti work with Chrony?  Do I need to file a separate issue for Chrony?
Thank You very much please let me know if you need more information.

**Comment by kiarn** [comment]
Hello @darkmoon2,

I've prepared a new install script 2 days ago : https://github.com/kiarn/ajenti/blob/master/scripts/install.sh

This worked in my virtual machine CentOS 8, I don't think that `python3-dbus` is necessary, but if you could test it and confirm, it would be great.
