### ISSUE TITLE
install scrip, https port

### ISSUE THREAD

**Issue by lukruh** [ajenti/ajenti#1254]
In the docs (http://docs.ajenti.org/en/latest/man/run.html?highlight=https#starting-service) I read the webpanel should be available under https on port 8000 but it doesnt. I can load the login page without encryption, but I don't want to login via http.. any further configuratoin required? There should be a hint in the docs or at least a warning on the webpanel..

**Comment by kiarn** [comment]
Hello @lukruh,

Is the parameter `ssl --> enable` set to `true` in `/etc/aenti/config.yml` ?
It must not only be set to `true`, but `ssl --> certificate` must also point to a valid certificate.

**Comment by lukruh** [comment]
ah I just saw the -c config parameter but didn't know where the default config is. `/etc/ajenti/` is more than obvious should have checked that.. however with ssl enabled it works thanks!
