### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by ggirardi1** [ajenti/ajenti#1261]
Hello guys!

I need to modify the nginx configuration file, but I am not able to, since Ajenti always discards my personalized settings when restarting the service.

I tried editing the file /var/lib/ajenti/plugins/vh-nginx/nginx_templates.py, but it doesn't reflect in /etc/nginx/nginx.conf.

Sorry for the ignorance, but how do I make this change or where do I apply it?

Best regards,

**Comment by kiarn** [comment]
Hello,

If you are talking about Ajenti 2, You need to config a proxypass with nginx to port 8000, something like : http://nginx.org/en/docs/http/ngx_http_proxy_module.html#example

Regards

Arnaud

**Comment by ggirardi1** [comment]
> Hello,
> 
> If you are talking about Ajenti 2, You need to config a proxypass with nginx to port 8000, something like : http://nginx.org/en/docs/http/ngx_http_proxy_module.html#example
> 
> Regards
> 
> Arnaud

Hello @kiarn. That's not really my question. I want to change the nginx template, which Ajenti uses, as I mentioned above.

The only problem is to apply this, I can only apply it by restarting the server.

**Comment by kiarn** [comment]
Ok, my bad, I wanted to answer too fast :)
You are speaking from Ajenti 1, I don't use it, and it's not really maintained anymore.
