### ISSUE TITLE
Docker Deployment

### ISSUE THREAD

**Issue by ddlidded** [ajenti/ajenti#1266]
Are there instructions available for deploying Ajenti on docker (portainer)?

**Comment by CyberCyclone** [comment]
It would be good if there was an official Docker image. A lot of people don't want to install it on the root operating system and creating a whole virtual machine just to run this is a real waste of resources.

**Comment by kiarn** [comment]
Hello @CyberCyclone 

The main goal of `Ajenti` is to have access to the server configuration and data and be able to manage it.
I don't get how it could work if `Ajenti` is installed inside a container.

Regards,

Arnaud

**Comment by CyberCyclone** [comment]
> Hello @CyberCyclone
> 
> The main goal of `Ajenti` is to have access to the server configuration and data and be able to manage it.
> I don't get how it could work if `Ajenti` is installed inside a container.
> 
> Regards,
> 
> Arnaud

Sorry, should have been more specific. The main dashboard panel could be containerised, but the agent on the remote servers would need to be installed on the OS level as you said.
