### ISSUE TITLE
Try to generate a self-signed ssl certificate

### ISSUE THREAD

**Issue by FreesieF** [ajenti/ajenti#1269]
Hello,

I tried to generate a self-signed certificate to Enable SSL in "General->Settings".

After confirming "Generating a new certificate will void all existing client authentication certificates!" with the button "Generate" I get an error:

` Server error occured. This is likely a bug.`

`Request
GET /api/settings/generate-server-certificate
Type
TypeError
Message
write() argument must be str, not bytes
Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aj/api/endpoint.py", line 71, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ajenti_plugin_settings/views.py", line 71, in handle_api_generate_server_certificate
    f.write(dump_privatekey(FILETYPE_PEM, key))
TypeError: write() argument must be str, not bytes`

**Comment by kiarn** [comment]
Hello,

Thank you for your report, I've corrected this : https://github.com/kiarn/ajenti/commit/e16f229415f7471ede15a1dfb7a74776536223f7
It will come with next release.

Regards

Arnaud

**Comment by KR0SIV** [comment]
It's December...... guess it's way past time to look for a better panel that actually is updated and functional.....
