### ISSUE TITLE
ajenti.org is down

### ISSUE THREAD

**Issue by raspher** [ajenti/ajenti#1274]
![Zrzut ekranu z 2020-08-07 00-43-33](https://user-images.githubusercontent.com/23345803/89589930-141ddb00-d847-11ea-9f67-de76edff94fb.png)

**Comment by pierow2k** [comment]
Looks like it's still down.  I stumbled across ajenti in some documentation, followed the link in these docs but the ajenti.org was unavailable. I found a cached copy via The WayBack Machine, and found links to the GirHub repo.
