### ISSUE TITLE
Fatal crash occured

### ISSUE THREAD

**Issue by ksorbo** [ajenti/ajenti#1282]
Cannot open in web browser:

### ajenti.log:
`2020-10-14 00:49:46,166 INFO    : Loading config from /etc/ajenti/config.yml`
`2020-10-14 00:49:46,169 INFO    : Ajenti Core 2.1.36`
`2020-10-14 00:49:46,169 INFO    : Master PID - 9560`
`2020-10-14 00:49:46,169 INFO    : Detected platform: debian / Ubuntu 20.04.1 LTS`
`2020-10-14 00:49:46,169 INFO    : Python version: 3.8.5`
`2020-10-14 00:49:46,228 INFO    : Discovered 12 plugins`
`2020-10-14 00:49:46,481 INFO    : Loaded 12 plugins`
`2020-10-14 00:49:46,482 INFO    : Binding to [0.0.0.0]:8000`
`2020-10-14 00:49:46,488 ERROR   : Fatal crash occured`
`2020-10-14 00:49:46,501 INFO    : New worker "restricted session" PID 9579, EUID 0, EGID 0`
`2020-10-14 00:49:46,502 INFO    : Worker 9579 is demoting to UID 65534 / GID 65534...`
`2020-10-14 00:49:46,502 INFO    : ...done, new EUID 65534 EGID 65534`
`2020-10-14 00:49:46,505 ERROR   : Crash report written to /root/ajenti-crash.txt`
`
### ajenti-crash.txt
`Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.1.36
Platform | debian / ubuntu / Ubuntu 20.04.1 LTS
Architecture | b'x86_64 x86_64'
Python | 3.8.5
Debug | False
Loaded plugins | ace, core, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settings, terminal

Library | Version
------- | -------
gevent | 20.9.0
greenlet | 0.4.17
psutil | 5.7.2

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 30, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 209, in run
        gevent.signal(signal.SIGINT, signal_handler)
    TypeError: 'module' object is not callable
`

**Comment by kiarn** [comment]
Hello @ksorbo 

You need gevent==1.3.7 currently in order to use Ajenti. The reason behind is that the module gipc requires gevent < 1.5.0. I'm waiting until this is done.
