### ISSUE TITLE
Ajenti Developers are Alive? I think no. Why?

### ISSUE THREAD

**Issue by salimcansatici** [ajenti/ajenti#1291]
Hi,

The project has been quiet and under development for a long time. There are a lot of errors in the installation and no one can experience it. There is an extremely difficult setup process and there is little detail. People who really want to contribute to the project think the project is dead. Unfortunately, I think "Ajenti" is over. Look for this installation error. See the error in auto setup? WTF? 

<img width="896" alt="Ekran Resmi 2020-11-13 23 26 37" src="https://user-images.githubusercontent.com/42337972/99118203-278bcf80-2608-11eb-9691-70831dc34054.png">

**Comment by kiarn** [comment]
I think this error is not related to the install script. There are many topics online which described this type of error in CentOS 8 : 

- are the DNS ok ?
- is the gpg configuration for dnf ok ?
- is the dnf cache cleared ?
- and so on ...

I made many automated installations from Ajenti in CentOS 8 and 7 and fixed the errors this week with the constructive help of other users.

**Comment by salimcansatici** [comment]
He has an Ajenti that says auto install? Where is this automatic? Haha! 

You can also see that there are a lot of errors in manual installations. If we evaluate what we see by how much, the ajenti will be harmful. 480 issue... 

are the DNS ok ? Yes
is the gpg configuration for dnf ok ? Yes
is the dnf cache cleared ? Yes

**Comment by kiarn** [comment]
I just ran a new automated install on CentOS.

Begin of the output : 

![a1](https://user-images.githubusercontent.com/10401079/99124025-a5001180-2601-11eb-99b7-6d624a5c7ab5.png)

End of the ouput : 

![a2](https://user-images.githubusercontent.com/10401079/99124045-ab8e8900-2601-11eb-9406-33f522f00142.png)

Even if the install process went until the end, I made a [fix](https://github.com/ajenti/ajenti/pull/1292/commits/03219aeab20ffd1d3acce78d39cde45f5ebd309d) to correct the unit file in systemd, fix which have to be accepted in the project.
