### ISSUE TITLE
ubuntu 20.10 unable to start ajenti-panel core dumped

### ISSUE THREAD

**Issue by ag88** [ajenti/ajenti#1293]
installed based on 
http://docs.ajenti.org/en/latest/man/install.html#native-dependencies-debian-ubuntu
tried the 'auto' install as well

while starting it up
```
ajenti-panel -v
...
20.11.2020 01:09  [...     5238]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
20.11.2020 01:09  [...     5238]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
20.11.2020 01:09  [...     5238]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
20.11.2020 01:09  [...     5238]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
Segmentation fault (core dumped)
```
any clues to fix this? python version is 3.8
the problem happens even if run as root

**Comment by ag88** [comment]
patched up some codes in :/usr/local/lib/python3.8/dist-packages/aj/__init__.py
the crash apparently happened in 
init() -> detect_platform() -> within call in distro.linux_distribution()
a temporary work around is to patch some sane values as return strings instead of calling distro.linux_distribution()
that works, it went through and hit another different core dump :\
```
  File "/usr/local/lib/python3.8/dist-packages/gipc/gipc.py", line 918, in _recv_in_buffer
    raise EOFError(
EOFError: Most likely, the other pipe end is closed.
    bytes_written = _write_nonblocking(self._fd, bindata)
...
  File "/usr/local/lib/python3.8/dist-packages/gevent/os.py", line 131, in nb_write
    result = _write(fd, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by kiarn** [comment]
Hello @ag88 ,

Which version of gevent and greenlet do you have ?
Does this help : https://github.com/ajenti/ajenti/issues/1281 ?

**Comment by ag88** [comment]
thanks @kiarn 
https://github.com/ajenti/ajenti/issues/1281#issuecomment-716180079
fixed that 2nd core dump :+1: :)

the first core dump isn't related to ajenti, i'm not sure what is broken deep down in the python libraries stack
it seemed to be related to os pipes
