### ISSUE TITLE
Ajenti Panel not working

### ISSUE THREAD

**Issue by 8PotatoChip8** [ajenti/ajenti#1297]
I left my ubuntu server alone and shutdown for about a month or so and it was working when I left it. Once I came back and turned it on for the first time the web panel is no longer working showing up on my website. Any ideas? I haven't touched it since I left it so I don't even remember what I was doing last.

**Comment by wrrr** [comment]
In a terminal it would possibly restart:

service ajenti restart

**Comment by 8PotatoChip8** [comment]
That did not work but I got ajenti running. Still no panel though. It says "ajtni.service: Can't open PID file /run/ajenti.pid (yet?) after start-post: Operation not permitted" if that helps. Thats some of what I see when I type "sudo systemctl status ajenti"

**Comment by wrrr** [comment]
Somewhere in this or the ajenti forum I recall having to kill that PID, but I am not certain where that was.

I would re-install it you can't lose anything previously set up it uses base linux folders and with nginx it overwrites the config files anyway and it won't do anything to  custom.d files if you have any.

https://support.ajenti.org/en/knowledge-bases/5/articles/1130-installing-ajenti-v-on-debianubuntu

**Comment by 8PotatoChip8** [comment]
"The following packages have unmet dependencies:
 ajenti-v : Depends: ajenti (> 1.2.21.12) but it is not going to be installed
                Depends: python-reconfigure (>- 0.1.39) but it is not going ot be installed
E: Unable to correct problems, you have help broken packages."

When I try to install ajenti through apt-get it shows me a whole list of dependencies, but I already have ajenti installed. (Sorry if this is very simple I am quite new still to working on webservers and linux as a whole.)

**Comment by 8PotatoChip8** [comment]
I dont really know how to fix all that so I did a fresh install..... sorry for anyone else coming to this thread in 5 - 10 years having the same problem. Although I hope this is fixed by then.
