### ISSUE TITLE
Error on starting ajenti locales

### ISSUE THREAD

**Issue by jmelich** [ajenti/ajenti#1298]
On a Ubuntu 18.04.5 LTS i've installed Ajenti v1.

The service seems it ok but ports weren't opening so I've started debugging.

When I checked to run as an app doing: `ajenti-panel -v` it shows the following error:

> Traceback (most recent call last):
>   File "/usr/local/bin/ajenti-panel", line 137, in <module>
>     from ajenti import core
>   File "/usr/local/lib/python3.6/dist-packages/ajenti/core.py", line 15, in <module>
>     import ajenti.locales  # importing locale before everything else!
>   File "/usr/local/lib/python3.6/dist-packages/ajenti/locales/__init__.py", line 13, in <module>
>     languages=([language] if language else None),
>   File "/usr/lib/python3.6/gettext.py", line 538, in translation
>     t = _translations.setdefault(key, class_(fp))
>   File "/usr/lib/python3.6/gettext.py", line 254, in __init__
>     self._parse(fp)
>   File "/usr/lib/python3.6/gettext.py", line 413, in _parse
>     catalog[str(msg, charset)] = str(tmsg, charset)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

After a bit of research I realized it was from my system locales so I taked care it was on the right ones and it was ok.

Even when I run `locale charmap` it says UTF-8.

Is there any workaround for it or a way to solve?

Thanks

**Comment by kiarn** [comment]
Hello @jmelich 

Ajenti v1 is not maintained anymore, it will be more and more difficult to install it, because it's only support Python 2.7 which is now deprecated.

**Comment by jmelich** [comment]
Thanks for your reply @kiarn.

I were asking given ajenti website shows both versions as if were still continued in parallel but with the particularity that v2 is lighter so with less functionality than v1.

Knowing that I close this thread.

Thanks ;)
