### ISSUE TITLE
I want to try Ajenti on Orange Pi but it don't install dependicies errors

### ISSUE THREAD

**Issue by meirinha-lab** [ajenti/ajenti#1299]
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ajenti : Depends: python (>= 2.6)
          Depends: python-support (>= 0.90.0) but it is not going to be installed
          Depends: python-lxml (>= 2.2.4) but it is not going to be installed
          Depends: python-gevent but it is not going to be installed
          Depends: python-gevent-socketio but it is not going to be installed
          Depends: python-psutil (>= 0.6.0) but it is not going to be installed
          Depends: python-reconfigure (>= 0.1.46) but it is not going to be installed
          Depends: python-daemon but it is not installable
          Depends: python-passlib but it is not going to be installed
          Depends: python-requests (>= 0.12.0) but it is not going to be installed
          Depends: python-dbus but it is not going to be installed
          Depends: python-imaging but it is not installable
          Depends: python-catcher but it is not going to be installed
          Depends: python-exconsole (>= 0.1.5) but it is not going to be installed
          Depends: python-ldap but it is not installable
E: Unable to correct problems, you have held broken packages.

Can you help?

**Comment by kiarn** [comment]
Hello @meirinha-lab,

Are you speaking of Ajenti 1 or 2 ? I cannot help for Ajenti 1, and Ajenti 2 requires at least Python 3.

**Comment by meirinha-lab** [comment]
The two, yes i have install python3

 

De: Kientz Arnaud <notifications@github.com> 
Enviada: 6 de dezembro de 2020 12:10
Para: ajenti/ajenti <ajenti@noreply.github.com>
Cc: meirinha-lab <pj.meirelles@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [ajenti/ajenti] I want to try Ajenti on Orange Pi but it don't install dependicies errors (#1299)

 

Hello @meirinha-lab <https://github.com/meirinha-lab> ,

Are you speaking of Ajenti 1 or 2 ? I cannot help for Ajenti 1, and Ajenti 2 requires at least Python 3.

**Comment by kiarn** [comment]
Sorry for the late reply, I had a terrible week.
How are you triying to install ajenti ? Can you please describe it ?
Did you try the automated install : 

`curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -`

?
