### ISSUE TITLE
In GUI the user Elevate to root not working

### ISSUE THREAD

**Issue by zs-gabor** [ajenti/ajenti#1302]
In Debian 10 python 3.7.3 and ajenti 2.1.37.
After manual fresh minimal install with the below authentication configuration in the config.yml :
auth:
  allow_sudo: true
  provider: os
  user_config: os
I authenticated successfully a none root user and want to Elevate to root, but not working. I got an authentication error and two unhandled exceptions pop-up.
I found in ajenti/ajenti-core/aj/auth.py the `class AuthenticationService():` `def check_sudo_password(self, username, password):` function handling authentication and use the sudo.
The unhandled exceptions occur when the  `o, e = sudo.communicate(password + '\n')`, because the communicate function parameters are must be bytes and it returns bytes.
These changes solved the unhandled exceptions: 
```
o, e = sudo.communicate(input=(password + '\n').encode('utf-8'))
...
raise SudoError((o + e).encode('utf-8').splitlines()[-1].strip())
```

My second problem was the sudo.
In Debian 10 the sudo validates the invoking user's credentials by default not the target user credentials. In the aj is sending target user credentials, but the sudo runs with the aj server process user, like "nobody" in my case.
In defaults the "sudoers" does not contain "nobody" user settings and has no password. Therefore, authentication cannot be successful.
In my case the sudo command gets "nobody" user password and it runs "ls" with "<username>" privileges.
What was the purpose of using `sudo -S -k -u <username> -- ls`?

To make sudo authentication work I added the following lines to the "sudoers" file:
```
Defaults:nobody targetpw
nobody  ALL=(ALL) /bin/ls
```
The first line enables the target user authentication to "nobody" user.

I hope I could help.

**Comment by kiarn** [comment]
Hello @zs-gabor,

Thanks for your detailled message. As you said, the first problem is fast solved, but the second needs some rework.
For some installations, I made a special sudoer file, but I don't think it's a good idea for a standard installation, I have to think about it.

**Comment by zs-gabor** [comment]
Hi,

Sorry my mistake in check_sudo_password, the correct line is:
`raise SudoError((o + e).decode('utf-8').splitlines()[-1].strip())`

If you designed sudo for password identification only, I suggest you use the following sudo command:
`sudo -S -k -v -u username`
In this case no require any command parameter to sudo, only verifys the user password.

**Comment by dsonbill** [comment]
Even with the new encode line, I get the same type error. Is there something else I have to do to get it to work?

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_core/views/api.py", line 116, in handle_api_auth
    if auth.check_sudo_password(username, password):
  File "/usr/local/lib/python3.8/dist-packages/aj/auth.py", line 158, in check_sudo_password
    o, e = sudo.communicate((password + '\n').encode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 850, in communicate
    greenlet.get()
  File "src/gevent/greenlet.py", line 769, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.8/dist-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 506, in _write_and_close
    fobj.write(data)
TypeError: a bytes-like object is required, not 'str'

**Comment by kiarn** [comment]
Hello @dsonbill 

I forgot this one.
I think changing : 

```
o, e = sudo.communicate(password + '\n')
```
onto

```
o, e = sudo.communicate(password.encode('utf-8') + b'\n')
```

in [/usr/local/lib/python3.6/dist-packages/aj/auth.py at line 158](https://github.com/ajenti/ajenti/blob/8ae6f7d7388ba92df43dfe5a5b4bbde6d43430a4/ajenti-core/aj/auth.py#L158) ( and then restart `Ajenti` ) should do the trick.

Regards

Arnaud

**Comment by dsonbill** [comment]
Thank you so much @kiarn. I'll give it a try as soon as I can.

**Comment by CyberCyclone** [comment]
Can we please get an update released with fixes for this?

```o, e = sudo.communicate(password.encode('utf-8') + b'\n')``` doesn't solve the authentication issues. All I get is an endlessly spinning padlock icon.

Trying to elevate permissions 9/10 just logs me out.

**Comment by kiarn** [comment]
Hello @CyberCyclone 

It's normal to have to give the password again. If you can post some errors from `/var/log/ajenti/ajenti.log` I can have a look at it. New version should come soon.
