### ISSUE TITLE
How to install this panel on debian10 running in a chroot container？

### ISSUE THREAD

**Issue by 1260074755** [ajenti/ajenti#1318]
When installing according to the official website tutorial, it will always prompt that ajenti cannot be found. I hope the author can reply!

**Comment by kiarn** [comment]
Hello,

Which install method are you using ? What is the complete traceback ?
What has this to do with chroot ?
Installing `Ajenti` in a chroot container will not permit `Ajenti` to work properly because it's purpose is to manage some resources on the server.

Regards

Arnaud
