### ISSUE TITLE
Ubuntu 20.04 Problem Superuser access required

### ISSUE THREAD

**Issue by mar1967** [ajenti/ajenti#1324]
Hi, i want to test ajenti and i hope you can help me to fix this error

reiner@master-source:~$ /usr/local/bin/ajenti-panel --dev
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
05.04.2021 13:23  [...     8279]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
05.04.2021 13:23  [...     8279]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
05.04.2021 13:23  [...     8279]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
05.04.2021 13:23  [...     8279]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
05.04.2021 13:23  [master  8279]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
05.04.2021 13:23  [master  8279]         entry.py:50    ERROR  Fatal crash occured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 39, in start
    aj.core.run(dev_mode=dev_mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 73, in run
    aj.config.load()
  File "/usr/local/bin/ajenti-panel", line 30, in load
    self.data = yaml.load(open(self.path), Loader=yaml.Loader)
PermissionError: [Errno 13] Permission denied: '/etc/ajenti/config.yml'
05.04.2021 13:23  [master  8279]        compat.py:19    DEBUG  Popen: ['uname', '-m']
05.04.2021 13:23  [master  8279]         entry.py:63    ERROR  Crash report written to /var/log/ajenti/crash-2021-04-05-13h23.txt
05.04.2021 13:23  [master  8279]         entry.py:64    ERROR  Please submit it to https://github.com/ajenti/ajenti/issues/new

 /var/log/ajenti/crash-2021-04-05-13h23.txt

Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.1.40
Platform | debian / ubuntu / Ubuntu 20.04.2 LTS
Architecture | x86_64
Python | 3.8.5
Debug | True
Loaded plugins |

Library | Version
------- | -------
gevent | 1.5.0
greenlet | 0.4.15
psutil | 5.5.1

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 73, in run
        aj.config.load()
      File "/usr/local/bin/ajenti-panel", line 30, in load
        self.data = yaml.load(open(self.path), Loader=yaml.Loader)
    PermissionError: [Errno 13] Permission denied: '/etc/ajenti/config.yml'

**Comment by kiarn** [comment]
Hello @mar1967 

You should start `ajenti` as root or with `sudo`.

**Comment by mar1967** [comment]
??? systemctl start ajenti

**Comment by mar1967** [comment]
> Hello @mar1967
> 
> You should start `ajenti` as root or with `sudo`.

 systemctl start ajenti
systemctl status ajenti
● ajenti.service - Ajenti panel
     Loaded: loaded (/lib/systemd/system/ajenti.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-04-05 13:42:19 CEST; 39min ago
    Process: 10646 ExecStart=/usr/bin/python3 /usr/local/bin/ajenti-panel -d (code=exited, status=0/SUCCESS)
    Process: 10649 ExecStartPost=/bin/sleep 5 (code=exited, status=0/SUCCESS)
   Main PID: 10648 (python3)
      Tasks: 11 (limit: 9407)
     Memory: 368.6M
     CGroup: /system.slice/ajenti.service
             ├─10648 /usr/bin/python3 /usr/local/bin/ajenti-panel -d
             ├─10660 /usr/local/bin/ajenti-panel worker [restricted session]
             └─10830 /usr/local/bin/ajenti-panel worker [session 2]

**Comment by mar1967** [comment]
ls -al /etc/ajenti/
insgesamt 24
drwxr-xr-x   2 root root  4096 Apr  5 13:13 .
drwxr-xr-x 162 root root 12288 Apr  5 12:26 ..
-rw-------   1 root root   380 Apr  5 13:13 config.yml
-rw-------   1 root root    11 Apr  5 12:26 users.yml

**Comment by mar1967** [comment]
I have the same error like the https://github.com/ajenti/ajenti/issues/1013 but fixing is not working

**Comment by mar1967** [comment]
sudo /usr/local/bin/ajenti-panel --dev
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.api.http.HttpMiddleware] (interface)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.api.http.HttpPlugin] (interface)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.api.http.SocketEndpoint] (interface)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator] (service)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.auth.AuthenticationMiddleware] (service)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.auth.AuthenticationProvider] (interface)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.auth.OSAuthenticationProvider] (implementation of [aj.auth.AuthenticationProvider])
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.auth.AuthenticationService] (service)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.auth.PermissionProvider] (interface)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.routing.CentralDispatcher] (service)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler] (service)
05.04.2021 14:44  [...    19015]  DEBUG    Registering [aj.gate.middleware.GateMiddleware] (service)
05.04.2021 14:44  [...    19015]        compat.py:19    DEBUG    Popen: ('lsb_release', '-a')
05.04.2021 14:44  [...    19015]        compat.py:19    DEBUG    Popen: ('uname', '-rs')
05.04.2021 14:44  [...    19015]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
05.04.2021 14:44  [master 19015]          core.py:72    INFO   Loading config from /etc/ajenti/config.yml
05.04.2021 14:44  [master 19015]          core.py:76    INFO   Loading users from /etc/ajenti/users.yml
05.04.2021 14:44  [master 19015]          core.py:81    WARN   Debug mode
05.04.2021 14:44  [master 19015]          core.py:83    WARN   Dev mode
05.04.2021 14:44  [master 19015]          core.py:94    INFO   Ajenti Core 2.1.40
05.04.2021 14:44  [master 19015]          core.py:95    INFO   Master PID - 19015
05.04.2021 14:44  [master 19015]          core.py:96    INFO   Detected platform: debian / Ubuntu 20.04.2 LTS
05.04.2021 14:44  [master 19015]          core.py:97    INFO   Python version: 3.8.5
05.04.2021 14:44  [master 19015]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/bin
05.04.2021 14:44  [master 19015]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.8
05.04.2021 14:44  [master 19015]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3.8/lib-dynload
05.04.2021 14:44  [master 19015]       plugins.py:67    DEBUG  Looking for plugins in /usr/local/lib/python3.8/dist-packages
05.04.2021 14:44  [master 19015]       plugins.py:67    DEBUG  Looking for plugins in /usr/lib/python3/dist-packages
05.04.2021 14:44  [master 19015]       plugins.py:285   INFO   Discovered 12 plugins
05.04.2021 14:44  [master 19015]       plugins.py:333   DEBUG  Resolved load order for 12 plugins: ['core', 'ace', 'dashboard', 'passwd', 'plugins', 'services', 'filesystem', 'filemanager', 'settings', 'terminal', 'packages', 'notepad']
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "core"
05.04.2021 14:44  [master 19015]          jadi.py:136   DEBUG  Registering [aj.plugins.core.api.sidebar.SidebarItemProvider] (interface)
05.04.2021 14:44  [master 19015]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.sidebar.Sidebar] (service)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.main.Permissions] (implementation of [aj.auth.PermissionProvider])
05.04.2021 14:44  [master 19015]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.navbox.Navbox] (service)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.api.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.config.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.main.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.resource_server.ResourcesHandler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.push.Push] (service)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.push.PushSocket] (implementation of [aj.api.http.SocketEndpoint])
05.04.2021 14:44  [master 19015]          jadi.py:70    DEBUG  Registering [aj.plugins.core.api.tasks.TasksService] (service)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.core.views.tasks.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "ace"
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "dashboard"
05.04.2021 14:44  [master 19015]          jadi.py:136   DEBUG  Registering [aj.plugins.dashboard.api.Widget] (interface)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.cpu.CPUWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.hostname.HostnameWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.loadavg.LoadAverageWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.memory.MemoryWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.dashboard.widgets.uptime.UptimeWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "passwd"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.passwd.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "plugins"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.plugins.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.plugins.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "services"
05.04.2021 14:44  [master 19015]          jadi.py:136   DEBUG  Registering [aj.plugins.services.api.ServiceManager] (interface)
05.04.2021 14:44  [master 19015]        compat.py:19    DEBUG  Popen: ['which', 'systemctl']
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.services.managers.systemd_manager.SystemdServiceManager] (implementation of [aj.plugins.services.api.ServiceManager])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.services.managers.sysv_manager.SysVServiceManager] (implementation of [aj.plugins.services.api.ServiceManager])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.services.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.services.main.Permissions] (implementation of [aj.auth.PermissionProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.services.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "filesystem"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.filesystem.main.Permissions] (implementation of [aj.auth.PermissionProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.filesystem.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "filemanager"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.filemanager.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "settings"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.settings.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.settings.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "terminal"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.main.Permissions] (implementation of [aj.auth.PermissionProvider])
05.04.2021 14:44  [master 19015]          jadi.py:70    DEBUG  Registering [aj.plugins.terminal.manager.TerminalManager] (service)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.views.Socket] (implementation of [aj.api.http.SocketEndpoint])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "packages"
05.04.2021 14:44  [master 19015]          jadi.py:136   DEBUG  Registering [aj.plugins.packages.api.PackageManager] (interface)
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.main.Permissions] (implementation of [aj.auth.PermissionProvider])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.views.Handler] (implementation of [aj.api.http.HttpPlugin])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.managers.apt_manager.APTPackageManager] (implementation of [aj.plugins.packages.api.PackageManager])
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.packages.managers.pip_manager.PIPPackageManager] (implementation of [aj.plugins.packages.api.PackageManager])
05.04.2021 14:44  [master 19015]       plugins.py:356   DEBUG  Importing plugin "notepad"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.notepad.main.ItemProvider] (implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "core"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "ace"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "dashboard"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "passwd"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "plugins"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "services"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.services.widget.ServiceWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "filesystem"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.filesystem.widget.DiskWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "filemanager"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "settings"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "terminal"
05.04.2021 14:44  [master 19015]          jadi.py:161   DEBUG  Registering [aj.plugins.terminal.widget.ScriptWidget] (implementation of [aj.plugins.dashboard.api.Widget])
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "packages"
05.04.2021 14:44  [master 19015]       plugins.py:366   DEBUG  Initializing plugin "notepad"
05.04.2021 14:44  [master 19015]       plugins.py:353   INFO   Loaded 12 plugins
05.04.2021 14:44  [master 19015]          core.py:127   INFO   Binding to [0.0.0.0]:8000
05.04.2021 14:44  [master 19015]          core.py:131   ERROR  Could not bind: [Errno 98] Die Adresse wird bereits verwendet

**Comment by mar1967** [comment]
sudo netstat -tlnp
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      2030/docker-proxy   
tcp        0      0 127.0.0.1:44777         0.0.0.0:*               LISTEN      15088/cockpit-bridg 
tcp        0      0 127.0.0.1:33807         0.0.0.0:*               LISTEN      15103/cockpit-bridg 
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1549/dnsmasq        
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      643/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      850/sshd: /usr/sbin 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      690/cupsd           
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      838/netdata         
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      838/netdata         
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      17764/python3       
tcp6       0      0 :::9090                 :::*                    LISTEN      1/init              
tcp6       0      0 :::9001                 :::*                    LISTEN      1026/java           
tcp6       0      0 :::22                   :::*                    LISTEN      850/sshd: /usr/sbin 
tcp6       0      0 ::1:631                 :::*                    LISTEN      690/cupsd           
tcp6       0      0 :::19999                :::*                    LISTEN      838/netdata

**Comment by kiarn** [comment]
`--dev` option is only for people who want to help the core development of `ajenti`.
In your case, this will not work because you still have `ajenti` running and listening on port 8000.

Doing `sudo systemctl restart ajenti` should start `ajenti` in normal mode.

**Comment by mar1967** [comment]
Ok, i have restarted ajenti

**Comment by mar1967** [comment]
Thank You

I have use your fix https://github.com/ajenti/ajenti/issues/1302 and now is all fine working
