### ISSUE TITLE
install ajenti v

### ISSUE THREAD

**Issue by AliKhadivi** [ajenti/ajenti#1330]
Hello
Will the "Ajenti V" plugin package be installed on Agenti version 2?
If not, what is the solution?

**Comment by kiarn** [comment]
Hello @AliKhadivi 

I already answered this question in #1256 
We need to rewrite all `nginx`, `apache`, `php` plugins for this, not sure when it will happen, but help and PR are always welcome.

**Comment by AliKhadivi** [comment]
Hello @kiarn 

**I have some questions:**
1- Is Agenti 1 less secure than Agenti 2?
2- Will I not have any security problems with Agenti 1 installation?
3- Are security updates still being done for Agenti 1?

**Thank you for your good and fast guidance**
