### ISSUE TITLE
Ajenti 2 Mail

### ISSUE THREAD

**Issue by ariefsn** [ajenti/ajenti#1332]
Hello,
is there email plugins for Ajenti 2?

Thanks

**Comment by kiarn** [comment]
Hello,

There is currently no plugin for email in Ajenti 2.
We are rewriting the core to use newer librairies, and then we can write new plugins (e.g. configuration for dovecot, postfix, etc ... ).

Regards,

Arnaud

**Comment by kiarn** [comment]
I will close this issue, because it's quite the same feature request as #1256 which will stay open.
