### ISSUE TITLE
Ajenti 2 login problem

### ISSUE THREAD

**Issue by matteoventuri7** [ajenti/ajenti#1334]
Hi, I try to login with root credentials but i can't login. Launching Ajenti with --dev i read this error: https://pastebin.com/sc6eqx9U
OS: Ubuntu 20.04.2 LTS
Python 3.8

**Comment by kiarn** [comment]
Hello @matteoventuri7 

The Websocketerror ist not hte problem for the auth, it's a common non-blocking error already solved in the new core development.

The real problem should appear after the line 

```
05.07.2021 08:45  [master 13664]    middleware.py:244   DEBUG  6.669s   33.0 bytes   200 POST /api/core/auth
```

Arnaud
