### ISSUE TITLE
Example plugin from template not building

### ISSUE THREAD

**Issue by H4gi** [ajenti/ajenti#1335]
I'm following the getting started tutorial at [http://docs.ajenti.org/en/latest/dev/intro.html](http://docs.ajenti.org/en/latest/dev/intro.html) but fail to build a basic plugin.

These are the steps I follow:

- Create a new plugin in the current directory:
```
ajenti-dev-multitool --new-plugin "Some plugin name"
```

- Build resources:
```
cd some_plugin_name
ajenti-dev-multitool --build
```

- And start it:
```
sudo ajenti-dev-multitool --run-dev
```

I get this error first for 'ajenti-dev-multitool --build': 
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:aj.plugins.PluginDependency'
  in "./plugin.yml", line 10, column 7
```

After updating 'plugin.yml' from

```
...
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
...
```
To

```
...
dependencies:
    - !PluginDependency {
        plugin_name: core
...
```
Now, I receive this error:

```
INFO Building resources for .
INFO Compiling ./resources/js/module.es
INFO Compiling ./resources/js/routing.es
INFO Compiling ./resources/js/controllers/index.controller.es
ERROR BUILD FAILED
INFO   3 error(s):
ERROR  * ./resources/js/module.es
WARNING b'You have mistakenly installed the `babel` package, which is a no-op in Babel 6.'
WARNING b"Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package."
WARNING b''
WARNING b'    npm uninstall babel'
WARNING b'    npm install --save-dev babel-cli'
WARNING b''
WARNING b'See http://babeljs.io/docs/usage/cli/ for setup instructions.'
ERROR  * ./resources/js/controllers/index.controller.es
WARNING b'You have mistakenly installed the `babel` package, which is a no-op in Babel 6.'
WARNING b"Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package."
WARNING b''
WARNING b'    npm uninstall babel'
WARNING b'    npm install --save-dev babel-cli'
WARNING b''
WARNING b'See http://babeljs.io/docs/usage/cli/ for setup instructions.'
ERROR  * ./resources/js/routing.es
WARNING b'You have mistakenly installed the `babel` package, which is a no-op in Babel 6.'
WARNING b"Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package."
WARNING b''
WARNING b'    npm uninstall babel'
WARNING b'    npm install --save-dev babel-cli'
WARNING b''
WARNING b'See http://babeljs.io/docs/usage/cli/ for setup instructions.'
```
Anyone know what's going wrong or can give me a link to a working demo plugin?

Thanks in advance!

**Comment by kiarn** [comment]
Hello @H4gi,

Many thanks for mentioning this error with the PluginDependency, I will correct this tomorrow.

About the error with babel, did you encounter any error while installing `babel-cli` ? 
I mean this command : 

```
npm -g install bower babel-cli babel-preset-es2015 babel-plugin-external-helpers less coffee-script angular-gettext-cli angular-gettext-tools
```

On which system did you try ? I've just tested on a Ubuntu 20.04, and it works fine. 

Cheers

Arnaud

**Comment by H4gi** [comment]
Hello @kiarn ,

Thanks for your reply!

Yes, I'm also working on Ubuntu 20.04.

I used this command from [https://github.com/ajenti/demo-plugins#readme](https://github.com/ajenti/demo-plugins#readme) to install the build tools and I did not encountered any errors:
```
sudo npm install -g babel babel-preset-es2015 less bower

```

But with your command:
```
npm -g install bower babel-cli babel-preset-es2015 babel-plugin-external-helpers less coffee-script angular-gettext-cli angular-gettext-tools
```
I did get an error message for babel-cli:

```
/usr/bin/babel-doctor -> /usr/lib/node_modules/babel-cli/bin/babel-doctor.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/babel-cli/bin/babel.js
npm ERR! dest /usr/bin/babel
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/babel-cli/bin/babel.js' -> '/usr/bin/babel'
npm ERR! File exists: /usr/bin/babel
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-06T20_27_33_079Z-debug.log
```

**After executing your command with '--force', everything works as expected.**


To come back to the small error in 'plugin.yml', I think this same error with the PluginDependency is also present in the [demo-plugins](https://github.com/ajenti/demo-plugins). In addition, I think the imports in the '__init__.py' files of the demo-plugins need to be modified from:
```
import main
```
to:
```
from .main import *
```

Thanks for your assistance!

**Comment by kiarn** [comment]
Hello @H4gi 

I made a fix for the dependency scheme : https://github.com/ajenti/plugin-template/pull/5
I'm glad you have succeeded to solve the problem yourself.

About the demo-plugin repo : it's deprecated and not compatible with the actual Ajenti, I think we could archive this repo.
The main stream to learn how Ajenti works is to test the plugin-template like you did and to understand how python and angular are communicating together.
Don't hesitate to ask if you have some questions !

Cheers

Arnaud

**Comment by MrJSmeets** [comment]
Hello @kiarn 

I'll do that, thanks for the clarification!

Cheers

H4gi

**Comment by kiarn** [comment]
Hello @joppesmeets @H4gi 

Can I close this issue and the other in the plugin repo ?

**Comment by MrJSmeets** [comment]
@kiarn Yes!
