### ISSUE TITLE
Terminal not working when accessing with https in Chrome

### ISSUE THREAD

**Issue by betty35** [ajenti/ajenti#1336]
Not sure if anyone else has come across this strange issue. I've run out of ideas of what's going on, and my current guess is that it may have something to do with the recent Chrome updates.

## Situation
I have an Ajenti 2 (2.1.40) installed on a Ubuntu server (20.04) behind nginx and with Cloudflare ssl.

It was working before and I noticed just this weekend that the terminal would freeze when I open it, not allowing me to type anything.

In Chrome browser, it throws this error here for every keypress.
![image](https://user-images.githubusercontent.com/17248038/126067707-6f02c781-743a-450f-a719-b9f89f6a9c21.png)

And in server's log, it's this:
`default_error_handler: method_access_denied, You do not have access to method "on_message" (endpoint=/socket, cket, msg_id=None)`

The strange thing is, this only happens in Chrome, and when using https. 

So far I only found terminal not working. File manager and notepad are still working.

## Cases
- In Chrome on PC (Version 91.0.4472.164 (Official Build) (64-bit)) with https and domain name --- not working
- In Chrome incognito window on PC with https and domain name --- not working
- In Chrome on PC with http and IP address & port --- working fine
- In Chrome on smart phone (Android)(Chrome 91.0.4472.120) with https and domain name --- not working
- In Edge (91.0.864.70) on PC with https and domain name --- working fine
- In Firefox on smart phone (Android) with https and domain name --- working fine

**Comment by kiarn** [comment]
Hello @betty35 

I use the same version of chrome and I'm not able to reproduce this.
What do you exactly mean with "http and IP address & port " ? 
Did you change `/etc/ajenti/config.yml` for the tests and restart `Ajenti` each time ?
I don't know Cloudflare, but does it eventually block websockets ?

Cheers

Arnaud

**Comment by betty35** [comment]
> Hello @betty35
> 
> I use the same version of chrome and I'm not able to reproduce this.
> What do you exactly mean with "http and IP address & port " ?
> Did you change `/etc/ajenti/config.yml` for the tests and restart `Ajenti` each time ?
> I don't know Cloudflare, but does it eventually block websockets ?
> 
> Cheers
> 
> Arnaud

Hi Arnaud,

By "http and IP address & port", I mean accessing the panel without ssl and domain name. For example, access locally from http://127.0.0.1:1234 (if running Ajenti on 1234), or from external with something like http://12.34.56.78:1234 (I know this is risky, so I changed my password temporarily, tested very quickly and changed back. Don't worry :) 

I don't think it's Cloudflare. I once suspected if that was me updating some options in HSTS or enabling that bot fighting feature, but reverting back to previous settings doesn't fix it. Plus, it only affected my Chrome browsers but not Edge or Firefox, which is why I'm wondering if it have something to do with Chrome's update.

**Comment by kiarn** [comment]
Hi @betty35 

There's an update on Chrome today, does it solve the problem ?
