### ISSUE TITLE
Installation error on Ubuntu 20.04 - Alibaba ECS

### ISSUE THREAD

**Issue by francescocan** [ajenti/ajenti#1337]
hi!

on a very new instance of ECS I have done the following:

_sudo apt update
sudo apt upgrade
sudo apt install build-essential python3-pip python3-dev python3-lxml libssl-dev python3-dbus python3-augeas python3-apt ntpdate
curl -O https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh
sudo bash ./install.sh_

It gives this error:
**Job for ajenti.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status ajenti.service" and "journalctl -xe" for details.**

When trying to access http://my-server-ip:8000 it says that the page has refused the connection

_ss -tunelp | grep 8000_ -> gives nothing, I haven't installed Apache either yet

Where is the problem? I have tried to do it a few times, reinitializing the disk every time, but nothing has changed.

![image](https://user-images.githubusercontent.com/77925723/126614900-9cd99192-aae8-4224-b4a1-3fb2eb900b06.png)

**Comment by kiarn** [comment]
Hello @francescocan,

After an install, can you please try to run a `ajenti-panel --dev` to see if an error occurs ?
You can then quit this modus by typing Ctrl + C.

**Comment by francescocan** [comment]
Hello @kiarn, sorry for the delay in coming back to you
please find a screenshot attached
thanks

![image](https://user-images.githubusercontent.com/77925723/127362049-bd3e1c7c-075b-4ff5-82ce-ea53739cbb5b.png)


Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.40
Platform | debian / ubuntu / Ubuntu 20.04.2 LTS
Architecture | x86_64
Python | 3.8.10
Debug | True
Loaded plugins |

Library | Version
------- | -------
gevent | 1.5.0
greenlet | 0.4.15
psutil | 5.8.0


    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)

**Comment by kiarn** [comment]
Hello @francescocan 

The above error is pretty clear : ajenti cannot read the config file in /etc/ajenti/config.yml.
Did you start ajenti as root ?

**Comment by francescocan** [comment]
@kiarn yes I did as root

**Comment by kiarn** [comment]
Ok. I did an install test on a Vm 20.04 with the exact same steps as you provide in your description, and I cannot reproduce this issue.
Are you sure you launched `ajenti-panel --dev` as root or as user with sudo ?
Because in your screenshot I only see `$ ajenti-panel --dev`.

**Comment by francescocan** [comment]
@kiarn yes, I don't use other users normally. Could this error depend on a particular configuration of Alibaba servers?

**Comment by kiarn** [comment]
> Could this error depend on a particular configuration of Alibaba servers?

I don't have any Alibaba server, and I don't know why they would block something in `/etc`, this doesn't make sense. Did you checked the content of `/etc/ajenti/config.yml` ?
It should be something like this : https://github.com/ajenti/ajenti/blob/master/ajenti-panel/config.yml
Maybe the file is empty and could not be written during the install process.

**Comment by francescocan** [comment]
OK, I'll try later to install it again and let you know @kiarn

**Comment by DeadPixhell** [comment]
Hello,

I have the same error after installing Ajenti on 20.04.3 Ubuntu LTS server.

> 03.09.2021 13:43  [master 279749]         entry.py:50    ERROR  Fatal crash occured
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 39, in start
>     aj.core.run(dev_mode=dev_mode, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 100, in run
>     PluginManager.get(aj.context).load_all_from(aj.plugin_providers)
>   File "/usr/local/lib/python3.8/dist-packages/aj/plugins.py", line 274, in load_all_from
>     yml_info = yaml.load(open(os.path.join(path, 'plugin.yml')), Loader=yaml.SafeLoader)
>   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
>     return loader.get_single_data()
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 51, in get_single_data
>     return self.construct_document(node)
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 60, in construct_document
>     for dummy in generator:
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 408, in construct_yaml_seq
>     data.extend(self.construct_sequence(node))
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in construct_sequence
>     return [self.construct_object(child, deep=deep)
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in <listcomp>
>     return [self.construct_object(child, deep=deep)
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 100, in construct_object
>     data = constructor(self, node)
>   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 427, in construct_undefined
>     raise ConstructorError(None, None,
> yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:aj.plugins.PluginDependency'
>   in "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_terminal/plugin.yml", line 9, column 7
> 03.09.2021 13:43  [master 279749]        compat.py:19    DEBUG  Popen: ['uname', '-m']
> 03.09.2021 13:43  [master 279749]         entry.py:63    ERROR  Crash report written to /var/log/ajenti/crash-2021-09-03-13h43.txt


Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.40
Platform | debian / ubuntu / Ubuntu 20.04.3 LTS
Architecture | x86_64
Python | 3.8.10
Debug | True
Loaded plugins |

Library | Version
------- | -------
gevent | 1.5.0
greenlet | 0.4.15
psutil | 5.8.0

**Comment by DeadPixhell** [comment]
Sorry, it's was not really the same i have edited the following file
`sudo nano /usr/local/lib/python3.8/dist-packages/ajenti_plugin_terminal/plugin.yml`
I have replaced :

> dependencies:
>     - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
>     - !!python/object:aj.plugins.PluginDependency { plugin_name: ace }
>     - !!python/object:aj.plugins.OptionalPluginDependency { plugin_name: dashboard }

By

> dependencies:
>     - !PluginDependency { plugin_name: core }
>     - !PluginDependency { plugin_name: ace }
>     - !OptionalPluginDependency { plugin_name: dashboard }

**Comment by sjomurodov** [comment]
Hello,

I have the same error after installing Ajenti on 20.04.3 Ubuntu LTS server.

`Ajenti bug report
--------------------


Info | Value
----- | -----
Ajenti | 2.1.43
Platform | debian / ubuntu / Ubuntu 20.04.3 LTS
Architecture | x86_64
Python | 3.8.10
Debug | True
Loaded plugins | 

Library | Version
------- | -------
gevent | 21.1.2
greenlet | 1.1.2
psutil | 5.8.0`

LOG

> 
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/aj/core.py", line 78, in run
        aj.users.load()
      File "/usr/local/lib/python3.8/dist-packages/aj/config.py", line 109, in load
        self.data = yaml.load(open(self.path), Loader=yaml.SafeLoader)
    PermissionError: [Errno 13] Permission denied: '/etc/ajenti/users.yml'
> 

> 
dependencies:
    - !PluginDependency { plugin_name: core }
    - !PluginDependency { plugin_name: ace }
    - !OptionalPluginDependency { plugin_name: dashboard }
> 

![image](https://user-images.githubusercontent.com/17804616/136854876-5b6e3b6e-4353-4c2b-ab94-a35ea656e213.png)

**Comment by kiarn** [comment]
Hello @sjomurodov 

I don't think it's the same error, but I will naturally look at it : does the file `/etc/ajenti/users.yml` ? 
What's it's content ?

Arnaud

**Comment by nadamix77** [comment]
> Sorry, it's was not really the same i have edited the following file `sudo nano /usr/local/lib/python3.8/dist-packages/ajenti_plugin_terminal/plugin.yml` I have replaced :
> 
> > dependencies:
> > - !!python/object:aj.plugins.PluginDependency { plugin_name: core }
> > - !!python/object:aj.plugins.PluginDependency { plugin_name: ace }
> > - !!python/object:aj.plugins.OptionalPluginDependency { plugin_name: dashboard }
> 
> By
> 
> > dependencies:
> > - !PluginDependency { plugin_name: core }
> > - !PluginDependency { plugin_name: ace }
> > - !OptionalPluginDependency { plugin_name: dashboard }

it works! thank you
