### ISSUE TITLE
Cant elevate in panel

### ISSUE THREAD

**Issue by ParadiseFallen** [ajenti/ajenti#1338]
Cant elevate in panel. Get error "its might be a bug"
Tryed to change 158 line to password.encode('utf8') + b'\n' but not helped

**Comment by kiarn** [comment]
Hello @ParadiseFallen

I can confirm the problem, and it seems it's related to the session, I will investigate this.

**Comment by kiarn** [comment]
Just to be sure, only the users in the sudo group can elevate, otherwise you'll get an "Authorization failed".
