### ISSUE TITLE
Ajenti.org letsencrypt cert expired on 11 july, please auto-renew

### ISSUE THREAD

**Issue by nabtron** [ajenti/ajenti#1340]
The website gives a warning of insecure content when accessing it. Maybe try setting up auto-renew for letsencrypt ssl certificate to avoid this in future? 

<img width="931" alt="Screenshot 2021-08-01 at 7 06 07 PM" src="https://user-images.githubusercontent.com/9471128/127773863-26339edd-ccec-441c-b479-a9e95750387e.png">

<img width="870" alt="Screenshot 2021-08-01 at 7 06 22 PM" src="https://user-images.githubusercontent.com/9471128/127773869-d695371f-769b-4c76-b9a6-24692646723c.png">

**Comment by Eugeny** [comment]
Fixed, thanks!
