### ISSUE TITLE
Log incorrect login attempts 

### ISSUE THREAD

**Issue by dudztroyer** [ajenti/ajenti#1342]
I've been using 1.x for about 2 years now, but now I'm using it on a new project. I don't know if this is still maintained, but I want to suggest one improvement.

Currently when someone tries to log in with with invalid credentials, it will only log into auth.log if the username exists but the password is incorrect. I think that it should be logged even if the username is invalid for security measures afterwards such as fail2ban. 

Current login function
https://github.com/ajenti/ajenti/blob/d84706c9fab98e1462cde4b95ba27c523cee8ea7/ajenti/users.py#L60-L61

Thanks

**Comment by kiarn** [comment]
Hello @dudztroyer 

Thanks for your idea. Ajenti 1 is not maintained anymore.
The improvement you are suggesting is on my todo-list for ajenti 2 ( as many other things ), I just don't have enough time currently to work on it.

**Comment by dudztroyer** [comment]
Thanks for the quick response.

Could you guide or give me some quick directions in order to patch this on my current servers? 


Edit: NVM, got it already. Thanks

**Comment by kiarn** [comment]
I don't really know how Ajenti 1 works, so my answer is pretty simple and naive : 

```
     if not username in ajenti.config.tree.users: 
         with open('/var/log/ajenti/failed_login', 'a') as log:
             log.write('Failed attempt from %s \n' % username)
```

And then you need a filter in fail2ban.

**Comment by dudztroyer** [comment]
My issue was finding the correct file to modify as I was only found ajenti-panel binaries.

I've modified the full "check_passwords" function to this (just rearranged the order of the function itself, see below) and it works like a charm... Idk what is the overhead of tracing the IP or getting the sync provider if some one is DoS the login panel, but this should do it.

I've already got the f2b filters set up and found out that invalid usernames wasn't filtering.

Anyway, I'll leave the function here for further reference if anybody needs it.

https://github.com/ajenti/ajenti/blob/d84706c9fab98e1462cde4b95ba27c523cee8ea7/ajenti/users.py#L60-L61
```py
    def check_password(self, username, password, env=None):
        """
        Verifies the given username/password combo

        :type username: str
        :type password: str
        :rtype: bool
        """
        if not username or not password:
            return False
        provider = self.get_sync_provider(fallback=True)
        if username == 'root' and not provider.syncs_root:
            provider = ajenti.usersync.AjentiSyncProvider.get()

        try:
            provider.sync()
        except Exception as e:
            logging.error(str(e))

        provider_name = type(provider).__name__

        ip_notion = ''
        ip = env.get('REMOTE_ADDR', None) if env else None
        if ip:
            ip_notion = ' from %s' % ip
            
        if not username in ajenti.config.tree.users:
            msg = 'failed login attempt for %s ("%s") through %s%s' % \
                (username, password, provider_name, ip_notion)
            syslog.syslog(syslog.LOG_WARNING, msg)
            logging.warn(msg)
            return False


        result = provider.check_password(username, password)

        if not result:
            msg = 'failed login attempt for %s ("%s") through %s%s' % \
                (username, password, provider_name, ip_notion)
            syslog.syslog(syslog.LOG_WARNING, msg)
            logging.warn(msg)
        else:
            msg = 'user %s logged in through %s%s' % (username, provider_name, ip_notion)
            syslog.syslog(syslog.LOG_INFO, msg)
            logging.info(msg)
        return result
```

**Comment by kiarn** [comment]
Thanks for your contribution !
