### ISSUE TITLE
Cannot install on Ubuntu 21.04

### ISSUE THREAD

**Issue by eriteria** [ajenti/ajenti#1343]
Hello, I have been trying to install Ajenti for a while now i can't get to overcome this one issue

Ubuntu 21.04
Python 3.9.5
Please Help me?
I think it's something to do with gevent or greenlet, i tried installing them individually they worked but when i run either the automatic installation or the manual installation i get the same issue.
`
:: OS: debian
:: Distro: ubuntu
:: Enabling universe repository
Adding component(s) 'universe' to all repositories.
Hit:1 http://archive.ubuntu.com/ubuntu hirsute InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:3 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease
Hit:4 http://ppa.launchpad.net/lakinduakash/lwh/ubuntu hirsute InRelease
Get:5 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]
Ign:6 http://ppa.launchpad.net/micahflee/ppa/ubuntu hirsute InRelease    
Err:7 http://ppa.launchpad.net/micahflee/ppa/ubuntu hirsute Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:8 http://archive.ubuntu.com/ubuntu hirsute-security InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/micahflee/ppa/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
:: Installing prerequisites
Hit:1 http://archive.ubuntu.com/ubuntu hirsute InRelease
Hit:2 http://ppa.launchpad.net/lakinduakash/lwh/ubuntu hirsute InRelease
Hit:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:4 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease               
Ign:5 http://ppa.launchpad.net/micahflee/ppa/ubuntu hirsute InRelease    
Get:6 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]
Err:7 http://ppa.launchpad.net/micahflee/ppa/ubuntu hirsute Release            
  404  Not Found [IP: 91.189.95.85 80]
Hit:8 http://archive.ubuntu.com/ubuntu hirsute-security InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/micahflee/ppa/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.8ubuntu3).
python3-dbus is already the newest version (1.2.16-5).
python3-dev is already the newest version (3.9.4-1).
python3-lxml is already the newest version (4.6.3-1).
python3-augeas is already the newest version (0.5.0-1.1).
python3-pip is already the newest version (20.3.4-1ubuntu2).
libssl-dev is already the newest version (1.1.1j-1ubuntu3.2).
python3-apt is already the newest version (2.2.0~ubuntu0.21.04.1).
ntpdate is already the newest version (1:4.2.8p12+dfsg-3ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
:: Upgrading PIP
rm: cannot remove '/usr/lib//usr/bin/python3/dist-packages/setuptools.egg-info': No such file or directory
Requirement already satisfied: pip in /usr/local/lib/python3.9/dist-packages (21.2.4)
Requirement already satisfied: wheel in /usr/local/lib/python3.9/dist-packages (0.37.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (57.4.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Skipping gevent-socketio as it is not installed.
WARNING: Skipping gevent-socketio-hartwork as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
:: Installing Ajenti
Collecting ajenti-panel
  Using cached ajenti_panel-2.1.40-py2.py3-none-any.whl
Collecting ajenti.plugin.core
  Using cached ajenti.plugin.core-0.98-py3-none-any.whl
Collecting ajenti.plugin.dashboard
  Using cached ajenti.plugin.dashboard-0.39-py3-none-any.whl
Collecting ajenti.plugin.settings
  Using cached ajenti.plugin.settings-0.30-py3-none-any.whl
Collecting ajenti.plugin.plugins
  Using cached ajenti.plugin.plugins-0.47-py3-none-any.whl
Collecting ajenti.plugin.notepad
  Using cached ajenti.plugin.notepad-0.27-py3-none-any.whl
Collecting ajenti.plugin.terminal
  Using cached ajenti.plugin.terminal-0.39-py3-none-any.whl
Collecting ajenti.plugin.filemanager
  Using cached ajenti.plugin.filemanager-0.27-py3-none-any.whl
Collecting ajenti.plugin.packages
  Using cached ajenti.plugin.packages-0.33-py3-none-any.whl
Collecting ajenti.plugin.services
  Using cached ajenti.plugin.services-0.30-py3-none-any.whl
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from ajenti-panel) (5.3.1)
Collecting aj==2.1.40
  Using cached aj-2.1.40-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from ajenti-panel) (2.25.1)
Collecting jadi>=1.0.3
  Using cached jadi-1.0.3-py3-none-any.whl
Collecting pyOpenSSL==19.1.0
  Using cached pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
Requirement already satisfied: gevent>=1 in /usr/local/lib/python3.9/dist-packages (from aj==2.1.40->ajenti-panel) (21.8.0)
Collecting termcolor
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting passlib
  Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
Requirement already satisfied: setproctitle in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (1.2.1)
Requirement already satisfied: setuptools>=41 in /usr/local/lib/python3.9/dist-packages (from aj==2.1.40->ajenti-panel) (57.4.0)
Collecting python-daemon
  Using cached python_daemon-2.3.0-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: simplejson in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (3.17.2)
Collecting greenlet<=0.4.16
  Using cached greenlet-0.4.16.tar.gz (60 kB)
Collecting gipc==1.1.1
  Using cached gipc-1.1.1-py3-none-any.whl
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (1.5.0)
Collecting gevent>=1
  Using cached gevent-1.5.0-cp39-cp39-linux_x86_64.whl
Collecting cookies
  Using cached cookies-2.2.1-py2.py3-none-any.whl (44 kB)
Requirement already satisfied: lxml>=2.2.4 in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (4.6.3)
Requirement already satisfied: psutil>=2.2.1 in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (5.8.0)
Collecting gevent-socketio-hartwork>=0.3.6
  Using cached gevent_socketio_hartwork-0.3.6.post201803091952-py3-none-any.whl (35 kB)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (1.15.0)
Requirement already satisfied: gevent-websocket in /usr/local/lib/python3.9/dist-packages (from aj==2.1.40->ajenti-panel) (0.10.1)
Requirement already satisfied: pip>=20 in /usr/local/lib/python3.9/dist-packages (from aj==2.1.40->ajenti-panel) (21.2.4)
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from aj==2.1.40->ajenti-panel) (4.8.0)
Collecting greenlet<=0.4.16
  Using cached greenlet-0.4.15.tar.gz (59 kB)
Requirement already satisfied: cryptography>=2.8 in /usr/lib/python3/dist-packages (from pyOpenSSL==19.1.0->aj==2.1.40->ajenti-panel) (3.3.2)
Collecting ajenti.plugin.passwd
  Using cached ajenti.plugin.passwd-0.24-py3-none-any.whl
Collecting ajenti.plugin.filesystem
  Using cached ajenti.plugin.filesystem-0.47-py3-none-any.whl
Collecting ajenti.plugin.ace
  Using cached ajenti.plugin.ace-0.29-py3-none-any.whl
Collecting pyte==0.8.0
  Using cached pyte-0.8.0-py3-none-any.whl
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from ajenti.plugin.terminal) (8.1.2)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting upstart-new
  Using cached upstart_new-0.3.4-py3-none-any.whl
Requirement already satisfied: lockfile>=0.10 in /usr/lib/python3/dist-packages (from python-daemon->aj==2.1.40->ajenti-panel) (0.12.2)
Requirement already satisfied: docutils in /usr/lib/python3/dist-packages (from python-daemon->aj==2.1.40->ajenti-panel) (0.16)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dmuy5krd
       cwd: /tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'greenlet' extension
  creating build
  creating build/temp.linux-x86_64-3.9
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-1n6GrT/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-1n6GrT/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c greenlet.c -o build/temp.linux-x86_64-3.9/greenlet.o
  greenlet.c: In function ‘g_initialstub’:
  greenlet.c:823:4: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
    823 |    result = PyEval_CallObjectWithKeywords(
        |    ^~~~~~
  In file included from /usr/include/python3.9/Python.h:145,
                   from greenlet.h:8,
                   from greenlet.c:5:
  /usr/include/python3.9/ceval.h:17:43: note: declared here
     17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
        |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  greenlet.c: In function ‘green_dealloc’:
  greenlet.c:1046:4: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
   1046 |    _Py_DEC_REFTOTAL;
        |    ^~~~~~~~~~~~~~~~
        |    _Py_DECREF
  greenlet.c:1046:4: note: each undeclared identifier is reported only once for each function it appears in
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: greenlet, gevent, termcolor, python-daemon, pyOpenSSL, passlib, jadi, gipc, gevent-socketio-hartwork, cookies, aj, ajenti.plugin.core, wcwidth, ajenti.plugin.passwd, ajenti.plugin.filesystem, pyte, ajenti.plugin.settings, ajenti.plugin.ace, upstart-new, ajenti.plugin.terminal, ajenti.plugin.dashboard, ajenti.plugin.services, ajenti.plugin.plugins, ajenti.plugin.packages, ajenti.plugin.notepad, ajenti.plugin.filemanager, ajenti-panel
  Attempting uninstall: greenlet
    Found existing installation: greenlet 1.1.1
    Uninstalling greenlet-1.1.1:
      Successfully uninstalled greenlet-1.1.1
    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k18tk_29/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet
         cwd: /tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/
    Complete output (24 lines):
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-x86_64-3.9
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-1n6GrT/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-1n6GrT/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c greenlet.c -o build/temp.linux-x86_64-3.9/greenlet.o
    greenlet.c: In function ‘g_initialstub’:
    greenlet.c:823:4: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
      823 |    result = PyEval_CallObjectWithKeywords(
          |    ^~~~~~
    In file included from /usr/include/python3.9/Python.h:145,
                     from greenlet.h:8,
                     from greenlet.c:5:
    /usr/include/python3.9/ceval.h:17:43: note: declared here
       17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    greenlet.c: In function ‘green_dealloc’:
    greenlet.c:1046:4: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
     1046 |    _Py_DEC_REFTOTAL;
          |    ^~~~~~~~~~~~~~~~
          |    _Py_DECREF
    greenlet.c:1046:4: note: each undeclared identifier is reported only once for each function it appears in
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of greenlet
  Moving to /usr/local/include/python3.9/greenlet/
   from /usr/local/include/python3.9/~reenlet
  Moving to /usr/local/lib/python3.9/dist-packages/greenlet-1.1.1.dist-info/
   from /usr/local/lib/python3.9/dist-packages/~reenlet-1.1.1.dist-info
  Moving to /usr/local/lib/python3.9/dist-packages/greenlet/
   from /usr/local/lib/python3.9/dist-packages/~reenlet
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4n5xyv3v/greenlet_ca6462f4e75e43cb932e9ae75267cf49/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k18tk_29/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet Check the logs for full command output.

`

**Comment by kiarn** [comment]
Hello @eriteria 

Yes it is an install problem with `greenlet` under python 3.9, I've read something about it the past months.
I didn't test the install under 21.04, I will test it as soon as possible when I'm back to my office :)

Arnaud
