### ISSUE TITLE
Installing on Debian 11: Error when building greenlet

### ISSUE THREAD

**Issue by xmeadow** [ajenti/ajenti#1345]
Thanks for the great installer!
Two times no trouble on Debian 10. But now first time with Debian 11 I get following error:

....

>   Building wheel for greenlet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e7jvz3jd
       cwd: /tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'greenlet' extension
  creating build
  creating build/temp.linux-x86_64-3.9
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c greenlet.c -o build/temp.linux-x86_64-3.9/greenlet.o
  greenlet.c: In function ‘g_initialstub’:
  greenlet.c:823:4: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
    823 |    result = PyEval_CallObjectWithKeywords(
        |    ^~~~~~
  In file included from /usr/include/python3.9/Python.h:145,
                   from greenlet.h:8,
                   from greenlet.c:5:
  /usr/include/python3.9/ceval.h:17:43: note: declared here
     17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
        |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  greenlet.c: In function ‘green_dealloc’:
  greenlet.c:1046:4: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
   1046 |    _Py_DEC_REFTOTAL;
        |    ^~~~~~~~~~~~~~~~
        |    _Py_DECREF
  greenlet.c:1046:4: note: each undeclared identifier is reported only once for each function it appears in
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
>     ERROR: Failed building wheel for greenlet
>     Running setup.py clean for greenlet
>   Successfully built ajenti.plugin.augeas ajenti.plugin.auth-users ajenti.plugin.datetime ajenti.plugin.network ajenti.plugin.power
>   Failed to build greenlet
>   Installing collected packages: greenlet, gevent, cffi, ptyprocess, lockfile, gevent-websocket, docutils, cryptography, termcolor, simplejson, setproctitle, pyyaml, python-daemon, pyOpenSSL, psutil, pexpect, passlib, jadi, gipc, gevent-socketio-hartwork, distro, cookies, aj, ajenti.plugin.core, wcwidth, ajenti.plugin.passwd, ajenti.plugin.filesystem, pyte, Pillow, ajenti.plugin.settings, ajenti.plugin.ace, upstart-new, scrypt, pytz, ajenti.plugin.terminal, ajenti.plugin.dashboard, ajenti.plugin.augeas, ajenti.plugin.services, ajenti.plugin.power, ajenti.plugin.plugins, ajenti.plugin.packages, ajenti.plugin.notepad, ajenti.plugin.network, ajenti.plugin.filemanager, ajenti.plugin.datetime, ajenti.plugin.auth-users, ajenti-panel
    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lm4kicsj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet
         cwd: /tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/
    Complete output (24 lines):
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-x86_64-3.9
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c greenlet.c -o build/temp.linux-x86_64-3.9/greenlet.o
    greenlet.c: In function ‘g_initialstub’:
    greenlet.c:823:4: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
      823 |    result = PyEval_CallObjectWithKeywords(
          |    ^~~~~~
    In file included from /usr/include/python3.9/Python.h:145,
                     from greenlet.h:8,
                     from greenlet.c:5:
    /usr/include/python3.9/ceval.h:17:43: note: declared here
       17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    greenlet.c: In function ‘green_dealloc’:
    greenlet.c:1046:4: error: ‘_Py_DEC_REFTOTAL’ undeclared (first use in this function); did you mean ‘_Py_DECREF’?
     1046 |    _Py_DEC_REFTOTAL;
          |    ^~~~~~~~~~~~~~~~
          |    _Py_DECREF
    greenlet.c:1046:4: note: each undeclared identifier is reported only once for each function it appears in
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lqci0ow5/greenlet_c4c1bbde59d847d8be0005d1ec7caf5d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lm4kicsj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/greenlet Check the logs for full command output.

**Comment by kiarn** [comment]
Hello @xmeadow 

Yes, I can confirm, that's the same problem as #1343 with Python 3.9.
I'm currently testing a requirement upgrade from gipc, greenlet and gevent and I hope a fix comes soon.
