### ISSUE TITLE
Upgrading to 2.1.42

### ISSUE THREAD

**Issue by xmeadow** [ajenti/ajenti#1346]
Hello there!

Minor cosmetic problem when I go to Plugins it says:
` Ajenti core 2.1.40. An upgrade to true is available.`

when clicking on "Update everything" two red messages pop up saying
`Some plugins failed to update`
and
`Failed: Command '['ajenti-upgrade']' returned non-zero exit status 1.`

It does that on both of my machines running Debian 10

**Comment by kiarn** [comment]
Hello,

Thanks for the report, I will have a look at this next week :)

Arnaud
