### ISSUE TITLE
[Ubuntu 20.04] Can't Elevate in ivanti

### ISSUE THREAD

**Issue by DeadPixhell** [ajenti/ajenti#1347]
Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.1.40
Platform | debian / ubuntu / Ubuntu 20.04.3 LTS
Architecture | x86_64
Python | 3.8.10
Debug | True
Loaded plugins |

Library | Version
------- | -------
gevent | 1.5.0
greenlet | 0.4.15
psutil | 5.8.0

Sudo user can't elevate
--------------------
Server error
 Server error occured. This is likely a bug.
Request
POST /api/core/auth
Type
TypeError
Message
a bytes-like object is required, not 'str'

Traceback
Traceback (most recent call last):

>   File "/usr/local/lib/python3.8/dist-packages/aj/api/endpoint.py", line 75, in wrapper
>     result = fx(self, context, *args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/ajenti_plugin_core/views/api.py", line 116, in handle_api_auth
>     if auth.check_sudo_password(username, password):
>   File "/usr/local/lib/python3.8/dist-packages/aj/auth.py", line 158, in check_sudo_password
>     o, e = sudo.communicate(password + '\n')
>   File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 850, in communicate
>     greenlet.get()
>   File "src/gevent/greenlet.py", line 769, in gevent._greenlet.Greenlet.get
>   File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
>   File "/usr/local/lib/python3.8/dist-packages/gevent/_compat.py", line 62, in reraise
>     raise value.with_traceback(tb)
>   File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
>   File "/usr/local/lib/python3.8/dist-packages/gevent/subprocess.py", line 506, in _write_and_close
>     fobj.write(data)
> TypeError: a bytes-like object is required, not 'str'

**Comment by kiarn** [comment]
Hello,

This should be solved in the last version published this week, please update.
