### ISSUE TITLE
Any plan to support Alpine Linux?

### ISSUE THREAD

**Issue by mythay** [ajenti/ajenti#1349]
Alpine become more and more popular now because of its minimal size. Is there any plan to support this openRC based release?

**Comment by Eugeny** [comment]
Have you already tried running Tabby on it from the .tgz? I've never packaged things for Alpine before, but I don't mind adding it to the CI if you could link some guide on packaging apks

**Comment by mythay** [comment]
I don't know what isTabby, can you give zsome details?
