### ISSUE TITLE
Parse

### ISSUE THREAD

**Issue by Slowlyroot** [ajenti/ajenti#1352]
> @opercaifa[]()![20211108_034759.jpg](https://user-images.githubusercontent.com/93892059/140673103-62c88211-2e04-4928-8aee- [ ] -7f319c16650a.jpg)

**Comment by Slowlyroot** [comment]
> []()**![Screenshot_20211108-011032_Chrome.jpg](https://user-images.githubusercontent.com/93892059/140686215-5162fc91-969a-46bf- [ ] -be83-890994e5241c.jpg)
**

**Comment by kiarn** [comment]
Hello,

It's not possible for us to see your pictures, can you describe your problem or format your message to display the screenshots ?

Arnaud

**Comment by kiarn** [comment]
Closing it because of lack of informations.
