### ISSUE TITLE
ERROR  Could not bind: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by nahropro** [ajenti/ajenti#1353]
I installed ajenti on Huawei vps successfully, but when is try to open it by serve-ip:8000 it is not opening?
In dev this error shows
20.11.2021 16:06  [master  4970]       plugins.py:353   INFO   Loaded 12 plugins
20.11.2021 16:06  [master  4970]          core.py:127   INFO   Binding to [0.0.0.0]:8000
20.11.2021 16:06  [master  4970]          core.py:131   ERROR  Could not bind: [Errno 98] Address already in use

**Comment by kiarn** [comment]
Hello,

Some service is already listening on port 8000, so Ajenti can not use this port. You can try to change the port in `/etc/ajenti/config.yml` and the restart ajenti.

Arnaud

**Comment by cloudwindy** [comment]
Hello, please close this issue if it has been resolved.
