### ISSUE TITLE
Feature Request: Role Management

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1357]
Most of the functionality won't be available without root permissions, and you have to elevate and input your password again. It would be better if you can login using your own account and automatically gain root permissions.

**Comment by cloudwindy** [comment]
And this can be done through role management.

**Comment by kiarn** [comment]
Hello @cloudwindy 

Please see if the auth_users plugins does not answer your needs. You can create new users with "role" e.g. associated with root system account.

**Comment by cloudwindy** [comment]
@kiarn
Thank for your reply. I just installed auth_users plugin, and met another issue. #1370

**Comment by kiarn** [comment]
I saw it last week and solved it.
To use the plugin, you can specify 'users' as provider in `/etc/ajenti/config.yml` and then restart `Ajenti`.

**Comment by cloudwindy** [comment]
@kiarn
Now another problem happened. Please check #1371.

**Comment by kiarn** [comment]
Hello,

#1371 is closed, did you come further ?

**Comment by cloudwindy** [comment]
I tried auth_users plugin but surprisingly find that all users with root permission share a same dashboard. Is there a way to customize a different dashboard for every user?

**Comment by kiarn** [comment]
Yes, that's right. The `auth_users` plugin miss an `UserConfig` interface to store these values.
With the `os` auth, all configs are stored in `~/.config/ajenti.yml`, but nothing is prepared for the `auth_users` plugins yet.

Arnaud

**Comment by cloudwindy** [comment]
Please don't stale, and close this if ```UserConfig``` is implemented. Thank you!
