### ISSUE TITLE
UI Enhancement: Make Title Changeable

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1358]
Make the text "Ajenti" beside menu button changeable in the settings like server name.

**Comment by kiarn** [comment]
Hello @cloudwindy 

It's [already possible](https://github.com/ajenti/ajenti/blob/38ce174356d77d73931a76673cf8d9334fa100ca/plugins/core/content/pages/index.html#L49) via the customization service. It's not well documented, and it would be great to simplify this, but it's currently not a priority for me: 

```
angular.module('ajenti.core').run(customization => {
    customization.plugins.core.title = "my_title";
});
```

**Comment by cloudwindy** [comment]
Thank you very much!
