### ISSUE TITLE
Bug Report: HTTP 403 Foribidden to Reverse Proxy

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1361]
When using a reverse proxy, requesting some of the font files returns HTTP 403 if header ```Origin``` isn't removed.

**Comment by kiarn** [comment]
Hello @cloudwindy 

Ok, thanks for your contributions, I will look at it and see if I can do anything.

**Comment by cloudwindy** [comment]
Maybe there's a hotlink protection?

**Comment by kiarn** [comment]
Yes, there's a little protection.
I assume your reverse proxy use the ip of the ajenti server to to transfer the requests.
You can try to specify this ip in the parameter `name` of `/etc/ajenti/config.yml` and then restart `Ajenti`.
But with this method, your reverse proxy will have to handle the certificate.

Arnaud

**Comment by cloudwindy** [comment]
In my opinion, it doesn't sound very reasonable to add hotlink protection to a control panel. Anyway, thank you for your explanation.

**Comment by kiarn** [comment]
Hello,

This protection is necessary in order to filter the request to the internal ip : it would be too dangerous to allow requests to the api from outside `Ajenti`. 

Arnaud

**Comment by cloudwindy** [comment]
I do think the protection is necessary for API. But is it for font files?

**Comment by kiarn** [comment]
All requests are simply filtered without making any differences, it's because this filter work at another level and just don't test the file type. It would be better to change the configuration of your reverse proxy, and it would probably solve another of your issues, or try to test what I said in https://github.com/ajenti/ajenti/issues/1361#issuecomment-980779312 ( you didn't mention if it works, it would be interesting for other people ).

Arnaud

**Comment by kiarn** [comment]
Hello,

I'm currently analyzing this point, and a question just came to my mind : does your proxy provide a SSL certificate ?
If the extern protocol ( the proxy, e.g. https ) is not the same as the intern protocol ( ajenti, e.g. http ), then the response will also be 403.

Arnaud

**Comment by Keridos** [comment]
Having the same issue. Could you add in a config to set trusted proxies and custom origin?
This is how most other web based projects do it.
Trusted Proxies is a list of allowed reverse proxies
Custom Origin is the external URL like: `https://hostname.domain.tld/`

**Comment by kiarn** [comment]
Hello @Keridos 

I must show how to adapt the HTTP headers in `Ajenti`. Do you use http as internal protocol ? ( I mean between the proxy and `Ajenti` )

Arnaud

**Comment by Keridos** [comment]
Yes, that way I do not have to provide certificates to ajenti and let the reverse Proxy handle SSL.

**Comment by kiarn** [comment]
I made some commits yesterday to fix the problem with the fonts : 

https://github.com/ajenti/ajenti/commit/329ec03c071d7fe8b04f927be18ac2aaeffb0a2e : add `trusted_domains`, <s>`behind_proxy`</s> and `trusted_proxies` parameter. 

https://github.com/ajenti/ajenti/commit/ce3c118173b1114ac4fddbc66af787da7db48091 : validate origin against `trusted_domains`
This solves the request about the fonts, but there's still a problem with the websocket.

But I cannot reproduce any problem involving the list of `trusted_proxies`, do you have a concrete example ?

Arnaud
