### ISSUE TITLE
Question: How to Participate in the Translating Project?

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1365]
I can help translating to Chinese. I also knows a little Japanese.

**Comment by kiarn** [comment]
Hello @cloudwindy 

It would be great if you can help to translate !
The translations are stored on [crowdin](https://crowdin.com/project/ajenti), and all users can pretty well help to translate. After that, I just have to compile the translations.

**Comment by cloudwindy** [comment]
Thanks! Could you make this on docs.ajenti.org?
