### ISSUE TITLE
How to install a custom plugin?

### ISSUE THREAD

**Issue by gmj93** [ajenti/ajenti#1366]
I created a new plugin following the documentation, using the `ajenti-dev-multitool`. I can run it correctly in my development VM using `ajenti-dev-multitool --run-dev`, after creating this plugin using `ajenti-dev-multitool --new-plugin "Plugin name"`. I could not find information about how to proceed from here to deploy this plugin on a different machine.

If I just copy the files to the new VM and run `ajenti-dev-multitool --run-dev` on the folder containing the plugin it doesn't show up on the interface.

How can I install the plugin that I created on a different ajenti instance?

**Comment by kiarn** [comment]
Hello @gmj93 

You can use the options of `ajenti-panel` to specify a custom plugin path : 

```
ajenti-panel --dev -stock-plugins --plugins /PATH/TO/YOUR/PLUGIN
```

Options : 
  - `--dev` : dev mode, also called by `ajenti-dev-multitool`
  - `--stock-plugins` : load the standards plugins located in `/usr/local/lib/python3.x/dist-packages/`
  - `--plugins` : you can specify your own path

You can also make a package for `pip`, like this : https://pypi.org/project/ajenti.plugin.cpu-temp/
with a name like `ajenti.plugin.NAME`, and upload it to pypi. This way your package would appear in the community plugins list, and it's then possible to install it directly via the `ajenti` interface.

Arnaud

**Comment by gmj93** [comment]
Hi @kiarn 
thanks for the instructions. Worked fine :+1:

**Comment by kiarn** [comment]
Hi @gmj93 

So we can close this issue ?

**Comment by gmj93** [comment]
Hi @kiarn 
yes, thank you very much for your help!
