### ISSUE TITLE
UI Enhancement: Better Expression of Ordinal Numbers in Different Languages

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1368]
https://github.com/ajenti/ajenti/blob/38ce174356d77d73931a76673cf8d9334fa100ca/plugins/core/resources/js/core/filters.es#L33-L48
The usage of suffix "st" "nd", etc is very common in English but not in other languages. In Japanese, suffix "番目" (banme) is used after number no matter what the number is (eg. first 1番目 second 2番目 third 3番目). And in Chinese, both prefix "第" (dì) and suffix "个" (gè) is used. (eg. first 第1个 second 第2个 third 第3个)

**Comment by kiarn** [comment]
Hello @cloudwindy 

Thank you for this explanation.
It will difficult to apply different math rules for different languages, but if I really see, this filter doesn't seem to be used in the UI. I mean I didn't found any occurences of this filter in the frontend.

Arnaud

**Comment by cloudwindy** [comment]
Oh I saw this in crowdin and misunderstood that it is used in the frontend. Sorry for the confusion.
