### ISSUE TITLE
Security: ajenti.log Should Be Root-only

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1369]
Currently ajenti.log contains a lot of information about the system, hardware, etc, and is exposed to all users. It should be set to root only (eg. ```chown root:root ajenti.log``` ```chmod 600 ajenti.log```)

**Comment by kiarn** [comment]
Hello,

The owner should already be root. I changed the permission to 640, I think it's sufficient and would allow people from the root group to read the logs.

Arnaud
