### ISSUE TITLE
Bug Report: Authentication Provider is not Visible

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1370]
Request to ```/api/core/authentication-providers``` succeeded, and returned ```[{"id": "os", "name": "OS users"}, {"id": "users", "name": "Custom users"}]```. However, no providers were shown in the combo box. Both Chrome and Firefox are experiencing this issue.

**Comment by kiarn** [comment]
Hello,

This is already solved with https://github.com/ajenti/ajenti/commit/e5e8f973c1555baef98a6d1d3df75bf1eaad6f0c

Arnaud
