### ISSUE TITLE
Feature Request: Allow Service to Manage Templated Units

### ISSUE THREAD

**Issue by cloudwindy** [ajenti/ajenti#1372]
For example I want to monitor the status of ```postfix@-.service``` instead of ```postfix.service```.

**Comment by cloudwindy** [comment]
I just found that all templated units are removed from ```Services``` list.

**Comment by cloudwindy** [comment]
Perhaps there should be a textbox to allow user to input the service instead of selecting from a combo box, since he/she already knew what service to monitor.

**Comment by kiarn** [comment]
Hello @cloudwindy ,

Can you please try the following command on your system : 

```
systemctl show -o json --full --all postfix@-.service
```

I don't habe some example to test, and it would be interesting to know if this command fails.

Arnaud

**Comment by cloudwindy** [comment]
No, it won't produce json, please refer to systemd/systemd#83.
Also the pager is turned on by default and you won't get the full config at once so I recommend you to add ```--no-page```.
The output format looks like this:
<details>
<summary>Show 13.9kB content</summary>
<b>Please note that all <code>[not set]</code><code>[no data]</code>and<code>[unprintable]</code> are pasted as they are.</b>
<pre>
Type=
Restart=no
PIDFile=
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
TimeoutAbortUSec=1min 30s
TimeoutStartFailureMode=terminate
TimeoutStopFailureMode=terminate
RuntimeMaxUSec=infinity
WatchdogUSec=infinity
WatchdogTimestamp=
WatchdogTimestampMonotonic=0
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
RestartPreventExitStatus=
RestartForceExitStatus=
SuccessExitStatus=
MainPID=0
ControlPID=0
BusName=
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusText=
StatusErrno=0
Result=success
ReloadResult=success
CleanResult=success
USBFunctionDescriptors=
USBFunctionStrings=
UID=[not set]
GID=[not set]
NRestarts=0
OOMPolicy=
ExecMainStartTimestamp=
ExecMainStartTimestampMonotonic=0
ExecMainExitTimestamp=
ExecMainExitTimestampMonotonic=0
ExecMainPID=0
ExecMainCode=0
ExecMainStatus=0
Slice=
ControlGroup=
MemoryCurrent=[not set]
CPUUsageNSec=[not set]
EffectiveCPUs=
EffectiveMemoryNodes=
TasksCurrent=[not set]
IPIngressBytes=[no data]
IPIngressPackets=[no data]
IPEgressBytes=[no data]
IPEgressPackets=[no data]
IOReadBytes=18446744073709551615
IOReadOperations=18446744073709551615
IOWriteBytes=18446744073709551615
IOWriteOperations=18446744073709551615
Delegate=no
DelegateControllers=
CPUAccounting=yes
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
CPUQuotaPeriodUSec=infinity
AllowedCPUs=
AllowedMemoryNodes=
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=yes
DefaultMemoryLow=0
DefaultMemoryMin=0
MemoryMin=0
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=18996
IPAccounting=no
IPAddressAllow=
IPAddressDeny=
IPIngressFilterPath=
IPEgressFilterPath=
DisableControllers=
ManagedOOMSwap=auto
ManagedOOMMemoryPressure=auto
ManagedOOMMemoryPressureLimit=0
ManagedOOMPreference=none
Environment=
PassEnvironment=
UnsetEnvironment=
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=0
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=1048576
LimitNOFILESoft=1048576
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=63321
LimitNPROCSoft=63321
LimitMEMLOCK=2089754624
LimitMEMLOCKSoft=2089754624
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=63321
LimitSIGPENDINGSoft=63321
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
WorkingDirectory=
RootDirectory=
RootImage=
RootImageOptions=[unprintable]
RootHash=
RootHashPath=
RootHashSignature=
RootHashSignaturePath=
RootVerity=
ExtensionImages=[unprintable]
MountImages=
OOMScoreAdjust=0
CoredumpFilter=0x33
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
CPUAffinity=
CPUAffinityFromNUMA=no
NUMAPolicy=n/a
NUMAMask=
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputFileDescriptorName=
StandardInputData=
StandardOutput=inherit
StandardOutputFileDescriptorName=
StandardError=inherit
StandardErrorFileDescriptorName=
TTYPath=
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogIdentifier=
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
LogRateLimitIntervalUSec=0
LogRateLimitBurst=0
LogExtraFields=
LogNamespace=
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend cap_audit_read cap_perfmon cap_bpf cap_checkpoint_restore
AmbientCapabilities=
User=
Group=
DynamicUser=no
RemoveIPC=no
SetCredential=[unprintable]
LoadCredential=[unprintable]
SupplementaryGroups=
PAMName=
ReadWritePaths=
ReadOnlyPaths=
InaccessiblePaths=
ExecPaths=
NoExecPaths=
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectClock=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectKernelLogs=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
PrivateMounts=no
PrivateIPC=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpIdentifier=
UtmpMode=init
SELinuxContext=
AppArmorProfile=
SmackProcessLabel=
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallFilter=~
SystemCallArchitectures=
SystemCallErrorNumber=2147483646
SystemCallLog=~
Personality=
LockPersonality=no
RestrictAddressFamilies=~
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
RuntimeDirectory=
StateDirectoryMode=0755
StateDirectory=
CacheDirectoryMode=0755
CacheDirectory=
LogsDirectoryMode=0755
LogsDirectory=
ConfigurationDirectoryMode=0755
ConfigurationDirectory=
TimeoutCleanUSec=infinity
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictSUIDSGID=no
RestrictNamespaces=no
BindPaths=
BindReadOnlyPaths=
TemporaryFileSystem=
MountAPIVFS=no
KeyringMode=private
ProtectProc=default
ProcSubset=all
ProtectHostname=no
NetworkNamespacePath=
IPCNamespacePath=
KillMode=control-group
KillSignal=15
RestartKillSignal=15
FinalKillSignal=9
SendSIGKILL=yes
SendSIGHUP=no
WatchdogSignal=6
Id=postfix@-.service
Names=postfix@-.service
Following=
Requires=
Requisite=
Wants=
BindsTo=
PartOf=
RequiredBy=
RequisiteOf=
WantedBy=
BoundBy=
ConsistsOf=
Conflicts=
ConflictedBy=
Before=
After=
OnFailure=
Triggers=
TriggeredBy=
PropagatesReloadTo=
ReloadPropagatedFrom=
JoinsNamespaceOf=
RequiresMountsFor=
Documentation=
Description=postfix@-.service
LoadState=not-found
ActiveState=inactive
FreezerState=running
SubState=dead
FragmentPath=
SourcePath=
DropInPaths=
UnitFileState=
UnitFilePreset=
StateChangeTimestamp=
StateChangeTimestampMonotonic=0
InactiveExitTimestamp=
InactiveExitTimestampMonotonic=0
ActiveEnterTimestamp=
ActiveEnterTimestampMonotonic=0
ActiveExitTimestamp=
ActiveExitTimestampMonotonic=0
InactiveEnterTimestamp=
InactiveEnterTimestampMonotonic=0
CanStart=no
CanStop=yes
CanReload=no
CanIsolate=no
CanClean=
CanFreeze=yes
Job=
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
Markers=
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
JobTimeoutRebootArgument=
ConditionResult=no
AssertResult=no
ConditionTimestamp=
ConditionTimestampMonotonic=0
AssertTimestamp=
AssertTimestampMonotonic=0
Conditions=[unprintable]
Asserts=[unprintable]
LoadError=org.freedesktop.systemd1.NoSuchUnit "Unit postfix@-.service not found."
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
FailureActionExitStatus=[not set]
SuccessAction=none
SuccessActionExitStatus=[not set]
RebootArgument=
InvocationID=
CollectMode=inactive
Refs=
</pre>
</details>

**Comment by kiarn** [comment]
Hello,

> Also the pager is turned on by default and you won't get the full config at once so I recommend you to add `--no-page`.

This will not do a difference with subprocess, and `Ajenti` only get a few informations.
The problem is not the json output, but the fact that the command `systemctl show ...` will fail with special services like `getty@.service`.
I can ignore special service and list templates ( with e.g. `''@." not in name` instead of  `''@" not in name` ), but I must be sure that this won't fail.

In your first post, you spoke about a `postfix@-.service`, but the output you provide doesn't seem to recognize this service. Can you please try with a real example ?

Arnaud

**Comment by cloudwindy** [comment]
I don't think there're special services. All template service units are named as ```<service_name>@<argument>.service```. A template unit without argument doesn't exist.

And I must apologize because I was pasting information from a machine which doesn't have postfix installed. The following information will be correct.

<details>
<summary>Show 9.0kB content</summary>
<pre>
Type=forking
Restart=no
PIDFile=
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
TimeoutAbortUSec=1min 30s
TimeoutStartFailureMode=terminate
TimeoutStopFailureMode=terminate
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestamp=
WatchdogTimestampMonotonic=0
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=no
RestartPreventExitStatus=
RestartForceExitStatus=
SuccessExitStatus=
MainPID=0
ControlPID=0
BusName=
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusText=
StatusErrno=0
Result=success
ReloadResult=success
CleanResult=success
USBFunctionDescriptors=
USBFunctionStrings=
UID=[not set]
GID=[not set]
NRestarts=0
OOMPolicy=stop
ExecMainStartTimestamp=
ExecMainStartTimestampMonotonic=0
ExecMainExitTimestamp=
ExecMainExitTimestampMonotonic=0
ExecMainPID=0
ExecMainCode=0
ExecMainStatus=0
ExecStartPre={ path=/usr/lib/postfix/configure-instance.sh ; argv[]=/usr/lib/postfix/configure-instance.sh - ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartPreEx={ path=/usr/lib/postfix/configure-instance.sh ; argv[]=/usr/lib/postfix/configure-instance.sh - ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStart={ path=/usr/sbin/postmulti ; argv[]=/usr/sbin/postmulti -i - -p start ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStartEx={ path=/usr/sbin/postmulti ; argv[]=/usr/sbin/postmulti -i - -p start ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecReload={ path=/usr/sbin/postmulti ; argv[]=/usr/sbin/postmulti -i - -p reload ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecReloadEx={ path=/usr/sbin/postmulti ; argv[]=/usr/sbin/postmulti -i - -p reload ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStop={ path=/usr/sbin/postmulti ; argv[]=/usr/sbin/postmulti -i - -p stop ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecStopEx={ path=/usr/sbin/postmulti ; argv[]=/usr/sbin/postmulti -i - -p stop ; flags= ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system-postfix.slice
ControlGroup=/system.slice/system-postfix.slice/postfix@-.service
MemoryCurrent=9367552
CPUUsageNSec=85170271000
EffectiveCPUs=
EffectiveMemoryNodes=
TasksCurrent=4
IPIngressBytes=[no data]
IPIngressPackets=[no data]
IPEgressBytes=[no data]
IPEgressPackets=[no data]
IOReadBytes=18446744073709551615
IOReadOperations=18446744073709551615
IOWriteBytes=18446744073709551615
IOWriteOperations=18446744073709551615
Delegate=no
DelegateControllers=
CPUAccounting=yes
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
CPUQuotaPeriodUSec=infinity
AllowedCPUs=
AllowedMemoryNodes=
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=yes
DefaultMemoryLow=0
DefaultMemoryMin=0
MemoryMin=0
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=2289
IPAccounting=no
IPAddressAllow=
IPAddressDeny=
IPIngressFilterPath=
IPEgressFilterPath=
DisableControllers=
ManagedOOMSwap=auto
ManagedOOMMemoryPressure=auto
ManagedOOMMemoryPressureLimit=0
ManagedOOMPreference=none
Environment=
PassEnvironment=
UnsetEnvironment=
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=0
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=524288
LimitNOFILESoft=1024
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=7632
LimitNPROCSoft=7632
LimitMEMLOCK=65536
LimitMEMLOCKSoft=65536
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=7632
LimitSIGPENDINGSoft=7632
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
WorkingDirectory=
RootDirectory=
RootImage=
RootImageOptions=[unprintable]
RootHash=
RootHashPath=
RootHashSignature=
RootHashSignaturePath=
RootVerity=
ExtensionImages=[unprintable]
MountImages=
OOMScoreAdjust=0
CoredumpFilter=0x33
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
CPUAffinity=
CPUAffinityFromNUMA=no
NUMAPolicy=n/a
NUMAMask=
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputFileDescriptorName=
StandardInputData=
StandardOutput=journal
StandardOutputFileDescriptorName=
StandardError=inherit
StandardErrorFileDescriptorName=
TTYPath=
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogIdentifier=
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
LogRateLimitIntervalUSec=0
LogRateLimitBurst=0
LogExtraFields=
LogNamespace=
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend cap_audit_read cap_perfmon cap_bpf cap_checkpoint_restore
AmbientCapabilities=
User=
Group=
DynamicUser=no
RemoveIPC=no
SetCredential=[unprintable]
LoadCredential=[unprintable]
SupplementaryGroups=
PAMName=
ReadWritePaths=
ReadOnlyPaths=
InaccessiblePaths=
ExecPaths=
NoExecPaths=
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectClock=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectKernelLogs=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
PrivateMounts=no
PrivateIPC=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpIdentifier=
UtmpMode=init
SELinuxContext=
AppArmorProfile=
SmackProcessLabel=
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallFilter=~
SystemCallArchitectures=
SystemCallErrorNumber=2147483646
SystemCallLog=~
Personality=
LockPersonality=no
RestrictAddressFamilies=~
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
RuntimeDirectory=
StateDirectoryMode=0755
StateDirectory=
CacheDirectoryMode=0755
CacheDirectory=
LogsDirectoryMode=0755
LogsDirectory=
ConfigurationDirectoryMode=0755
ConfigurationDirectory=
TimeoutCleanUSec=infinity
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictSUIDSGID=no
RestrictNamespaces=no
BindPaths=
BindReadOnlyPaths=
TemporaryFileSystem=
MountAPIVFS=no
KeyringMode=private
ProtectProc=default
ProcSubset=all
ProtectHostname=no
NetworkNamespacePath=
IPCNamespacePath=
KillMode=control-group
KillSignal=15
RestartKillSignal=15
FinalKillSignal=9
SendSIGKILL=yes
SendSIGHUP=no
WatchdogSignal=6
Id=postfix@-.service
Names=postfix@-.service
Following=
Requires=system-postfix.slice sysinit.target
Requisite=
Wants=network-online.target
BindsTo=
PartOf=postfix.service
RequiredBy=
RequisiteOf=
WantedBy=postfix.service
BoundBy=
ConsistsOf=
Conflicts=shutdown.target
ConflictedBy=
Before=shutdown.target postfix.service
After=nss-lookup.target system-postfix.slice systemd-journald.socket network-online.target sysinit.target basic.target
OnFailure=
Triggers=
TriggeredBy=
PropagatesReloadTo=
ReloadPropagatedFrom=postfix.service
JoinsNamespaceOf=
RequiresMountsFor=
Documentation="man:postfix(1)"
Description=Postfix Mail Transport Agent (instance -)
LoadState=loaded
ActiveState=active
FreezerState=running
SubState=running
FragmentPath=/lib/systemd/system/postfix@.service
SourcePath=
DropInPaths=
UnitFileState=enabled-runtime
UnitFilePreset=enabled
StateChangeTimestamp=Sun 2021-12-05 15:59:10 CST
StateChangeTimestampMonotonic=15342458
InactiveExitTimestamp=Sun 2021-12-05 15:59:00 CST
InactiveExitTimestampMonotonic=5882660
ActiveEnterTimestamp=Sun 2021-12-05 15:59:10 CST
ActiveEnterTimestampMonotonic=15342458
ActiveExitTimestamp=
ActiveExitTimestampMonotonic=0
InactiveEnterTimestamp=
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=yes
CanIsolate=no
CanClean=
CanFreeze=yes
Job=
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
Markers=
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
JobTimeoutRebootArgument=
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Sun 2021-12-05 15:59:00 CST
ConditionTimestampMonotonic=5876609
AssertTimestamp=Sun 2021-12-05 15:59:00 CST
AssertTimestampMonotonic=5876611
Conditions=[unprintable]
Asserts=[unprintable]
LoadError=
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
FailureActionExitStatus=[not set]
SuccessAction=none
SuccessActionExitStatus=[not set]
RebootArgument=
InvocationID=2b5124c39b664054a2a1c19e78e0a9e3
CollectMode=inactive
Refs=
</pre>
</details>

**Comment by cloudwindy** [comment]
> ```
> systemctl show -o json --full --all postfix@-.service
> ```
This command won't fail as long as the format is ```<service_name>.service``` (normal units) or ```<service_name>@<argument>.service``` (template units with argument).

**Comment by cloudwindy** [comment]
If you need another example, as far as I know, the service of tor is ```tor@default.service```. Although there's ```tor.service``` but it can only be used to reload other tor instances and starting this service doesn't actually start tor. You can try ```systemctl list-units -t service -o json``` to get a list of all services currently loaded (and this list includes template units).

**Comment by kiarn** [comment]
Unfortunately, if I list the services, I get : 

```
$ systemctl list-unit-files --no-pager | grep @
apport-forward@.service                static         
autovt@.service                        enabled        
container-getty@.service               static         
getty@.service                         enabled        
lvm2-pvscan@.service                   static         
mdadm-grow-continue@.service           static         
mdadm-last-resort@.service             static         
mdmon@.service                         static         
postfix@.service                       indirect
...
```
and I must ignore these services / templates, because the command

```
systemctl show -o json --full --all postfix@.service
```

will fail.

The command : 

```
systemctl show -o json --full --all postfix@argument.service
```

may work, but I don't know since I don't use templates, that's why I asked you if you can test it ( thank you for your answer ).

So, what I can do is : instead of removing all services containing `@`, I will remove all services containing `@.`, this will allow to list used templatesw with argument.

Arnaud
