### ISSUE TITLE
Remote archive is not reachable. Please check the address and login information

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#1373]
I tried to setup a remote archive with a google drive directory and when I test it I got this error : "Remote archive is not reachable. Please check the address and login information"
When trying a backup on the drive directory, the backup fails.
I deleted the drive and did it again from scratch, no change.
I authorized rclone and the link I gave to the system has all the permissions.

Am I missing something ?

**Comment by kiarn** [comment]
Hello @romainRoch 

Are you talking about Ajenti 1 ? This is not supported anymore.

Arnaud
