### ISSUE TITLE
installation error debian bullseye armv5

### ISSUE THREAD

**Issue by dancremar** [ajenti/ajenti#1375]
<p>Collecting cryptography>=2.8
  Using cached cryptography-36.0.1.tar.gz (572 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/pip-standalone-pip-vkd8ygcl/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ehhqyqtq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4'
       cwd: None
  Complete output (108 lines):
  Collecting setuptools>=40.6.0
    Using cached setuptools-60.1.1-py3-none-any.whl (952 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting cffi>=1.12
    Using cached cffi-1.15.0.tar.gz (484 kB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting setuptools-rust>=0.11.4
    Using cached setuptools_rust-1.1.2-py3-none-any.whl (21 kB)
  Collecting pycparser
    Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
  Collecting typing-extensions>=3.7.4.3
    Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
  Collecting semantic-version<3,>=2.8.2
    Using cached semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
  Building wheels for collected packages: cffi
    Building wheel for cffi (setup.py): started
    Building wheel for cffi (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-57saovjp
         cwd: /tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/
    Complete output (35 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-armv5tel-3.9
    creating build/lib.linux-armv5tel-3.9/cffi
    copying cffi/lock.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/cparser.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/model.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/verifier.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/__init__.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/api.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/error.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv5tel-3.9/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-armv5tel-3.9/cffi
    running build_ext
    creating build/temp.linux-armv5tel-3.9
    creating build/temp.linux-armv5tel-3.9/c
    arm-linux-gnueabi-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-Nm8yNO/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-armv5tel-3.9/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
       15 | #include <ffi.h>
          |          ^~~~~~~
    compilation terminated.
    error: command '/usr/bin/arm-linux-gnueabi-gcc' failed with exit code 1
    ----------------------------------------
    ERROR: Failed building wheel for cffi
    Running setup.py clean for cffi
  Failed to build cffi
  Installing collected packages: typing-extensions, setuptools, semantic-version, pycparser, wheel, setuptools-rust, cffi
      Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cc76yipf/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-ehhqyqtq/overlay --compile --install-headers /tmp/pip-build-env-ehhqyqtq/overlay/include/python3.9/cffi
           cwd: /tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/
      Complete output (37 lines):
      running install
      /usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-armv5tel-3.9
      creating build/lib.linux-armv5tel-3.9/cffi
      copying cffi/lock.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/cparser.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/model.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/verifier.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/recompiler.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/commontypes.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/__init__.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/api.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/error.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/_embedding.h -> build/lib.linux-armv5tel-3.9/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-armv5tel-3.9/cffi
      running build_ext
      creating build/temp.linux-armv5tel-3.9
      creating build/temp.linux-armv5tel-3.9/c
      arm-linux-gnueabi-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-Nm8yNO/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-armv5tel-3.9/c/_cffi_backend.o
      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
         15 | #include <ffi.h>
            |          ^~~~~~~
      compilation terminated.
      error: command '/usr/bin/arm-linux-gnueabi-gcc' failed with exit code 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p9p0jb2j/cffi_23a56ba1607446e880d3fa014a9e4c4f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cc76yipf/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-ehhqyqtq/overlay --compile --install-headers /tmp/pip-build-env-ehhqyqtq/overlay/include/python3.9/cffi Check the logs for full command output.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f9/4b/1cf8e281f7ae4046a59e5e39dd7471d46db9f61bb564fddbff9084c4334f/cryptography-36.0.1.tar.gz#sha256=53e5c1dc3d7a953de055d77bef2ff607ceef7a2aac0353b5d630ab67f7423638 (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/bin/python3 /tmp/pip-standalone-pip-vkd8ygcl/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ehhqyqtq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.</p>

**Comment by kiarn** [comment]
Hello,

Please try to format your post in order to make it readable, like using the code tag.
Arm cannot be supported at the moment, please see https://github.com/ajenti/ajenti/issues/1325 for more explanations.

Arnaud

**Comment by Renaud-Pagin** [comment]
Hello,

fatal error: ffi.h: No such file or directory

Try : apt install libffi-dev

Regards
