### ISSUE TITLE
Attempt to create new file in File Manager 

### ISSUE THREAD

**Issue by alpauna** [ajenti/ajenti#1376]
Server error
 Server error occured. This is likely a bug.
Request
POST /api/filesystem/write//etc/ssl/domain-certs/alshowto.key?encoding=utf-8
Type
AttributeError
Message
'NoneType' object has no attribute 'decode'
Traceback
Traceback (most recent call last):
` File "/usr/local/lib/python3.9/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ajenti_plugin_filesystem/views.py", line 87, in handle_api_fs_write
    content = content.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'`
 

Attempted to create a new file in a new directory that I created caused this issue.
Also, just installed via automatic install mentioned [here](http://docs.ajenti.org/en/latest/man/install.html) 

As noted on page not all functions have been tested

**Comment by alpauna** [comment]
Forgot to include version Ajenti core 2.1.43, no upgrades available.
Also this is on Debian 11

**Comment by kiarn** [comment]
Hello @alpauna 

Thanks for the feedback and the description, I could reproduce this, and I think it's fixed.

Arnaud
