### ISSUE TITLE
Does anyone provide commercial support for Ajenti?

### ISSUE THREAD

**Issue by kiwiheretic** [ajenti/ajenti#1380]
We are in the market for a panel as an alternative to CPanel or Plesk but we need to know someone has our back.  Is Ajenti the right solution for us?

We are looking for something with reseller ability (ie sub accounts).  Ability to host WordPress and extra points for Wagtail sites.

**Comment by kiarn** [comment]
Hello @kiwiheretic 

There's currently no commercial for Ajenti, and I don't think Ajenti fulfill your requirements.

Regards

Arnaud
