### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by xmyoard** [ajenti/ajenti#1384]
Hi, 
I used the automatic script for installation and after it being completed, I can't still access the panel
any help is kindly appreciated.
![image](https://user-images.githubusercontent.com/87631878/157190881-644480cc-ac1b-4c94-8189-ef02e03ea151.png)

thanking you,
Adarsh

**Comment by kiarn** [comment]
Hi @Aadi-mone

Did you try on port 8000 with https ?

Arnaud

**Comment by xmyoard** [comment]
No, I still can access it.

thank you.

**Comment by kiarn** [comment]
Ok, try the following : 

```
systemctl stop ajenti
ajenti-panel --dev
```

This should start `Ajenti` with debug logs in the console. You can exit it with Ctrl + C, and then restart `Ajenti` with `systemctl`. Please show if you encounter an error while running `Ajenti` in the console.

You can also see if there's any error in `/var/log/ajenti/ajenti.log`

Arnaud

**Comment by xmyoard** [comment]
It was solved when i restarted the service, I was dumb xd
thank you

**Comment by kiarn** [comment]
Good, so I can close it :+1:
