### ISSUE TITLE
Plugin Homepage change to doc page?

### ISSUE THREAD

**Issue by cjerrington** [ajenti/ajenti#1386]
I was interested in a few of the plugins and wanted to know more information. The home page link goes to the main website. Could this be changed to the [docs link](http://docs.ajenti.org/en/latest/) for that plugin in question? 

Is this configured in the `plugin.yml` file? If so, I could work on making a pull request if it'll help. 

![image](https://user-images.githubusercontent.com/8809376/162065875-5492f04b-2822-4021-b097-263fd9bd86df.png)

**Comment by kiarn** [comment]
Hello @cjerrington 

Thanks !  It's good idea. I've started last week to write some basic documentation about the plugins, and I have added a direct to the related pages.

Arnaud

**Comment by cjerrington** [comment]
Thanks! I think once the app is installed and your browsing the plugins to install it might help to have the link so users can get more information.
