### ISSUE TITLE
Supervisor plugin failes to start created process

### ISSUE THREAD

**Issue by waclawthedev** [ajenti/ajenti#1388]
It leads to fatal error during supervisor process start
How to reproduce:
1. Add any process via Supervisor plugin
2. Try to start the process
3. The browser console will say `Error: undefined is not an object (evaluating 'service.managerId')`
4. Nothing happens next

**env:**
Debian GNU/Linux 11 (bullseye)
Supervisor plugin 0.19
Ajenti core 2.1.44

**Comment by kiarn** [comment]
Hello @waclawthedev 

Thanks for the report and the issues, I will only answer here : the supervisor plugin is not finished yet.
I don't use it and I'm actually very busy with others upgrades, so it will take some time before I can correct this.

Arnaud
