### ISSUE TITLE
Ajenti doesn't enable https during the installation

### ISSUE THREAD

**Issue by waclawthedev** [ajenti/ajenti#1389]
How to reproduce:
1. Use `curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -`
2. Wait for installation
3. Take a look at `:: Complete
Ajenti will be listening at https://[your_ip]
Log in with your root password or another OS user`
4. Check the https://[your_ip]
5. It will fail, just **http**://[your_ip] is available after installation

**env:**
Debian GNU/Linux 11 (bullseye)
Ajenti core 2.1.44

**Comment by kiarn** [comment]
Hello @waclawthedev 

It seems there's a problem with the dependency on `PyOpenSSl`, I will fix it.
Can you please try the folllowing, as root: 

```
pip3 install -U pyOpenSSl # should be version 22.0.0
/usr/local/bin/ajenti-ssl-gen YOUR_HOSTNAME
systemctl restart ajenti.service
```

Arnaud

**Comment by waclawthedev** [comment]
@kiarn i just signed in, generated the self signed certificate and enabled ssl
