### ISSUE TITLE
Authentication failed Help

### ISSUE THREAD

**Issue by linkea131** [ajenti/ajenti#1394]
09.05.2022 04:41  [rstrct  5106]          gate.py:123   DEBUG                        ... POST /api/core/auth
09.05.2022 04:41  [rstrct  5106]          gate.py:123   ERROR    Error checking password: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fcff190be10>
command: /bin/sh
args: ['/bin/sh', '-c', '/bin/su -c "/bin/echo SUCCESS" - root']
buffer (last 100 chars): b'\xe5\xaf\x86\xe7\xa0\x81\xef\xbc\x9a'
before (last 100 chars): b'\xe5\xaf\x86\xe7\xa0\x81\xef\xbc\x9a'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 5231
child_fd: 15
closed: False
timeout: 25
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'.*:'")
09.05.2022 04:41  [...     5106]           api.py:110   WARN     Failed login from root at IP : 192.168.0.199
09.05.2022 04:41  [master  5065]    middleware.py:221   DEBUG  28.157   33.0 bytes   200 POST /api/core/auth
09.05.2022 04:41  [master  5065]       handler.py:242   INFO   192.168.0.199 - - [2022-05-09 04:41:57] "POST /api/core/auth HTTP/1.1" 200 193 28.157874

OS：Centos 8 Linux
virtual environment：vmware

**Comment by kiarn** [comment]
Hello @linkea131,

That's a problem with the shell locales : `Ajenti` is awaiting the false string from the prompt to give the password.
I will have a look at this next week. Which `Python3` version do you have ?

Cheers

Arnaud

**Comment by linkea131** [comment]
python3.6.8 installed automatically when ajenti2 is installed

**Comment by kiarn** [comment]
Hello,

This should be fixed in the next version, thanks for the report.

Cheers,

Arnaud
