### ISSUE TITLE
Can't connect to the panel

### ISSUE THREAD

**Issue by SikinoGaming** [ajenti/ajenti#1395]
I installed Ajenti with install.sh, install_venv.sh, pip, copied the GitHub repo and did build and install with setup.py but every time I run it with ``ajenti-panel``, ``./ajenti/ajenti-panel/ajenti-panel`` or ``ajenti/ajenti-panel/packaging/files/ajenti``, I get the same result. Can you help me?
Thanks in advance, @SikinoGaming

**Comment by kiarn** [comment]
Hello,

It's simplier to solve the problem if we only focus on one install method : using `install.sh`.
Please try it again and see in `/var/log/ajenti/ajenti.log` if there's some informations about the problem.

If not, you can stop the service ( depending on the OS you are using ) and launching `ajenti-panel --dev` to see what happen ( you can quit this with `Crtl + C` ). Which OS/version are you using ?

Cheers

Arnaud

**Comment by SikinoGaming** [comment]
I'm sorry to disturb you, it was Apache that was in confict with Ajenti but i have an other problem while trying to go to the panel :
![image](https://user-images.githubusercontent.com/71142041/169646351-d6d191b8-e7a4-4868-8561-c2385b1da510.png)

Hope you can help me.

**Comment by kiarn** [comment]
The panel is listening on `https`, you should not try to reach it with an `http` request.

**Comment by SikinoGaming** [comment]
Same thing
