### ISSUE TITLE
Problem while connectiong to the panel

### ISSUE THREAD

**Issue by SikinoGaming** [ajenti/ajenti#1396]
While connecting, browser say 

![image](https://user-images.githubusercontent.com/71142041/169691421-a996f365-828b-4b89-b80d-da64a73905b1.png)

Terminal say

![image](https://user-images.githubusercontent.com/71142041/169691431-cbf425a3-bfb0-427b-9ec7-840baa2c900d.png)

This is my conf.yml :

![image](https://user-images.githubusercontent.com/71142041/169691476-cbf3a72a-7682-44a0-9bc8-7f21568c54b9.png)

**Comment by kiarn** [comment]
Thanks for the report, I can confirm I forgot to handle one special case, and this should be solved.

Arnaud

**Comment by kiarn** [comment]
If you want to solve the problem now on your installation, just set `force` to `false` in `ssl` -> `client_auth`.

Arnaud
