### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by ZGLinus** [ajenti/ajenti#1398]
I want to use authentication provider user instead of OS, because the log show an error when I use authentication provider OS.

>  [rstrct 19269]          gate.py:123   ERROR    Error checking password: out of pty devices

But I cannot find the explanation of "user_config" on the docs. So, it crash.

If I want to use authentication user provider, what should I do with "user_config"?

 Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.1.44
Platform | centos / centos / "CentOS Linux release 7.9.2009 (AltArch)"
Architecture | aarch64
Python | 3.6.8
Debug | True
Loaded plugins | ace, core, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settings, terminal

Library | Version
------- | -------
gevent | 21.1.2
greenlet | 21.1.2
psutil | 5.9.1

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/aj/entry.py", line 39, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aj/core.py", line 176, in run
        middleware_stack = HttpMasterMiddleware.all(aj.context) + [gateway]
      File "/usr/local/lib/python3.6/site-packages/jadi/jadi.py", line 122, in _all
        return list(context.get_components(cls, ignore_exceptions=ignore_exceptions))
      File "/usr/local/lib/python3.6/site-packages/jadi/jadi.py", line 38, in get_components
        instance = self.get_component(comp)
      File "/usr/local/lib/python3.6/site-packages/jadi/jadi.py", line 32, in get_component
        self.component_instances[fqdn] = cls(self)
      File "/usr/local/lib/python3.6/site-packages/aj/security/pwreset.py", line 20, in __init__
        self.auth_provider = AuthenticationService.get(self.context).get_provider()
      File "/usr/local/lib/python3.6/site-packages/aj/auth.py", line 165, in get_provider
        raise AuthenticationError(f'Authentication provider {provider_id} is unavailable')
    aj.auth.AuthenticationError: Authentication provider user is unavailable

**Comment by kiarn** [comment]
Hello @ZGLinus 

It seems that the auth user plugin is missing. You can install it through the plugin management or manually as root with : 

```
pip3 install ajenti.plugin.auth-users
```

Arnaud

**Comment by ZGLinus** [comment]
It don't work. And the error was the as the previous.
So, what is the option "user_config" in auth for? And what should I change to make it work?
 
Here is config.yml.
```yaml
auth:
  allow_sudo: true
  emails: {}
  provider: user
  user_config: os
  users_file: /etc/ajenti/users.yml
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8001
color: default
max_sessions: 9
session_max_time: 3600
name: localhost
ssl:
  certificate:
  fqdn_certificate:
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: false
```

**Comment by kiarn** [comment]
Ha ok, I see, you are right, I forgot to mention this entry in the documentation. Each authentication provider stores the user configuration ( dashboard tabs, etc ... ) in differents directories, and `user_config` gives the possibility to manage this.

In most cases, the right configuration is : 

```
provider: os
user_config: os
```

or 

```
provider: users
user_config: users
```

I will add this in the documentation next week when I'm back at my computer.
I think you only forgot the 's' in the provider entry.

Arnaud

**Comment by ZGLinus** [comment]
It work!
One more question, how can I get hash of my password? Is it MD5, SHA-1 or another algorithm?

**Comment by ZGLinus** [comment]
It work!
One more question. How can I get the hash of my own password? The log shows that a algorithm "Scrpyt" is used, but I don't know the specific parameters of it.

**Comment by kiarn** [comment]
Hello @ZGLinus ,

This is 

```
import scrypt, os

scrypt.encrypt(os.urandom(256), password, maxtime=1)
```

Cheers,

Arnaud

**Comment by kiarn** [comment]
Can I close this issue ?

**Comment by ZGLinus** [comment]
I get the correct hash of my password. 
Ajenti failed to create configuration file because of permission problem. But I've given 777 to the configuration path.
Maybe I should try another panel.

**Comment by kiarn** [comment]
Give 777 to a configuration path should never be necessary, I never encounter this problem.
And I think it would be better to post here the error message, so I can eventually solve your problem.

Arnaud

**Comment by ZGLinus** [comment]
```
Server error
 Server error occured. This is likely a bug.
Request
GET /api/core/user-config
Type
PermissionError
Message
[Errno 13] permission denied: '/.config'
Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ajenti_plugin_core/views/config.py", line 64, in handle_api_user_config
    return UserConfigService.get(self.context).get_provider().data
  File "/usr/local/lib/python3.6/site-packages/aj/config.py", line 226, in get_provider
    for provider in UserConfigProvider.all(self.context):
  File "/usr/local/lib/python3.6/site-packages/jadi/jadi.py", line 122, in _all
    return list(context.get_components(cls, ignore_exceptions=ignore_exceptions))
  File "/usr/local/lib/python3.6/site-packages/jadi/jadi.py", line 38, in get_components
    instance = self.get_component(comp)
  File "/usr/local/lib/python3.6/site-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
  File "/usr/local/lib/python3.6/site-packages/aj/config.py", line 241, in __init__
    os.makedirs(_dir)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] permission denied: '/.config'
```

Here is the error message shown in the panel. Ajenti shows a message "Superuser access required", but Ajenti have been run under the root user.

**Comment by kiarn** [comment]
```PermissionError: [Errno 13] permission denied: '/.config'```

Ok, `/.config` is definitively the wrong path, it seems that the user under which you are using Ajenti is not recognized by the OS, the right path should be `/home/USER/.config`. For each user in `/etc/ajenti/users.yml`, there's an associated `uid` from the system, e.g. : 

```
  test:
    email: ..@...
    password: bla
    permissions: {}
    uid: 1002
```

So, an user with uid 1002 should exist on your system. If not, `~USER` will not expand to the right user path. Can you please verify this ?

> Ajenti shows a message "Superuser access required", but Ajenti have been run under the root user.

This is not related : the fact that `Ajenti` runs as root user does not mean that each `Ajenti` users will have access to all resources. It depends under which uid an user is logged. The permissions are flexible.

Arnaud
