### ISSUE TITLE
plugin install doesn't work

### ISSUE THREAD

**Issue by Ludo-code** [ajenti/ajenti#1403]
in ajenti 2 install of plugin supervisor doesn't work, when try to install and reload panel the app doesn't seems to be installed.

**Comment by kiarn** [comment]
Hello @Ludo-code 

The plugin supervisor does not work properly actually, there's many issues about, I need to correct it first.

Arnaud

**Comment by Ludo-code** [comment]
Yes thanks you so much for our reply :)
