### ISSUE TITLE
How to set ajenti on domain

### ISSUE THREAD

**Issue by Ludo-code** [ajenti/ajenti#1404]
Hello, I have wanted to know how to set an custom domain on ajenti on port 8000 my goal is to access it without enter the port, and ssl + http port are already in use and don't want to change port of other service ...

How to make it ?

**Comment by kiarn** [comment]
Hello @Ludo-code 

It's not possible to avoid the port in the url if you are using a custom port for https. It's not related to Ajenti, it's the common way to handle URLs.
The only way to do it is to install Ajenti behind a proxy which translate https://custom.domain.com to https://192.168.1.3:8000 ( if Ajenti is installed on an intern machine with IP 192.168.1.3, it's just an example ).

Edit : Example with Nginx : https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Arnaud

**Comment by Ludo-code** [comment]
What It's working thanks
