### ISSUE TITLE
Error Handling Widgets Without Elevation

### ISSUE THREAD

**Issue by FidesTorres** [ajenti/ajenti#1407]
When a Widget is added that has functions that need Elevation, when using the function without elevation a general error appears. (Reproduce: Add a widget for service Nginx (or Apache), then stop the service with the button on the widget, without Elevation.)

**Comment by kiarn** [comment]
Hello @FidesTorres 

Are you speaking from AJenti 1 ? There's no such widget nginx or apache in Ajenti 2 yet, and Ajenti 1 is not supported anymore.

Arnaud

**Comment by FidesTorres** [comment]
You can add a service. Including Nginx.

**Comment by kiarn** [comment]
Hello @FidesTorres 

Please add a screenshot from the error you are talking about, because I really don't understand what you mean.

Arnaud

**Comment by FidesTorres** [comment]
![Screenshot_2022-09-23_13-51-22](https://user-images.githubusercontent.com/43442463/191954781-ab436888-a1a8-43b3-b352-d55cf220e990.png)

**Comment by kiarn** [comment]
Hello @FidesTorres 

Many thanks for your contribution, it should be solved.

Arnaud
