### ISSUE TITLE
Timeout when starting after installing on Debian 11

### ISSUE THREAD

**Issue by 0xDedSec42** [ajenti/ajenti#1410]
I just installed Ajenti on an older server. After the installation finished Ajenti will timeout repeatedly after about 90 seconds.

```
● ajenti.service - Ajenti panel
     Loaded: loaded (/lib/systemd/system/ajenti.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Tue 2022-09-20 22:17:55 CEST; 3min 2s ago
    Process: 522 ExecStart=/opt/ajenti/bin/python3 /opt/ajenti/bin/ajenti-panel -d (code=killed, signal=>
        CPU: 1min 30.090s

Sep 20 22:16:25 cloud4-vm151 systemd[1]: Starting Ajenti panel...
Sep 20 22:17:55 cloud4-vm151 systemd[1]: ajenti.service: start operation timed out. Terminating.
Sep 20 22:17:55 cloud4-vm151 systemd[1]: ajenti.service: Failed with result 'timeout'.
Sep 20 22:17:55 cloud4-vm151 systemd[1]: Failed to start Ajenti panel.
Sep 20 22:17:55 cloud4-vm151 systemd[1]: ajenti.service: Consumed 1min 30.090s CPU time.
```

Is there a way to increase the value?

**Comment by 0xDedSec42** [comment]
I found that this seems to be a systemd thing. I increased the timeout of the ajenti.service to 900 seconds. The service is using one core to 100 % for the whole time and it quits again.

I have to mention that I used the venv method.

**Comment by 0xDedSec42** [comment]
I just tried the venv-method on a much more recent machine with the same behavior. You can reproduce it by using Debian 11 and https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install-venv.sh.

**Comment by kiarn** [comment]
Hello @ulfklose 

Thanks. I've just tested and I can confirm the timeout. I will have a look at this the next days.

Arnaud
