### ISSUE TITLE
Hosting and jail accounts on on AJenti 2

### ISSUE THREAD

**Issue by afidegnum** [ajenti/ajenti#1417]
How do I host an Nginx server and create jail accounts for users on Ajenti 2?

**Comment by kiarn** [comment]
Hello @afidegnum 

There's no nginx plugin yet on Ajenti 2.

Regards

Arnaud

**Comment by afidegnum** [comment]
what about docker ?

**Comment by kiarn** [comment]
There's already a little docker plugin to list images, containers, and display which are running.

Arnaud
