### ISSUE TITLE
Error accessing dashboard over https

### ISSUE THREAD

**Issue by Joly0** [ajenti/ajenti#1420]
![grafik](https://user-images.githubusercontent.com/13993216/210009663-d9d8f5e1-a9f3-4061-b933-91da14ff5ce0.png)
Hey, i just tried to setup ajenti, first manually installing it, and then using the installation script, but i keep getting the error from the screenshot "Errorcode: SSL_ERROR_RX_RECORD_TOO_LONG" everytime i try to access ajenti over https.
This issue doesnt occur when accessing over http., though i would prefer not to use http.

In the screenshot i used the domain my vps provided me with, though it doesnt work either, when using the dedicated ip adress of the server.

**Comment by kiarn** [comment]
Hello @Joly0 

That's a common error in firefox, and there's many way to solve it ( clear cache, update firefox, etc ... ).
To be sure, can you please try to access `Ajenti` with another browser ?

Arnaud
