### ISSUE TITLE
freebsd support

### ISSUE THREAD

**Issue by rafalohaki** [ajenti/ajenti#1428]
is freebsd fully supported?
what about arm64 freebsd, will it work?

**Comment by kiarn** [comment]
Hello @rafalohaki 

I don't know if the install process work on a freebsd machine. You can eventually try the automatic script and see if it works : https://docs.ajenti.org/en/latest/man/install.html

If not, you can post here the errors and I can try to solve it, but I do not have the time to handle it myself.

Cheers

Arnaud
