### ISSUE TITLE
Greenlet under debian 10 and python 3.11

### ISSUE THREAD

**Issue by cekvenich2** [ajenti/ajenti#1431]
GNU C17 (Debian 10.2.1-6) version 10.2.1 20210110 (x86_64-linux-gnu)
          compiled by GNU C version 10.2.1 20210110, GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.0, isl version isl-0.23-GMP
      
      GGC heuristics: --param ggc-min-expand=96 --param ggc-min-heapsize=125316
      Compiler executable checksum: 1f803793fa2e3418c492b25e7d3eac2f
      In file included from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.h:42:5: error: unknown type name ‘CFrame’
         42 |     CFrame* cframe;
            |     ^~~~~~
      src/greenlet/greenlet.c: In function ‘green_clear_exc’:
      src/greenlet/greenlet.c:173:17: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
        173 |     g->exc_state.exc_type = NULL;
            |                 ^
      src/greenlet/greenlet.c:175:17: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
        175 |     g->exc_state.exc_traceback = NULL;
            |                 ^
      src/greenlet/greenlet.c: In function ‘g_switchstack’:
      src/greenlet/greenlet.c:528:44: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_depth’; did you mean ‘recursion_limit’?
        528 |         current->recursion_depth = tstate->recursion_depth;
            |                                            ^~~~~~~~~~~~~~~
            |                                            recursion_limit
      src/greenlet/greenlet.c:529:38: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
        529 |         current->top_frame = tstate->frame;
            |                                      ^~~~~
            |                                      cframe
      src/greenlet/greenlet.c:552:25: warning: assignment to ‘int *’ from incompatible pointer type ‘_PyCFrame *’ [-Wincompatible-pointer-types]
        552 |         current->cframe = tstate->cframe;
            |                         ^
      src/greenlet/greenlet.c:577:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_depth’; did you mean ‘recursion_limit’?
        577 |         tstate->recursion_depth = target->recursion_depth;
            |                 ^~~~~~~~~~~~~~~
            |                 recursion_limit
      src/greenlet/greenlet.c:578:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
        578 |         tstate->frame = target->top_frame;
            |                 ^~~~~
            |                 cframe
      src/greenlet/greenlet.c:601:24: warning: assignment to ‘_PyCFrame *’ from incompatible pointer type ‘int *’ [-Wincompatible-pointer-types]
        601 |         tstate->cframe = target->cframe;
            |                        ^
      src/greenlet/greenlet.c: In function ‘g_initialstub’:
      src/greenlet/greenlet.c:813:5: error: unknown type name ‘CFrame’
        813 |     CFrame trace_info;
            |     ^~~~~~
      src/greenlet/greenlet.c:857:18: error: incompatible types when assigning to type ‘int’ from type ‘_PyCFrame’
        857 |     trace_info = *PyThreadState_GET()->cframe;
            |                  ^
      src/greenlet/greenlet.c:864:17: error: request for member ‘previous’ in something not a structure or union
        864 |     self->cframe->previous = &PyThreadState_GET()->root_cframe;
            |                 ^~
      src/greenlet/greenlet.c:878:50: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘recursion_depth’; did you mean ‘recursion_limit’?
        878 |     self->recursion_depth = PyThreadState_GET()->recursion_depth;
            |                                                  ^~~~~~~~~~~~~~~
            |                                                  recursion_limit
      src/greenlet/greenlet.c: In function ‘green_new’:
      src/greenlet/greenlet.c:1018:34: warning: assignment to ‘int *’ from incompatible pointer type ‘_PyCFrame *’ [-Wincompatible-pointer-types]
       1018 |         ((PyGreenlet*)o)->cframe = &PyThreadState_GET()->root_cframe;
            |                                  ^
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:45,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c: In function ‘green_traverse’:
      src/greenlet/greenlet.c:1124:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
       1124 |     Py_VISIT(self->exc_state.exc_type);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/objimpl.h:199:13: note: in definition of macro ‘Py_VISIT’
        199 |         if (op) {                                                       \
            |             ^~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:38,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1124:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
       1124 |     Py_VISIT(self->exc_state.exc_type);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/pyport.h:24:38: note: in definition of macro ‘_Py_CAST’
         24 | #define _Py_CAST(type, expr) ((type)(expr))
            |                                      ^~~~
      /usr/local/pyenv/versions/3.11.1/include/python3.11/objimpl.h:200:30: note: in expansion of macro ‘_PyObject_CAST’
        200 |             int vret = visit(_PyObject_CAST(op), arg);                  \
            |                              ^~~~~~~~~~~~~~
      src/greenlet/greenlet.c:1124:5: note: in expansion of macro ‘Py_VISIT’
       1124 |     Py_VISIT(self->exc_state.exc_type);
            |     ^~~~~~~~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:45,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1126:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
       1126 |     Py_VISIT(self->exc_state.exc_traceback);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/objimpl.h:199:13: note: in definition of macro ‘Py_VISIT’
        199 |         if (op) {                                                       \
            |             ^~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:38,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1126:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
       1126 |     Py_VISIT(self->exc_state.exc_traceback);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/pyport.h:24:38: note: in definition of macro ‘_Py_CAST’
         24 | #define _Py_CAST(type, expr) ((type)(expr))
            |                                      ^~~~
      /usr/local/pyenv/versions/3.11.1/include/python3.11/objimpl.h:200:30: note: in expansion of macro ‘_PyObject_CAST’
        200 |             int vret = visit(_PyObject_CAST(op), arg);                  \
            |                              ^~~~~~~~~~~~~~
      src/greenlet/greenlet.c:1126:5: note: in expansion of macro ‘Py_VISIT’
       1126 |     Py_VISIT(self->exc_state.exc_traceback);
            |     ^~~~~~~~
      src/greenlet/greenlet.c: In function ‘green_clear’:
      src/greenlet/greenlet.c:1162:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
       1162 |     Py_CLEAR(self->exc_state.exc_type);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/pyport.h:24:38: note: in definition of macro ‘_Py_CAST’
         24 | #define _Py_CAST(type, expr) ((type)(expr))
            |                                      ^~~~
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:581:29: note: in expansion of macro ‘_PyObject_CAST’
        581 |         PyObject *_py_tmp = _PyObject_CAST(op); \
            |                             ^~~~~~~~~~~~~~
      src/greenlet/greenlet.c:1162:5: note: in expansion of macro ‘Py_CLEAR’
       1162 |     Py_CLEAR(self->exc_state.exc_type);
            |     ^~~~~~~~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:44,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1162:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
       1162 |     Py_CLEAR(self->exc_state.exc_type);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:583:14: note: in definition of macro ‘Py_CLEAR’
        583 |             (op) = NULL;                        \
            |              ^~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:38,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1164:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
       1164 |     Py_CLEAR(self->exc_state.exc_traceback);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/pyport.h:24:38: note: in definition of macro ‘_Py_CAST’
         24 | #define _Py_CAST(type, expr) ((type)(expr))
            |                                      ^~~~
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:581:29: note: in expansion of macro ‘_PyObject_CAST’
        581 |         PyObject *_py_tmp = _PyObject_CAST(op); \
            |                             ^~~~~~~~~~~~~~
      src/greenlet/greenlet.c:1164:5: note: in expansion of macro ‘Py_CLEAR’
       1164 |     Py_CLEAR(self->exc_state.exc_traceback);
            |     ^~~~~~~~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:44,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1164:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
       1164 |     Py_CLEAR(self->exc_state.exc_traceback);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:583:14: note: in definition of macro ‘Py_CLEAR’
        583 |             (op) = NULL;                        \
            |              ^~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:38,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c: In function ‘green_dealloc’:
      src/greenlet/greenlet.c:1256:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
       1256 |     Py_CLEAR(self->exc_state.exc_type);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/pyport.h:24:38: note: in definition of macro ‘_Py_CAST’
         24 | #define _Py_CAST(type, expr) ((type)(expr))
            |                                      ^~~~
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:581:29: note: in expansion of macro ‘_PyObject_CAST’
        581 |         PyObject *_py_tmp = _PyObject_CAST(op); \
            |                             ^~~~~~~~~~~~~~
      src/greenlet/greenlet.c:1256:5: note: in expansion of macro ‘Py_CLEAR’
       1256 |     Py_CLEAR(self->exc_state.exc_type);
            |     ^~~~~~~~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:44,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1256:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’
       1256 |     Py_CLEAR(self->exc_state.exc_type);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:583:14: note: in definition of macro ‘Py_CLEAR’
        583 |             (op) = NULL;                        \
            |              ^~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:38,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1258:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
       1258 |     Py_CLEAR(self->exc_state.exc_traceback);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/pyport.h:24:38: note: in definition of macro ‘_Py_CAST’
         24 | #define _Py_CAST(type, expr) ((type)(expr))
            |                                      ^~~~
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:581:29: note: in expansion of macro ‘_PyObject_CAST’
        581 |         PyObject *_py_tmp = _PyObject_CAST(op); \
            |                             ^~~~~~~~~~~~~~
      src/greenlet/greenlet.c:1258:5: note: in expansion of macro ‘Py_CLEAR’
       1258 |     Py_CLEAR(self->exc_state.exc_traceback);
            |     ^~~~~~~~
      In file included from /usr/local/pyenv/versions/3.11.1/include/python3.11/Python.h:44,
                       from src/greenlet/greenlet.h:8,
                       from src/greenlet/greenlet.c:11:
      src/greenlet/greenlet.c:1258:29: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’
       1258 |     Py_CLEAR(self->exc_state.exc_traceback);
            |                             ^
      /usr/local/pyenv/versions/3.11.1/include/python3.11/object.h:583:14: note: in definition of macro ‘Py_CLEAR’
        583 |             (op) = NULL;                        \
            |              ^~
      src/greenlet/greenlet.c: In function ‘PyGreenlet_New’:
      src/greenlet/greenlet.c:1777:15: warning: assignment to ‘int *’ from incompatible pointer type ‘_PyCFrame *’ [-Wincompatible-pointer-types]
       1777 |     g->cframe = &PyThreadState_GET()->root_cframe;
            |               ^
      error: command '/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
ERROR: Could not build wheels for gevent, which is required to install pyproject.toml-based projects

**Comment by kiarn** [comment]
Hello @cekvenich2 

What did you do exactly ? Installing Ajenti on Debian 10 via automatic install script ? Or anything else ?
Can you please describe it ?

Arnaud

**Comment by cekvenich2** [comment]
Yes, I get ERROR: Failed building wheel for greenlet on Debian 11(updated), Node 8.14 and Python 3.11.1 using the auto install. Oddly: it works, anjeti works and I use it. I assume that if I do manual install there would not be errors.

**Comment by kiarn** [comment]
Ok, thanks, I can confirm on Debian 10 with Python 3.11 as default python.
It seems I need to pin an higher version of gevent and greenlet, but I must first test it.

**Comment by kiarn** [comment]
Gipc still depends on greenlet < 2.0, and a new version of gipc should soon be released : https://github.com/jgehrcke/gipc/issues/125

**Comment by kiarn** [comment]
Hello,

It's possible to install Ajenti on Debian 11 with Python 3.11 with the latest version (2.2.5).
But I just saw a problem with the cookies library which stops Ajenti start. I will habe a look at this this week.

**Comment by kiarn** [comment]
This should now be solved with the new version 2.2.6.
