### ISSUE TITLE
Ajenti 1.x install on Ubuntu 22.04

### ISSUE THREAD

**Issue by Serasar** [ajenti/ajenti#1433]
Trying to install Ajenti 1.x on Ubuntu 22.04
Have error:
`The following packages have unmet dependencies:
 ajenti : Depends: python (>= 2.6) but it is not installable
          Depends: python-support (>= 0.90.0) but it is not going to be installed
          Depends: python-lxml (>= 2.2.4) but it is not installable
          Depends: python-gevent but it is not going to be installed
          Depends: python-gevent-socketio but it is not going to be installed
          Depends: python-psutil (>= 0.6.0) but it is not going to be installed
          Depends: python-reconfigure (>= 0.1.46) but it is not going to be installed
          Depends: python-daemon but it is not installable
          Depends: python-passlib but it is not going to be installed
          Depends: python-requests (>= 0.12.0) but it is not going to be installed
          Depends: python-dbus but it is not installable
          Depends: python-imaging but it is not installable
          Depends: python-catcher but it is not going to be installed
          Depends: python-exconsole (>= 0.1.5) but it is not going to be installed
          Depends: python-ldap but it is not installable`
Tried solution from here:https://support.ajenti.org/communities/1/topics/1657-installation-issue-the-following-packages-have-unmet-dependencies
But get init error:
`Feb 17 08:17:45 mine1863 systemd[1]: Starting LSB: Ajenti...
Feb 17 08:17:45 mine1863 ajenti[28982]: Starting Ajenti:
Feb 17 08:17:45 mine1863 ajenti[28987]: /etc/init.d/ajenti: 52: /usr/bin/ajenti>
Feb 17 08:17:45 mine1863 ajenti[28982]:  * failed
Feb 17 08:17:45 mine1863 systemd[1]: Started LSB: Ajenti.
Feb 17 08:18:59 mine1863 systemd[1]: Stopping LSB: Ajenti...
Feb 17 08:18:59 mine1863 ajenti[29058]: Stopping Ajenti:
Feb 17 08:18:59 mine1863 ajenti[29058]:  * not running
Feb 17 08:18:59 mine1863 systemd[1]: ajenti.service: Deactivated successfully.
Feb 17 08:18:59 mine1863 systemd[1]: Stopped LSB: Ajenti.`
Maybe packages should be updated to work with modern python2 packages?

**Comment by kiarn** [comment]
Hello @Serasar ,

Ajenti 1 is since years not maintained anymore. I'm only working on Ajenti 2 and 3.

Regards,

Arnaud
