### ISSUE TITLE
Can not login Ajenti after Nginx by HTTPS

### ISSUE THREAD

**Issue by GOKORURI007** [ajenti/ajenti#1435]
### What happened
I used Nginx to reverse proxy Ajenti through my domain. When I used HTTP, everything worked fine. But when I used HTTPS, I couldn't log into Ajenti. It seems that all of the static resources are unreachable.

### When I used HTTP
![image](https://user-images.githubusercontent.com/40916324/221445470-c1160e79-89f3-4e2a-8349-e7d429d3404e.png)
### When I used HTTPS
![image](https://user-images.githubusercontent.com/40916324/221445501-3f0188a1-bf58-4d36-8301-f8e653fc42b1.png)
### My Nginx config
```
server
{
    listen 80;
    server_name example.com;
    root  /home/wwwroot/example.com;
    
location /
    {
        proxy_pass http://localhost:8000;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    access_log  /home/wwwlogs/example.com.log;
}

server
{
    listen 443 ssl http2;
    server_name example.com;
    root  /home/wwwroot/example.com;
    
    ssl_certificate /etc/letsencrypt/live/example.com/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
    ssl_session_cache builtin:1000 shared:SSL:10m;
    ssl_dhparam /usr/local/nginx/conf/ssl/dhparam.pem;
    
    include rewrite/other.conf;
 
    location / 
    {
        proxy_pass http://localhost:8000;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    access_log  /home/wwwlogs/example.com.log;
}

```

**Comment by kiarn** [comment]
Hello @GOUKOU007 

`Ajenti` tests the origin of the request to ensure the request is valid. I think in your case it's necessary to complete the `trusted_domains` parameter with the extern domain in the config file : http://docs.ajenti.org/en/latest/man/config.html#other-global-parameters

I hope it helps

Arnaud

**Comment by GOKORURI007** [comment]
Thank you for your reply but the resolution do not work for me.
I have tried to add my domain into trusted_domains by these way:
```
trusted_domains: [www.example.com]
trusted_domains: ["www.example.com"]
trusted_domains: [http://www.example.com]
```
Unfortunately, none of them helps me login into ajenti by HTTPS. However, if I use HTTP with my domain just like http://www.example.com:8000, I can login into ajenti correctly. So I guess that maybe not a `trusted_domains` problem.

**Comment by kiarn** [comment]
I think you need to specify https protocol for this, because you reach your site with the external url `https://www.example.com` and not `http://www.example.com`.
I forgot to say this, but I'm sure you already know it, it's necessary to restart Ajenti in order to use the new values.

**Comment by GOKORURI007** [comment]
Thank you! It works well now!

**Comment by kiarn** [comment]
Ok, thank you for the feedback !
