### ISSUE TITLE
Connecting to ajenti on Ubuntu 22.04

### ISSUE THREAD

**Issue by NikLever** [ajenti/ajenti#1455]
I cannot connect to https://195.20.254.172:8000/ I get 'This site cannot be reached'

Here are some outputs. Mean nothing to me. But might help someone.

`root@ubuntu:~# netstat -tlnp | grep 8000
tcp 0 0 0.0.0.0:8000 0.0.0.0:* LISTEN 2968/python3

root@ubuntu:~# ps aux | grep ajenti
root 2968 0.1 3.4 192736 68776 ? S 09:44 0:01 /usr/bin/python3 /usr/local/bin/ajenti-panel -d
nobody 2974 0.0 2.5 118968 49832 ? S 09:44 0:00 /usr/local/bin/ajenti-panel worker [restricted session]
root 3394 0.0 0.1 4024 2148 pts/0 R+ 10:05 0:00 grep --color=auto ajenti`

**Comment by kiarn** [comment]
Hello @NikLever 

The output you brought are meaning that Ajenti is listening on port 8000, it seems to be ok from this point of view.
Is there some firewall blocking the direct access to the ip ? 
Is Ajenti really running in https mode ? (you can check it in `/etc/ajenti/config.yml`)

Or is there maybe some errors shown in `/var/log/ajenti/` ?

Arnaud
