### ISSUE TITLE
Does this project provide commercial support?

### ISSUE THREAD

**Issue by webquest-nz** [ajenti/ajenti#1456]
Basically question is in the title as we need to know if anyone is providing commercial support for this project.  It looks straightforward to install but sometimes unexpected things happen and we need to know we are covered.

I tried asking on the forum but I guess I went to an old one as it seemed to be dead.

Thanks.

**Comment by kiarn** [comment]
Hello @webquest-nz 

I do not provide commercial support, I work on it on my free time.
Ajenti is used in other projects like linuxmuster.net which are supported by IT companies, and I fix the issues as soon as I get a description of the problem. If you encounter some problem, I may try to solve it as fast as I can :)

Cheers

Arnaud
