### ISSUE TITLE
“Available plugins” take a long time to load on Debian 11.7

### ISSUE THREAD

**Issue by tyultra** [ajenti/ajenti#1457]
After clicking “Plugins”, it takes a long time to load the "Available plugins" list, anything I can do to make it faster? VPS location：CN.
Thank you.
![image](https://github.com/ajenti/ajenti/assets/36122504/10c2bdc7-b459-45bb-b389-6fb050845b40)

**Comment by kiarn** [comment]
Hello @tyultra,

Requests for available plugins are sent to https://pypi.org.
Can you access this URL from your VPN ?

Cheers

Arnaud
