### ISSUE TITLE
Docker images and containers are not shown in the plugin - venv incompatibility?

### ISSUE THREAD

**Issue by Magneticdud** [ajenti/ajenti#1458]
I installed this on a fresh debian 12, which required ajenti v2 to be installed in the python virtual environment.

I also installed docker and have a couple containers running and some images downloaded. The web ui says nothing found, both in containers and in the images.

It's an incompatibility with venv that can't talk with the docker daemon or i did some other mistake?

**Comment by kiarn** [comment]
Hello @Magneticdud 

Installing Ajenti in venv should not affect the docker plugin.
What are the output of `which docker` ? (commonly `/usr/bin/docker`)
Do you get some data with  `/usr/bin/docker stats --format '{{json .}}' --no-stream -a` ?

Regards

Arnaud

**Comment by Magneticdud** [comment]
huh, weird. I did the docker stats command, but then when i went back to check on the web panel, i could see everything, containers, images, cpu and memory usage and so on.

So now it works even if  i did not do anything

i like this panel, thanks to everyone for everything

**Comment by Magneticdud** [comment]
I now know why I could not see the docker images and containers at that time.

I installed docker with the rootless mode.

When I did another test on a fresh install, instead i installed docker as root and it showed in ajenti.

So, if anyone else can't see the containers or images, need to run docker as root, not as user
