### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by knagyorg** [ajenti/ajenti#1460]
Hi all,
what is the correct Nginx configuration setting for Ajenti2? Is there an example of such a configuration?
Regards
Karel

**Comment by kiarn** [comment]
Hi @knagyorg 

Ajenti implements his own web server, you don't need nginx nor apache. Or are you trying to set up a reverse proxy ?

Regards

Arnaud

**Comment by knagyorg** [comment]
Hi @kiarn,
sorry for the inaccuracy - yes I meant to use a reverse proxy.
Regards
Karel

**Comment by kiarn** [comment]
Hi @knagyorg,

You can just use a standard reverse proxy configuration fo nginx. In a default installation, ajenti is listening on port 8000, so something like:

```
location / {
    proxy_pass http://AJENTI_SERVER_IP:8000;
}
```

On the Ajenti server, you also need to add the FQDN in `/etc/ajenti/config.yml` in the `trusted_domains` list, something like:

```
trusted_domains: ["http://MYDOMAIN/"]
```

(with the right protocol)

Regards

Arnaud

**Comment by knagyorg** [comment]
@kiarn thank you very much for the instructions. I also found an old article for using Ajenti behind Nginx (https://support.ajenti.org/knowledge-bases/5/articles/1129-ajenti-behind-nginx) and now it already works.
Regards
Karel
