### ISSUE TITLE
Error: $q is not defined

### ISSUE THREAD

**Issue by cweikl** [ajenti/ajenti#1461]
Having started the WebUI Setup, I get to the final step "Setup Complete"". As I click "close", I receive a hint that an unhandled error occurred (start browser console) and "could not restart".
As I start the browser console (firefox) I get the following errors:

`12:24:15.690 HTTPS: hostname is an IP - host is not upgradable 10.0.0.1 [background.js:29812:21](moz-extension://dc73f03b-9e09-472a-8a53-4713b3a93109/public/js/background.js)
12:24:15.907
Unhandled exception occured [all.js:725:17](http://10.0.0.1/resources/all.js)
12:24:15.908 Consider sending this error to https://github.com/ajenti/ajenti/issues/new [all.js:726:17](http://10.0.0.1/resources/all.js)
12:24:15.908
Error: $q is not defined
this.restartUI/<@http://10.0.0.1/resources/all.js:5887:13
processQueue@http://10.0.0.1/resources/all.vendor.js:16716:28
qFactory/scheduleProcessQueue/<@http://10.0.0.1/resources/all.vendor.js:16732:39
$eval@http://10.0.0.1/resources/all.vendor.js:18014:28
$digest@http://10.0.0.1/resources/all.vendor.js:17828:31
$apply@http://10.0.0.1/resources/all.vendor.js:18122:24
done@http://10.0.0.1/resources/all.vendor.js:12102:47
completeRequest@http://10.0.0.1/resources/all.vendor.js:12311:15
requestLoaded@http://10.0.0.1/resources/all.vendor.js:12239:24
[all.vendor.js:14219:24](http://10.0.0.1/resources/all.vendor.js)
    consoleLog http://10.0.0.1/resources/all.vendor.js:14219
    <anonym> http://10.0.0.1/resources/all.js:727
    processQueue http://10.0.0.1/resources/all.vendor.js:16724
    scheduleProcessQueue http://10.0.0.1/resources/all.vendor.js:16732
    $eval http://10.0.0.1/resources/all.vendor.js:18014
    $digest http://10.0.0.1/resources/all.vendor.js:17828
    $apply http://10.0.0.1/resources/all.vendor.js:18122
    done http://10.0.0.1/resources/all.vendor.js:12102
    completeRequest http://10.0.0.1/resources/all.vendor.js:12311
    requestLoaded http://10.0.0.1/resources/all.vendor.js:12239`

Setting up lmn7.2 via WEBUI Setup stops here.
![Bildschirmfoto vom 2023-12-21 12-25-48](https://github.com/ajenti/ajenti/assets/16056720/27120f0c-5ad1-48ab-b75c-e2008e5f2dd0)

**Comment by kiarn** [comment]
Hello @cweikl 

Thanks, missing $q is now solved: https://github.com/linuxmuster/linuxmuster-webui7/commit/2868f91754108bcd2c5c3617004860d6cb3578ab (issue by webui7 ;) ). It would be interesting to know why the restart did not work, but it's another issue.

Arnaud

**Comment by kiarn** [comment]
I found out why the restart failed, and solved it too: https://github.com/linuxmuster/linuxmuster-webui7/commit/98602c907ab86a14cf7a3a896d7a27458389b096
