### ISSUE TITLE
fail to install debian bookworm 

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#1470]
arm-linux-gnueabihf-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-311/src/c/_cffi_backend.o
            src/c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
               15 | #include <ffi.h>
                  |          ^~~~~~~
            compilation terminated.
            error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by kiarn** [comment]
Hello,

There's actually no support for arm installation. There's some thread here related to this problem, but I did not have the time to test it deeply. The main problem is to install cffi on this platform, which is not an issue related to Ajenti.

Arnaud

**Comment by ghost** [comment]
Then install cffi from source for arm64

pip3 install --no-cache cffi --no-binary :all:

link:[ ](https://stackoverflow.com/questions/76624963/is-there-any-way-to-get-cffi-to-install-both-x86-64-and-arm64-mach-o-files-on-a)

**Comment by ghost** [comment]
https://stackoverflow.com/questions/76624963/is-there-any-way-to-get-cffi-to-install-both-x86-64-and-arm64-mach-o-files-on-a

**Comment by ghost** [comment]
also please fix your scripts to use pip3 now pip is for older systems

**Comment by kiarn** [comment]
Thanks for your input to install cffi, I will give it a try when I find the time.

> also please fix your scripts to use pip3 now pip is for older systems

I'm using `python3 -m pip` which is barely the same as `pip3`.

**Comment by szef1233** [comment]
>            arm-linux-gnueabihf-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-311/src/c/_cffi_backend.o
>             src/c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>                15 | #include <ffi.h>
>                   |          ^~~~~~~
>             compilation terminated.
>             error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
>             [end of output]
>       
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>         ERROR: Failed building wheel for cffi
>       Failed to build cffi
>       ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
>
