### ISSUE TITLE
is there any way to install ajenti offline ?

### ISSUE THREAD

**Issue by akashpatekar2312** [ajenti/ajenti#1477]

**Comment by kiarn** [comment]
Hello @akashpatekar2312,

I'm currently AFK, so I will provide a short answer: the [install script of Ajenti](https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install-venv.sh) is based on the installation of Python librairies via pip3 and some configurations check (e.g. create valid configuration files in /etc/ajenti ). So your question it basically the same as "is it possible to install pip packages and dependencies offline ?".

The answer is yes, but you will have to download all packages and dependencies on another system with the same architecture, and then copy it on the destination system, as described here: https://stackoverflow.com/a/14447068
