### ISSUE TITLE
Clarification of documentation

### ISSUE THREAD

**Issue by baltazartroisville** [ajenti/ajenti#1478]
Hi Arnaud,

First of all, I would like to thank you for your great project. 
You really seem to put your heart and soul and a lot of work into it, and for a few years now you seem to have had to do it all on your own. I can only admire that.

I just have one small suggestion to improve the documentation, when it comes to transactional email, it says that this feature is used to send notifications, such as password resets. What other notifications are there?
It would be great to have them all listed so you can consider whether you need these notifications at all.

Best regards

**Comment by kiarn** [comment]
Hi @baltazartroisville,

Thank you for your positive feedback, it's highly appreciated !
You are right, the documentation is not clear for this point: currently there's nooher notification sent as the password reset email. The backend to send emails is prepared, and could be used in other plugins, but that not the case actually.
I will update the documentation in this way when i'm coming back to my office.
