### ISSUE TITLE
Ajenti-panel WEB, root url cannot be changed

### ISSUE THREAD

**Issue by javabeanuser** [ajenti/ajenti#1480]
Unfortunatelly the /view part of the URL is hardcoded anc cannot be replaced or added a prefix for nginx ingress or etc reverse proxy.

**Comment by kiarn** [comment]
Hi,

I don't get what you are trying to achieve. You can always redirect a request to the root path of Ajenti via a reverse proxy, but yes, it's not possible to change some basic paths of Ajenti. Adding a prefix should not be a problem.
