### ISSUE TITLE
repo.ajenti.org is down

### ISSUE THREAD

**Issue by sercanarici** [ajenti/ajenti#1482]
hello @Eugeny 

I want to install ajenti 1x on ubuntu but failed because the http://repo.ajenti.org/ is down..

Is there any mirror for this repo?
Thanks.

![Screenshot 2024-07-09 at 22 41 10](https://github.com/ajenti/ajenti/assets/5367382/d6bc5a35-9094-47d6-80a6-bc95fafd6ca1)

**Comment by Eugeny** [comment]
Unfortunately it's gone for good. Domainfactory, where it was hosted, has ended their VPS offering and deleted the VM that hosted it. Somehow, I wasn't notified.

**Comment by sercanarici** [comment]
> Unfortunately it's gone for good. Domainfactory, where it was hosted, has ended their VPS offering and deleted the VM that hosted it. Somehow, I wasn't notified.

Oh no! Any alternative ways to install?

**Comment by Eugeny** [comment]
Building from source from the 1.x branch should still be possible: https://github.com/ajenti/ajenti/tree/1.x

**Comment by sercanarici** [comment]
Ok, thanks.
