### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AmeisenbeereReal** [ajenti/ajenti#1483]
Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 2.2.10
Platform | debian / ubuntu / Ubuntu 24.04 LTS
Architecture | x86_64
Python | 3.12.3
Debug | False
Loaded plugins | ace, core, dashboard, filemanager, filesystem, notepad, packages, passwd, plugins, services, settin>

Library | Version
------- | -------
gevent | 23.9.1
greenlet | 23.9.1
psutil | 5.9.8

    Traceback (most recent call last):
      File "/opt/ajenti/lib/python3.12/site-packages/aj/entry.py", line 29, in start
        aj.core.run(dev_mode=dev_mode, **kwargs)
      File "/opt/ajenti/lib/python3.12/site-packages/aj/core.py", line 208, in run
        context.load_cert_chain(certfile=fqdn_cert_path, keyfile=fqdn_cert_path)
    FileNotFoundError: [Errno 2] No such file or directory

**Comment by kiarn** [comment]
Hi,

It's a duplicate of #1432.
Workaround is: 

```
/usr/local/bin/ajenti-ssl-gen $(hostname)
systemctl restart ajenti.service
```

Regards

Arnaud

**Comment by bairog** [comment]
@AmeisenbeereReal Hello. How did you managed to install Ajenti on Ubuntu 24.04? Didn't you get **error: externally-managed-environment** during installation (at **Upgrading PIP** stage) like me #1486?
