### ISSUE TITLE
Login button results in ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Philanatidae** [ajenti/ajenti#1494]
After installing per the instructions on the website, I am able to connect via HTTP to the web interface:
<img width="960" alt="Screenshot 2024-12-27 at 9 47 25 PM" src="https://github.com/user-attachments/assets/02992095-3207-4657-b95a-4e3ccfde8c78" />
After logging in using my sudo (`root` as well), my web browser gives me an ERR_EMPTY_RESPONSE (Edge, but same error in Safari as well):
<img width="655" alt="Screenshot 2024-12-27 at 9 49 45 PM" src="https://github.com/user-attachments/assets/e39cc6f1-fac7-4b19-87dd-e30cfc79e0c5" />
No-where in the documentation does it mention this error.

**Comment by kiarn** [comment]
Hello @Philanatidae 

If you are using Ubuntu 24.04, please see https://github.com/ajenti/ajenti/issues/1486#issuecomment-2497506590

**Comment by Philanatidae** [comment]
That works @kiarn, thank you.. Looks like I forgot the distro I'm running, I have Debian Trixie. Looks like updating `gipc` is valid for Debian variants with this issue.

Closing b/c duplicate of #1486.
