### ISSUE TITLE
OpenVPN page shows "[Errno 111] Connection refused" and asks to configure OpenVPN plugin

### ISSUE THREAD

**Issue by vitalyve** [ajenti/ajenti#313]
If I log out from Ajenty and try to log in and open the OpenVPN page AFTER SEVERAL HOURS the page shows "[Errno 111] Connection refused" error message , "Please configure OpenVPN plugin" message and  OpenVPN plugin configuration dialog (with already filled in fields). Then it asks to restart Ajenti. After restart OpenVPN page works fine.

Screenshot: http://i.imgur.com/DlVNg6O.png

Ajenti working on Ubuntu Server 12.04.4.

**Comment by vitalyve** [comment]
Похоже, проблема в том, OpenVPN не закрывает открытую сессию, т.к. ждет команды exit или quit, в то время как плагин просто пытается закрыть текущее соединение после каждого обращения или же открыть новое, если окно браузера было закрыто и ты залогинился заново.

Вот тут описание менеджмент интерфейса: https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html

А в нем написано:

## COMMAND -- exit, quit

Close the managment session, and resume listening on the
management port for connections from other clients. Currently,
the OpenVPN daemon can at most support a single management client
any one time.

**Comment by delagen** [comment]
+1
