### ISSUE TITLE
[Suggestions] Ajenti/V

### ISSUE THREAD

**Issue by gxgani** [ajenti/ajenti#332]
Would like to suggest the following things:
- [x]  Switching to Maria-DB from MySQL.
- [x]  Displaying Ajenti Version on Dashboard? + Notification on new Update
- [x]  Page to customize PHP Configuration. (Like Memory Limit, shell_exec)
- [ ]  Ability to change MySQL and FTP Password.
- [ ]  Nginx Pagespeed module: https://github.com/pagespeed/ngx_pagespeed

Thanks, would keep adding them when I come across a new one.

**Comment by micahsoft** [comment]
Any news on getting the pagespeed module to work? Is there at least a manual workaround? 

thanks

**Comment by darit** [comment]
I'm also lurking around for a workaround to make Pagespeed work with Ajenti-V. If you find something please tell. (Following the Pagespeed install doesn't work :()

**Comment by 1Conan** [comment]
hmmmm thats wierd i dont think pagespeed would affect ajenti v lol

**Comment by darit** [comment]
Pagespeed must be installed into the nginx module to work, ajenti wont work if it's installed.

**Comment by stopspazzing** [comment]
Do you mind elaborating @darit ? Why not custom install nginx with pagespeed and by default have it off globally, but to use it enable it on a per site basis overriding default config?

Are you saying you have tested this and ajenti is un-accessable? Should be fine if pagespeed off; in nginx.conf

**Comment by 1Conan** [comment]
How does it affect Ajenti-V? im kinda wondering

**Comment by bernhardmostrey** [comment]
Any news on the pagespeed module?

**Comment by 1Conan** [comment]
@bernhardmostrey
You can compile nginx with it linked then replace the nginx binary installed by ajenti using it.
