### ISSUE TITLE
Regarding Docker based Agenti setup

### ISSUE THREAD

**Issue by paimpozhil** [ajenti/ajenti#415]
Hi Eugene,

I have setup this docker based ajenti panel

https://github.com/paimpozhil/WhatPanel

I hope you like it.. and I am trying to add more features to Ajenti to isolate one website from seeing another with help of docker/containers.

Also I believe we must make it easy for phpmyadmin to be used on-demand basis. 

Please tell me what you think.

**Comment by davidoster** [comment]
Hello people!
Any news on an updated docker version of ajent v?
