### ISSUE TITLE
[Feature] Need mysql user/database privilege assignment feature

### ISSUE THREAD

**Issue by paimpozhil** [ajenti/ajenti#432]
Right now it lets me create mysql user/database but i cant assign an user to the database.

it would be nice it has has that feature.

then there is a nice small Mysql php admin called "adminer.php" I guess we should include that may be .

 it already has the user/privilege management and is very simple however if we use this we need to package a php binary to help/run this.

Let me know if i should try doing this..

Im not a python programmer so my capabilities are very limited lol

**Comment by julianxhokaxhiu** [comment]
+1 for a solution or adminer. Both are win-win solutions.
