### ISSUE TITLE
Download remote files to local computer

### ISSUE THREAD

**Issue by sk1llsh0t** [ajenti/ajenti#582]
Can you add a feature where clicking a file will give the option to download the file to the local computer? if multiple files are checked, a download button will give the option to compress the file using zip, tar, etc, and then download that file.

**Comment by mikestp27** [comment]
I agree this would be nice to have.  Was also listed under ajenti-v by someone else: https://github.com/Eugeny/ajenti-v/issues/157

**Comment by mikestp27** [comment]
Good morning.  Is there any plans to work on this?   Am I the only one thinking this would be useful?
