### ISSUE TITLE
Enabling website maintenance mode in Ajenti V causes nginx error 

### ISSUE THREAD

**Issue by Mottoweb** [ajenti/ajenti#622]
nginx: [emerg] duplicate location "/" in /etc/nginx/conf.d/stagingcolorneedlecom.conf:61

Line 61 of that file: location / {

**Comment by tadaskarpavicius** [comment]
Same here. Got some time to track that it was maintenance mode which was causing this bug. Fix this ASAP

**Comment by tadaskarpavicius** [comment]
To reproduce just install ajenti and "friends". And add a new website (with maintenance - on, by default), then add recommended config for WP from here(http://support.ajenti.org/topic/353409-setting-up-a-php-website-with-ajenti-v-wordpress-example/)
And you will get the error straight away. 
The error goes away when you turn the Maintenace mode off
