### ISSUE TITLE
cant access ajenti with ssl

### ISSUE THREAD

**Issue by ShadyNawara** [ajenti/ajenti#636]
Hi, when i enable ssl in ajenti configuration. and type in my domain and port 8000 using https i get an connection reset error. ajenti only works when disabling ssl and using http.

i really like ajenti. as it the best control panel i have ever seen and ajenti v just top it off.

Any help would be appreciated.

**Comment by CreativeWolf** [comment]
Hi Shandoosheri,

Can you please help with how you got this solved?

Much appreciate it.

Thanks

**Comment by ShadyNawara** [comment]
Hey, i have installed the package from here : [https://gist.github.com/ellimilial/5ef1d1917e00970d4457!](https://gist.github.com/ellimilial/5ef1d1917e00970d4457)

Tell me if it works

**Comment by CreativeWolf** [comment]
Heya,

I was continuing my search and stumbled upon this -
https://github.com/Eugeny/ajenti/issues/618

Had to install python-dev and gevent on my Ubuntu boxlet.

That fixed the issue.

Thanks for responding and pointing out, appreciate it much!

Peace

Creativewolf
