### ISSUE TITLE
SSL Connection Error 

### ISSUE THREAD

**Issue by AnotherShen** [ajenti/ajenti#646]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)
NameError: global name 'SSLContext' is not defined
<Greenlet at 0x7f1b4d330910: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 0x7f1b4d4716d0 fileno=6 address=0.0.0.0:8000>>(<socket at 0x7f1b4d15f650 fileno=11 sock=108.61.18, ('58.165.98.186', 56519))> failed with NameError

That is the error I get cheers for any help.

**Comment by Ragnarokkr** [comment]
Same problem here. Installed on Ubuntu 14.04.1 and everything was fine. After the OS upgrade to 14.10, this error appeared.

I've checked for pyhton-greenlet and it's already at its more recent version. Still haven't found a solution. :(

**Comment by triniwiz** [comment]
check https://github.com/Eugeny/ajenti/issues/618 for ubuntu 14.10

**Comment by hertzg** [comment]
Same issue here on `Debian Jessie`

**Comment by Xefir** [comment]
Please look at this issue : https://github.com/ajenti/ajenti/issues/702

Basically, the new gevent will work with the latest version of ajenti.

Do `sudo easy_install -U gevent` and restart ajenti :-)

**Comment by hertzg** [comment]
@Xefir Thanks

```
apt-get install python-setuptools python-dev
easy_install -U gevent
service ajenti restart
```
