### ISSUE TITLE
Custom config + Maintenence Mode  = nginx error

### ISSUE THREAD

**Issue by Lusitaniae** [ajenti/ajenti#648]
Ajenti was giving this error on the Websites panel.
`nginx: [emerg] duplicate location "/" on /.../website.conf`

Because I was using this on custom configuration (from WP installation guide)
`# This order might seem weird - this is attempted to match last if rules below fail.`
  `location / {
        try_files $uri $uri/ /index.php?$args;
    }`

and had maintenance mode activated.

**Comment by seanmcn** [comment]
Noticed the same thing myself, I'll try fix it and do a pull request but my last one hasn't been accepted yet and that was pretty simple so don't hold your breath!
