### ISSUE TITLE
IPV6 Firewall Behaves Unpredictably

### ISSUE THREAD

**Issue by Rtzq0** [ajenti/ajenti#664]
When IPv6 firewall rules get applied on my system they overwrite the IPv4 firewall rules (instead of affecting the IPv6 firewall). 

Because my company has requested I drop all IPv6 traffic, I attempted to do this in the IPv6 firewall (DROP:DROP:DROP in the Filter chain, no additional rules) but suddenly lost my connection. Upon checking, I found that this settings change was visible in my iptables--list but not my ip6tables --list. This means that both firewall menus configure IPv4 traffic for me, and I have to configure IPv6 by hand.

Is it possible that iptables-restore is getting called instead of ip6tables-restore?

Currently running 1.2.22.17 on up to date Ubuntu 14.04

**Comment by janxb** [comment]
I can confirm that the problem described by jason is correct.
If I enable autostart in the _iptables_ and _ip6tables_ plugin, two files are created in _/etc/network/if-up.d/_: those files are named _iptables_ and _ip6tables_, but the content of both files are as following:

**/etc/network/if-up.d/iptables**

```
#!/bin/sh
 iptables-restore < /etc/iptables.up.rules
```

**/etc/network/if-up.d/ip6tables**

```
#!/bin/sh
 iptables-restore < /etc/ip6tables.up.rules
```

As you can see, both files are calling the restore-command for ip(v4)tables..

**Comment by janxb** [comment]
THAT was fast!
I fixed this and wanted to create a pull-request in one minute.. :+1: 

Thanks ;)
