### ISSUE TITLE
Crash report on "Packages" section

### ISSUE THREAD

**Issue by hamdarsi** [ajenti/ajenti#674]
After immediate install, I logged in, changed password and move to Packages section. A dialog appeared which was telling a problem with running yum has occurred. Unfortunately I can not provide the stack trace since after a reboot the problem was resolved.
Running ajenti ajenti-1.2.22.13-1.noarch on centos 7 clean minimal install without updating default packages.

**Comment by seanmcn** [comment]
There should be log files in /var/log/ajenti/ that could provide some insight.
