### ISSUE TITLE
Ajenti Invalid Id /Password

### ISSUE THREAD

**Issue by HosTBuvA** [ajenti/ajenti#676]
Hello there any one help me 
I just installed Ajenti on my VPS

After installation when i try to login in VPS

It Say Invalid LOgin Detail

Pleae help me

**Comment by miry** [comment]
Did you try: `The default username is root, and the password is admin.`?

**Comment by bogdaniel** [comment]
same here i tried with username: root and password: admin .. doesn't work :-)

**Comment by armnetworking** [comment]
worked for me:
root
admin
