### ISSUE TITLE
Does Ajenti has any cpanel client hosting control panel to log into?

### ISSUE THREAD

**Issue by topstarnetwork** [ajenti/ajenti#677]
Hello,
Does Ajenti has any cpanel client hosting control panel to log into?
Foer exemple once a domain is created can a client log directly to a Ajenti domain control panel the way cpanel and virtualmin does?

**Comment by cvega** [comment]
Check out: http://ajenti.org/. There is a control panel.

**Comment by topstarnetwork** [comment]
I saw the hosting addon but can a user log directly to this hosting panel or is it only for the server administrator?

**Comment by seanmcn** [comment]
I don't think there is a "hosting panel" for clients as you are expecting like cPanel has. It's really just for the server admin. Perhaps a plugin will come out soon with that ability.

**Comment by topstarnetwork** [comment]
When you say;" Perhaps a plugin will come out soon with that ability."
do you mean it is planed or is not yet under your future coming releasze?

**Comment by seanmcn** [comment]
As in perhaps someone will create one, I'm not a part of the Ajenti team.
