### ISSUE TITLE
Can't finish installing. 502 Bad Gateway from meta.ajenti.org

### ISSUE THREAD

**Issue by dpowers86** [ajenti/ajenti#689]
Followed the instructions to install on Debian. I can't seem to compete the installation. Keep getting a 502 error from meta.ajenti.org.

16.03.2015 00:15 ajenti-panel:105              INFO  Using config file /etc/ajenti/config.json
16.03.2015 00:15 ajenti-panel:130              INFO  Ajenti starting in foreground
16.03.2015 00:15 registry.py:280               DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
16.03.2015 00:15 compat.py:20                  DEBUG Popen: git describe --tags 2> /dev/null
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['lsb_release', '-sd']
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['uname', '-mrs']
16.03.2015 00:15 core.py:60                    INFO  Ajenti 1.2.22.17 running on platform: debian
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin sensors
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: main
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin main
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin sensors
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: dashboard
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin dashboard
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin sensors
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin dhcpd
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: services
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin services
16.03.2015 00:15 sm_upstart.py:49              INFO  Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'systemctl']
16.03.2015 00:15 sm_systemd.py:30              INFO  Disabling systemd service manager: global name 'SystemdService' is not defined
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin dhcpd
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'dhcpd']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [dhcpd] skipping due to BinaryDependency (dhcpd)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin netatalk
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'afpd']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [netatalk] skipping due to BinaryDependency (afpd)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin mysql
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: db_common
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin db_common
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin mysql
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'mysql']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [mysql] skipping due to BinaryDependency (mysql)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin raid
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'mdadm']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [raid] skipping due to BinaryDependency (mdadm)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin hdparm
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'hdparm']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [hdparm] skipping due to BinaryDependency (hdparm)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin hddtemp
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'hddtemp']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [hddtemp] skipping due to BinaryDependency (hddtemp)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin megaraid
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [megaraid] skipping due to FileDependency (/opt/MegaRAID/MegaCli/MegaCli)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin ipmi
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'ipmitool']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [ipmi] skipping due to BinaryDependency (ipmitool)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin mongo
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'mongod']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [mongo] skipping due to BinaryDependency (mongod)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin notepad
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: codemirror
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin codemirror
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin notepad
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin lm_sensors
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'sensors']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [lm_sensors] skipping due to BinaryDependency (sensors)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin hosts
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin webserver_common
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin memcache
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'memcached']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [memcache] skipping due to BinaryDependency (memcached)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin tasks
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: cron
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin cron
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'crontab']
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin tasks
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin iptables
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'ip6tables']
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin psql
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'psql']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [psql] skipping due to BinaryDependency (psql)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin fm
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin snmpd
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'snmpd']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [snmpd] skipping due to BinaryDependency (snmpd)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin bind9
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'named']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [bind9] skipping due to BinaryDependency (named)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin ajenti_org
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin power
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'systemctl']
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'pm-hibernate']
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin nsd
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'nsd']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [nsd] skipping due to BinaryDependency (nsd)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin configurator
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin apcups
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'apcaccess']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [apcups] skipping due to BinaryDependency (apcaccess)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin ctdb
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'ctdb']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [ctdb] skipping due to BinaryDependency (ctdb)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin fail2ban
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'fail2ban-client']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [fail2ban] skipping due to BinaryDependency (fail2ban-client)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin squid
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'squid3']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [squid] skipping due to BinaryDependency (squid3)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin resources
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin taskmgr
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin plugins
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin uname
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin munin
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'munin-cron']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [munin] skipping due to BinaryDependency (munin-cron)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin resolv
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin csf
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'csf']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [csf] skipping due to BinaryDependency (csf)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin fstab
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin scripts
16.03.2015 00:15 **init**.py:286               DEBUG Preloading plugin dependency: terminal
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin terminal
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin scripts
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin network
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin ntpd
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'ntpd']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [ntpd] skipping due to BinaryDependency (ntpd)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin supervisor
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'supervisord']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [supervisor] skipping due to BinaryDependency (supervisord)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin rethink
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'rethinkdb']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [rethink] skipping due to BinaryDependency (rethinkdb)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin exports
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'nfsstat']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [exports] skipping due to BinaryDependency (nfsstat)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin openvpn
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'openvpn']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [openvpn] skipping due to BinaryDependency (openvpn)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin packages
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin samba
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'smbd']
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'smbstatus']
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin nginx
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'nginx']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [nginx] skipping due to BinaryDependency (nginx)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin smartctl
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'smartctl']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [smartctl] skipping due to BinaryDependency (smartctl)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin elements
16.03.2015 00:15 **init**.py:340               WARN   **\* [elements] Plugin error: format error
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin users
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin apache
16.03.2015 00:15 compat.py:20                  DEBUG Popen: ['which', 'apache2']
16.03.2015 00:15 **init**.py:346               DEBUG  **\* [apache] skipping due to BinaryDependency (apache2)
16.03.2015 00:15 **init**.py:297               DEBUG Loading plugin logs
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [Inflater] <ajenti.ui.inflater.Inflater object at 0x7f6935330c90>
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [UI] <ajenti.ui.UI object at 0x7f6933431790>
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout main:file-dialog
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout main:file-dialog-save
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout main:passwd-main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout main:input-dialog
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout dashboard:dash
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout dashboard:welcome
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout dashboard:text
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout sensors:progressbar-widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout sensors:cpu-line
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout sensors:value-widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout sensors:cpu-widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout services:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout services:widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout services:bar
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout db_common:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout notepad:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout notepad:config
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout notepad:listitem
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout hosts:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout webserver_common:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout cron:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout tasks:params-deletedir
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout tasks:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout tasks:params-copydir
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout tasks:params-rsync
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout tasks:params-execute
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-state
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-custom
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-interface
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-address
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-reject-with
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-match
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-protocol
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-ports
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout iptables:option-port
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout fm:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout fm:config
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout ajenti_org:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout ajenti_org:config
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout power:widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout configurator:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout configurator:ad-sync-config
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout configurator:ldap-sync-config
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout configurator:licensing
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout taskmgr:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout plugins:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout uname:widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout resolv:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout fstab:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout fstab:widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout fstab:free-widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout fstab:iio-widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout terminal:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout terminal:config
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout scripts:widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout network:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout network:widget
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout network:bit-linux-dhcp
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout network:bit-linux-basic
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout network:bit-linux-ipv4
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout network:bit-linux-ifupdown
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout packages:installer
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout packages:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout packages:row
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout packages:headers
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout samba:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout users:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout users:user-list
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout logs:main
16.03.2015 00:15 inflater.py:38                DEBUG Precaching layout logs:config
16.03.2015 00:15 core.py:99                    INFO  Starting server on (u'0.0.0.0', 8000)
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [SessionMiddleware] <ajenti.middleware.SessionMiddleware object at 0x7f6932e3a290>
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [AuthenticationMiddleware] <ajenti.middleware.AuthenticationMiddleware object at 0x7f6932e3a710>
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [CentralDispatcher] <ajenti.routing.CentralDispatcher object at 0x7f6932e3a790>
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [IPCServer] <ajenti.ipc.IPCServer object at 0x7f6932e3a8d0>
16.03.2015 00:15 **init**.py:207               DEBUG Root context instantiated [Licensing] <ajenti.licensing.Licensing object at 0x7f6932e3a750>
16.03.2015 00:15 feedback.py:49                DEBUG Registering installation
16.03.2015 00:15 feedback.py:30                DEBUG Feedback >> register ({'edition': 'vanilla', 'version': '1.2.22.17', 'os': 'debian'})
16.03.2015 00:15 connectionpool.py:188         INFO  Starting new HTTP connection (1): meta.ajenti.org
16.03.2015 00:15 connectionpool.py:362         DEBUG "POST /api/v2/register HTTP/1.1" 502 166
16.03.2015 00:15 feedback.py:35                DEBUG Feedback << <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/feedback.py", line 52, in worker
    resp = send('register', data)
  File "/usr/lib/pymodules/python2.7/ajenti/feedback.py", line 36, in send
    return json.loads(response.content)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
<Greenlet at 0x7f693425ec30: worker> failed with ValueError

**Comment by Eugeny** [comment]
This is not a crash. Panel will continue working just fine even if the meta server isn't available.
