### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by tobolskiy** [ajenti/ajenti#709]
![2015-04-19 17-52-09 server](https://cloud.githubusercontent.com/assets/12018640/7219500/40babc90-e6bd-11e4-84a7-849b82c9212a.png)

**Comment by Xefir** [comment]
Ajenti don't touch to kernel what so ever.

I think your problem isn't related to ajenti project.

**Comment by mattia1107** [comment]
i have the same problem after updating ajenti. 
My problem is related to ajenti-panel and kernel.
