### ISSUE TITLE
Will Not Start After Manual Install

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#720]
root@AlphaServ:/etc/ajenti# service ajenti restart
Stopping Ajenti:
[FAIL] not running ... failed!
Starting Ajenti:
17.05.2015 00:46 INFO  Using config file /etc/ajenti/config.json
[ ok ] started.
root@AlphaServ:/etc/ajenti# service ajenti status
[ ok ] Ajenti is not running.
root@AlphaServ:/etc/ajenti# service ajenti start 
Starting Ajenti:
17.05.2015 00:47 INFO  Using config file /etc/ajenti/config.json
[ ok ] started.
root@AlphaServ:/etc/ajenti# service ajenti status
[ ok ] Ajenti is not running.

root@AlphaServ:~# cat /etc/ajenti/config.json
{
    "users": {
        "AlphaTech": {
            "configs": {
                "ajenti.plugins.dashboard.dash.Dash": "{\"widgets\": [{\"index\": 0, \"config\": null, \"container\": \"1\", \"class\": \"ajenti.plugins.sensors.memory.MemoryWidget\"}, {\"index\": 1, \"config\": null, \"container\": \"1\", \"class\": \"ajenti.plugins.sensors.memory.SwapWidget\"}, {\"index\": 2, \"config\": null, \"container\": \"1\", \"class\": \"ajenti.plugins.dashboard.welcome.WelcomeWidget\"}, {\"index\": 0, \"config\": null, \"container\": \"0\", \"class\": \"ajenti.plugins.sensors.uptime.UptimeWidget\"}, {\"index\": 1, \"config\": null, \"container\": \"0\", \"class\": \"ajenti.plugins.power.power.PowerWidget\"}, {\"index\": 2, \"config\": null, \"container\": \"0\", \"class\": \"ajenti.plugins.sensors.cpu.CPUWidget\"}]}"
            }, 
            "password": "InsertPasswordHere", 
            "permissions": []
        }
    }, 
    "bind": {
        "host": "0.0.0.0", 
        "port": 82
    }, 
    "authentication": false, 
    "ssl": {
        "enable": false,
        "certificate_path": "/etc/ajenti/ajenti.pem"
    }, 
    "enable_feedback": true, 
    "installation_id": null
}

**Comment by Mel0ne** [comment]
Подтверждаю, та же самая проблема

**Comment by Mel0ne** [comment]
Судя по логу это вся та же песня с питоном: 

/usr/lib/pymodules/python2.7/ajenti/feedback.py:8: UserWarning: libevent version mismatch: system version is '2.0.21-stable' but this gevent is compiled against '2.0.19-stable'
  import gevent
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 124, in <module>
    from ajenti import core
  File "/usr/lib/pymodules/python2.7/ajenti/core.py", line 17, in <module>
    import ajenti.feedback
  File "/usr/lib/pymodules/python2.7/ajenti/feedback.py", line 8, in <module>
    import gevent
  File "/usr/lib/pymodules/python2.7/gevent/__init__.py", line 49, in <module>
    from gevent.greenlet import Greenlet, joinall, killall
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 6, in <module>
    from gevent.hub import greenlet, getcurrent, get_hub, GreenletExit, Waiter
  File "/usr/lib/pymodules/python2.7/gevent/hub.py", line 30, in <module>
    greenlet = __import__('greenlet').greenlet
ImportError: /usr/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

**Comment by Mel0ne** [comment]
which distr you use? if Debian update to last version (8) apt-get dist-upgrade
