### ISSUE TITLE
Ajenti very slow loading after gevent update. (Debian 8)

### ISSUE THREAD

**Issue by wopss** [ajenti/ajenti#725]
Hello,

I updated gevent for Debian 8 (SSL issue) and now Ajenti is slow, very slow.
In FireFox console, it say 
"00:47:51.296 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create1 resources.js:8:3580"

**Comment by oleksii-zavrazhnyi** [comment]
Same shit, extremely slow...

**Comment by bassybeats** [comment]
If I turn off SSL it is fast and responsive. If I turn SSL back on in config.json everything goes slow again. Running Debain 8 as well. its just a in house dev server so might be able to live without SSL.

**Comment by alessiodionisi** [comment]
Same here

**Comment by oleksii-zavrazhnyi** [comment]
After disabling SSL in config it works fine, @Eugeny please prioritise this issue.
Thanks.

**Comment by Eugeny** [comment]
Which gevent version do you use now? 1.0.2? The problem shows up in any browser? Does it happen when running SSL-enabled Ajenti locally, or via network only?

**Comment by alessiodionisi** [comment]
Gevent 1.0.2 for me.
I have two servers with Ubuntu 15.04, on first server ssl is slow, on second ssl not work.

**Comment by wopss** [comment]
@Eugeny, yes, version **1.0.2** for gevent.
On all browsers: **Mozilla**, **Chrome**, **Internet Explorer**.
It happen when I run **SSL-enabled Ajenti via network** and *_locally_.

**Comment by Eugeny** [comment]
I can't reproduce this with just gevent==1.0.2
Could you please check the openSSL version on the system and the negotiated TLS/SSL/cipher? 
Are you using a self-generated certificate or a "real" one?

**Comment by wopss** [comment]
I'm using a self-generated. (I generated one with Ajenti without SSL enabled)
OpenSSL: "OpenSSL 1.0.1k 8 Jan 2015".
Please tell me how to do that "the negotiated TLS/SSL/cipher".

**Comment by Eugeny** [comment]
Example for Chrome:
![selection_116](https://cloud.githubusercontent.com/assets/161476/7916933/8e9cf8ee-088f-11e5-9c19-bcb996ea259f.png)

**Comment by wopss** [comment]
@Eugeny on Chrome I can't get this because the page took too long to reload it and Chrome give me error.
On FireFox
![ajenti 1](https://cloud.githubusercontent.com/assets/3403191/7917343/529448f4-0892-11e5-95a6-7bbd00162be6.png)
![ajenti 2](https://cloud.githubusercontent.com/assets/3403191/7917344/5297ded8-0892-11e5-8b36-b50f049c3add.png)

**Comment by bassybeats** [comment]
OpenSSL 1.0.2a 19 Mar 2015
built on: reproducible build, date unspecified
platform: debian-amd64

Gevent 1.0.2
using  /usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-x86_64.egg

**Comment by lukasmrtvy** [comment]
Same problem here
openssl 1.0.1f-1ubuntu11.4
Gevent 1.0.2
All browsers
Over network and locally
ubuntu 15.04 amd64

**Comment by murphinator** [comment]
Same here 

OpenSSL 1.0.1f 6 Jan 2014
Gevent 1.0.2
FF and Chrome
ubuntu 15.04 amd64

**Comment by Xefir** [comment]
Re-run easy_install -U gevent.

I've got the 1.1b3 right now on debian 8 and it fixes a lot of problem (like this one)
