### ISSUE TITLE
ajenti gui failure

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#729]
I have installed ajenti on a debian jessie armhf system. It installed fine  no errors but when I attempt to goto the se service at port 8000 it fails to load.

root@kb3vga-repeater:~# service ajenti status -l
● ajenti.service - LSB: Ajenti
   Loaded: loaded (/etc/init.d/ajenti)
   Active: active (running) since Fri 1999-12-31 19:28:09 CST; 15 years 5 months ago
   CGroup: /system.slice/ajenti.service
           └─464 /usr/bin/python /usr/bin/ajenti-panel -d

Dec 31 19:28:06 kb3vga-repeater ajenti[447]: Starting Ajenti:
Dec 31 19:28:09 kb3vga-repeater ajenti[447]: 1999-12-31 19:28:09,858 INFO     ajenti-panel.<module>(): Using config file /etc/ajenti/config.json
Dec 31 19:28:09 kb3vga-repeater ajenti[447]: started.
Dec 31 19:28:09 kb3vga-repeater systemd[1]: Started LSB: Ajenti.

**Comment by ghost** [comment]
Just did a install on amd64 debian jessie 8.0 and same issue it wont load up the gui at https://ip.og.the.maching:8000

says its running but no access

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 382, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/dist-packages/gevent/ssl.py", line 84, in __init__
    ctx = SSLContext(ssl_version)

NameError: global name 'SSLContext' is not defined
<Greenlet at 0xb4c81120L: <bound method SocketIOServer.wrap_socket_and_handle of <SocketIOServer at 
0xb4c5f4f0L fileno=6 address=0.0.0.0:8000>>(<socket at 0xb6ce0970L fileno=10 sock=10.50.1.208:, 
('10.50.1.209', 59442))> failed with NameError

this is what I get with ajenti-panel -v

**Comment by alessiodionisi** [comment]
You have openssl lib?

**Comment by ghost** [comment]
yes . its installed
all the deps are installed...

I added the debian repo for ajenti. then did apt-get update . apt-get install ajenti. it installs all the deps

**Comment by janxb** [comment]
Maybe your problem is the same as some others which were posted here before.
If this could be the case, maybe you try the solution mentioned here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766867#15

Just patch the file mentioned in the last response from Frank Eular (no. 15) and tell us if this solved your problem. For me, it solved the SSL-problem after an installation on debian jessie.
