### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by pajooh** [ajenti/ajenti#731]
hello Ajenti maintainers
I'm trying to select an admin panel for my servers, and i faced Ajenti.
it looks very promising, but checking GitHub generated [graph](https://github.com/ajenti/ajenti/graphs/contributors), it seems that contributions are reduced this year.
can someone tell how is it going here in terms of project's future, any help would be highly appreciated.

**Comment by mateuszkwiatkowski** [comment]
Leaving this question without answer for over a month is quite self-explanatory.
I wanted to put some effort into Ajenti, especially to improve FreeBSD support. I'd like to avoid investing my time in dead project.

**Comment by lcdss** [comment]
Ajenti seems a good CP but could be better with more contributions from community. Seems that most users just use it, but never contributes with this project, what is a shame. Few are those who contribute and helps this great project grow.
