### ISSUE TITLE
Install Script Moved

### ISSUE THREAD

**Issue by StudioLE** [ajenti/ajenti#733]
The 'Installing on Ubuntu' page of the knowledge base: http://support.ajenti.org/topic/349868-installing-on-ubuntu/

Specifies the install script as https://raw.github.com/ajenti/ajenti/master/scripts/install-ubuntu.sh which no longer exists.

It should be either:
- https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh
- https://raw.githubusercontent.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh

**Comment by Eugeny** [comment]
Fixed
