### ISSUE TITLE
Ajenti V - Ideas

### ISSUE THREAD

**Issue by matias-casal** [ajenti/ajenti#734]
I really love your software, with a little use i can tell you some points to get better:
- [ ] The HTML5 notification almost show with a lot of delay, so, in important things (Like: cant create a bd or username because is too long or other error) show a little alert in the html of the page.
- [ ] I have some problems with the nginx configuration, for example i download a wordpress config for nginx, but i cant replace the default configuration.. if this is for some secure reason, you have to give the option to include my own configuration overriding the default (now we have: custom settings and custom main settings, but i always have problems, for example: "location can no defined here", etc).

Like i say at the start, i really love this software, keep working, is a really good project

**Comment by suciptoid** [comment]
Also need automatic script installer like Wordpress auto installer. :+1:
