### ISSUE TITLE
Error when installing - SSL ajenti-ssl-gen

### ISSUE THREAD

**Issue by uzegonemad** [ajenti/ajenti#735]
I'm encountering an error when installing ajenti. I'm running Debian 7. I used the [quick install](http://support.ajenti.org/topic/349864-installing-on-debian/) and everything appeared to work until the SSL generation. See the attached error for details. This happens every time I run the installer.

```
Setting up ajenti (1.2.22.21) ...

:: Generating key

Generating RSA private key, 2048 bit long modulus
......+++
.................................................................................+++
e is 65537 (0x10001)

:: Generating certificate request

/bin/sh: 9: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/usr/bin/ajenti-ssl-gen", line 43, in <module>
    os.chmod(certificate_path, 0400)
OSError: [Errno 2] No such file or directory: '/etc/ajenti/ajenti.pem'
------------------------------------------------
Now start Ajenti with 'service ajenti restart'
```

**Comment by bbbenji** [comment]
Disable SSL in `/etc/ajenti/config.json` if it is not already and restart Ajenti. You should be able to access the panel despite the error. Now you can try generating a new certificate from the configuration page.

**Comment by prhomhyse** [comment]
Try this method( https://gist.github.com/prhomhyse/515dd85cd017805d8634 ), it will have the right key installed and you are set to use Ajenti. it worked for me anytime i want to set Ajenti up for anyone. :) :100:
