### ISSUE TITLE
Ajenti do not start - ImportError: No module named os

### ISSUE THREAD

**Issue by mateuszbrylski** [ajenti/ajenti#743]
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.api.http.HttpPlugin](interface)
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.api.http.SocketEndpoint](interface)
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator](service)
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.auth.AuthenticationMiddleware](service)
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.auth.AuthenticationProvider](interface)
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.auth.OSAuthenticationProvider](implementation of [aj.auth.AuthenticationProvider])
03.07.2015 13:52  [...     2593]  DEBUG    Registering [aj.auth.AuthenticationService](service)
Traceback (most recent call last):
  File "/usr/local/bin/ajenti-panel", line 118, in <module>
    plugin_providers=plugin_providers,
  File "/usr/local/lib/python2.7/dist-packages/aj/entry.py", line 35, in start
    import aj.core
  File "/usr/local/lib/python2.7/dist-packages/aj/core.py", line 17, in <module>
    from aj.gate.middleware import GateMiddleware
  File "/usr/local/lib/python2.7/dist-packages/aj/gate/middleware.py", line 16, in <module>
    from aj.gate.gate import WorkerGate
  File "/usr/local/lib/python2.7/dist-packages/aj/gate/gate.py", line 2, in <module>
    import gipc
  File "/usr/local/lib/python2.7/dist-packages/gipc/**init**.py", line 8, in <module>
    from gipc import pipe, start_process, GIPCError, GIPCClosed, GIPCLocked
  File "/usr/local/lib/python2.7/dist-packages/gipc/gipc.py", line 34, in <module>
    import gevent.os
ImportError: No module named os

**Comment by Eugeny** [comment]
Please include output of `pip freeze`

**Comment by mateuszbrylski** [comment]
aj==2.0.57
ajenti==1.2.22.21
ajenti-panel==2.0.57
ajenti.plugin.ace==0.19
ajenti.plugin.core==0.43
ajenti.plugin.dashboard==0.17
ajenti.plugin.filemanager==0.14
ajenti.plugin.filesystem==0.16
ajenti.plugin.notepad==0.16
ajenti.plugin.packages==0.18
ajenti.plugin.passwd==0.12
ajenti.plugin.plugins==0.32
ajenti.plugin.services==0.17
ajenti.plugin.settings==0.15
ajenti.plugin.terminal==0.22
chardet==2.0.1
cookies==2.2.1
fpconst==0.7.2
gevent==0.13.6
gevent-socketio==0.3.6
gevent-websocket==0.3.6
gipc==0.5.0
greenlet==0.4.0
jadi==1.0.2
lockfile==0.8
lxml==2.3.2
Mako==0.7.0
MarkupSafe==0.15
medusa==0.5.4
meld3==0.6.5
oauthlib==0.1.2
passlib==1.5.3
pexpect==3.3
PIL==1.1.7
Pillow==2.9.0
psutil==3.0.1
pycrypto==2.6
pyOpenSSL==0.13.1
pyte==0.4.9
python-apt==0.8.8.2
python-augeas==0.4.0
python-catcher==0.1.7
python-daemon==1.5.5
python-debian==0.1.21
python-debianbts==1.11
python-exconsole==0.1.5
python-ldap==2.4.10
PyYAML==3.11
reconfigure==0.1.72
reportbug==6.4.4
requests==2.7.0
setproctitle==1.1.8
six==1.1.0
SOAPpy==0.12.0
supervisor==3.0a8
termcolor==1.1.0
upstart-new==0.3.4

**Comment by Eugeny** [comment]
Please try upgrading your Gevent installation with `sudo pip install "gevent>=1.0"`

**Comment by mateuszbrylski** [comment]
Thanks! :+1:
