### ISSUE TITLE
CSF Firewall

### ISSUE THREAD

**Issue by Richardds** [ajenti/ajenti#770]
Hello, I changed listen port from 22 to let's say 12345 for SSH but i didn't allow new port in CSF Firewall. I'm still allow connect to SSH even if port 12345 is not listed in CSF Firewall.

I removed my local IP from allowed IPs as well
![](http://i.imgur.com/rJrzP48.png)

I forgot something?

Thanks, Richard

**Comment by allanice001** [comment]
you may need to restart ssh to activate the change.
on the server - run the following::
netstat -ntap | grep ssh and the output should be the new port if the
change was applied, else try restarting ssh

On Wed, Aug 19, 2015 at 9:41 PM, Richard Boldiš notifications@github.com
wrote:

> Hello, I changed listen port from 22 to let's say 12345 for SSH but i
> didn't allow new port in CSF Firewall. I'm still allow connect to SSH even
> if port 12345 is not listed in CSF Firewall.
> 
> I removed my local IP from allowed IPs as well
> 
> https://camo.githubusercontent.com/5d092b6cdc878ad441a28f78eb62c196aedce040/687474703a2f2f692e696d6775722e636f6d2f724a727a5034382e706e67
> 
> I forgot something?
> 
> Thanks, Richard
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ajenti/ajenti/issues/770.

## 

We live in an age when pizza gets to your home before the police.

##   - Jeff Marder

Allan Swanepoel
allanice001@gmail.com
allanice.001@unix.net
dragonmaster@linaccess.com
+27 71 850 5554
Linux User #452990

## Linux Machine #360914

IMPORTANT: This email is intended for the use of  the  individual
addressee(s)  named  above  and  may  contain information that is
confidential,  privileged  or  unsuitable  for  overly  sensitive persons
with  low  self-esteem, no sense of humour or irrational religious beliefs.
If you are not  the  intended  recipient,  any dissemination,
distribution  or copying  of  this  email is not authorised (either
explicitly or implicitly) and  constitutes  an irritating  social  faux
pas. Unless the word absquatulation has been used in its correct context
somewhere  other  than  in  this warning, it does not have any legal or
grammatical use and may be ignored. No animals were  harmed  in  the
transmission  of  this email,  although  the  yorkshire  terrier  next door
is living on borrowed time, let me tell you. Those of you with an
overwhelming fear  of  the unknown will be gratified to learn that there is
no hidden message revealed by reading  this  warning  backwards,  so just
ignore that Alert Notice from Microsoft: However, by pouring a complete
circle of salt around yourself and your  computer  you can  ensure  that
no harm befalls you and your pets.

**Comment by Richardds** [comment]
I'm able connect to new port but CSF Firewall didn't block new port 2229.
http://i.imgur.com/0264XmE.png
