### ISSUE TITLE
Multi Domain Error

### ISSUE THREAD

**Issue by luckyrajiv** [ajenti/ajenti#783]
Hi, 

i have added two domains for Ex: abc.com and xyz.com
and created subdomains for each as mail.abc.com and mail.xyz.com

My Issue: 
If i type wrong address for abc.com like 1.abc.com which doesnt exists, it goes to abc.com, this is okay.

But if i type 1.xyz.com which also doesnt exists, it also goes to abc.com, instead of going to xyz.com 

Can anyone help ? Is it a configuration issue ?

**Comment by Ardakilic** [comment]
This is ajenti-v related or normal ajenti? 

As far as I understood it falls back to abc.com, because it's the default domain (or the first one in alphabetical order), think and handle subdomains like separate domains, just with similar names. I don't think nginx support domain based default virtualhost setup.

**Comment by luckyrajiv** [comment]
i installed ajenti and ajenti -v over ubuntu 14.

Yes, abc.com is the first domain i added but not by the alphabetical order.  also, yes, i have added each subdomain as separate entity in ajenti v control panel as it is said so under websites section. 

my issue is that even if any link which is like a 404 error instead of going to its main domain it goes to other domain. for eg: if i type wrong address like xyz.com/blog/rihdhk , by default it should go to xyz.com or show 404 error page not found etc on the same url. But what is happening is, it goes to abc.com ( the domain which was added first, i mean where the cp of ajenti is installed ).

if the url of xyz.com is correct , then it works, only if the url doesnt exist for xyz.com or its subdomain doesnt exist, it falls back to abc.com

how can i fix this ?

**Comment by brianjking** [comment]
Also having this issue on a DigitalOcean droplet running Ubuntu 14.04 x64 & Ajenti.

**Comment by allanice001** [comment]
you need to add a *.xyz.com entry for the ajenti cp, as well as a dns entry
for *.xyz.com

On Fri, Sep 4, 2015 at 10:24 PM, Brian J King notifications@github.com
wrote:

> Also having this issue on a DigitalOcean droplet running Ubuntu 14.04 x64
> & Ajenti.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ajenti/ajenti/issues/783#issuecomment-137844488.

## 

We live in an age when pizza gets to your home before the police.

##   - Jeff Marder

Allan Swanepoel
allanice001@gmail.com
allanice.001@unix.net
dragonmaster@linaccess.com
+27 71 850 5554
Linux User #452990

## Linux Machine #360914

IMPORTANT: This email is intended for the use of  the  individual
addressee(s)  named  above  and  may  contain information that is
confidential,  privileged  or  unsuitable  for  overly  sensitive persons
with  low  self-esteem, no sense of humour or irrational religious beliefs.
If you are not  the  intended  recipient,  any dissemination,
distribution  or copying  of  this  email is not authorised (either
explicitly or implicitly) and  constitutes  an irritating  social  faux
pas. Unless the word absquatulation has been used in its correct context
somewhere  other  than  in  this warning, it does not have any legal or
grammatical use and may be ignored. No animals were  harmed  in  the
transmission  of  this email,  although  the  yorkshire  terrier  next door
is living on borrowed time, let me tell you. Those of you with an
overwhelming fear  of  the unknown will be gratified to learn that there is
no hidden message revealed by reading  this  warning  backwards,  so just
ignore that Alert Notice from Microsoft: However, by pouring a complete
circle of salt around yourself and your  computer  you can  ensure  that
no harm befalls you and your pets.
