### ISSUE TITLE
Has no images when change host IP

### ISSUE THREAD

**Issue by Ordsall** [ajenti/ajenti#790]
When I install Ajenti, I used host 192.168.0.234, and all was good. When I changed host IP to 192.168.0.3, I has no images in Ajenti interface. Interface working, but images wasn't loading.

**Comment by Jonathan-Rosewood** [comment]
Have some problem when i install ajenti after installing and basic configuring nginx, php5 etc..

**In my /etc/ajenti/config.json:**
`
"bing": {
    "host": "0.0.0.0",
    "port": 8000
},
`
