### ISSUE TITLE
MongoDb issues

### ISSUE THREAD

**Issue by tsgiannis** [ajenti/ajenti#798]
Hello i am trying to admin my mongodb instance but it seems i am stuck
When i choose the MongoDb plugin i get 2 notifications:
![mongo01](https://cloud.githubusercontent.com/assets/14885251/10301509/cdf60d70-6c0b-11e5-976c-006a34d72739.jpg)
and then i get this popup
![mongo002](https://cloud.githubusercontent.com/assets/14885251/10301517/e7174de6-6c0b-11e5-994f-ceb23303e8c6.jpg)
I know i am missing something but i don't know what exactly these errors mean

**Comment by brunocascio** [comment]
same issue

**Comment by brunocascio** [comment]
I installed `pyMongo==2.8` and it's worked.

`sudo pip install pymongo==2.8`

:)

Also i added this lines in `/etc/mongodb.conf`:

``` yaml
...
setParameter:
  enableLocalhostAuthBypass: 0
...
```

Source: https://github.com/mongodb-labs/mongo-connector/issues/240
