### ISSUE TITLE
Enabling clamav on mail server

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#799]
I am having problems in enabling clamav on email server, I have followed the guide from here http://michaelfranzl.com/2013/09/07/setting-up-exim4-mail-transfer-agent-with-spam-filtering-greylisting-and-anti-virus/ but and tried to write those configuration at "Custom configuration" at mail tab, but it did not work.

Is it all right if I write them at /etc/exim4/exim4.conf.template and run "update-exim4.conf" on server, will it destroy the ajenti mail configuration?

**Comment by Xefir** [comment]
Ajenti load his custom configuration, I don't think you'll succeed by doing through update-exim4.conf

I have done in an older issue a screen of my config on ajenti to work with spamassassin, I can't figure witch number is.

So here is again : 

![image](https://cloud.githubusercontent.com/assets/961976/10395698/aa6b7116-6e9e-11e5-824d-b38c2ff13dd0.png)

Sorry for the langage on the screen, i'm french ^^" (but the input should be at the same place on Mail > Advenced)
With this, spamassassin and clamav should be working (it does on my server).

**Comment by ghost** [comment]
Hello,

Thanks a lot for your help. That configuration is now accepted. But I have got another problem. I do not know why courier is running only as process with TCP6 and port 143, it needs to be running at 993 as well. And should it be running at TCP4 as well for both ports?

![untitled](https://cloud.githubusercontent.com/assets/14217191/10397232/d52d0420-6ea6-11e5-8aec-3bba1f754bc5.png)

Sending emails is working properly but receiving them is taking so much time, they are showed at mainlog as received but at email are not showed until a certain time.

p.s. Even roundcube does not work, it shows "Login failed". And outlook works only under TLS.

Best regards,
Edoniti.

**Comment by Xefir** [comment]
Your problem isn't one, but it's related to this PR : https://github.com/Eugeny/ajenti-v/pull/193

Short things short, SSL has been disabled for security issue, so only TLS is accepted.

For Roundcube to work, the only thing you have to change on the config is this : 

```
$config['default_host'] = 'tls://your-main-domain';
```

Replace your-main-domain by the domain you have register the mail's certificate.

However, for your TCP4 problem, i have no idea, sorry =/

**Comment by ghost** [comment]
Hello,

Thanks you a lot, it is working now. Just for information now on security level "None" is not allowed either? Just "TLS"? Because earlier it worked with "None" as well. Now with "none" outlook fails to authenticate.

According to this article https://www.fastmail.com/help/technical/ssltlsstarttls.html "SSL/TLS encrypted IMAP uses port 993", will TLS work properly with 143 port with Ajenti? While for outgoing TLS should I use 25 or 465?

p.s. Up to now it seems everything good without TCP4 courier, hope it will not cause any problems in the future.

Best regards,
Edoniti.
