### ISSUE TITLE
Showing blank page after login

### ISSUE THREAD

**Issue by kdpuvvadi** [ajenti/ajenti#800]
After installing ajenti on Freshly installed Ubuntu 14.04 hosted on azure, it is basic LAMP setup and it is showing blank page with any UI, 
<img width="1114" alt="screen shot 2015-10-09 at 9 35 33 pm" src="https://cloud.githubusercontent.com/assets/7326255/10399062/1b7e1758-6ece-11e5-9f0d-3070dda424e9.png">

**Comment by Xefir** [comment]
Bug related to gevent.
Install the 1.1b3 or 1.1b4.
The latest 1.1b5 cause this blank screen.

For install gevent 1.1b4 : 

```
sudo easy_install -U gevent==1.1b4
```

**Comment by kdpuvvadi** [comment]
Thanks it worked
