### ISSUE TITLE
start ajenti from console error

### ISSUE THREAD

**Issue by minotaurdsp** [ajenti/ajenti#801]
root@ats0:/home/kaspars# ajenti-panel -v
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.api.http.HttpMiddleware](interface)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.api.http.HttpPlugin](interface)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.api.http.SocketEndpoint](interface)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.security.verifier.ClientCertificateVerificator](service)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.auth.AuthenticationMiddleware](service)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.auth.AuthenticationProvider](interface)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.auth.OSAuthenticationProvider](implementation of [aj.auth.AuthenticationProvider])
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.auth.AuthenticationService](service)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.auth.PermissionProvider](interface)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.routing.CentralDispatcher](service)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.gate.middleware.SocketIORouteHandler](service)
21.10.2015 17:00  [...    12074]  DEBUG    Registering [aj.gate.middleware.GateMiddleware](service)
21.10.2015 17:00  [...    12074]        compat.py:19    DEBUG    Popen: git describe --tags 2> /dev/null
21.10.2015 17:00  [...    12074]        compat.py:19    DEBUG    Popen: ['lsb_release', '-sd']
21.10.2015 17:00  [master 12074]          core.py:70    INFO   Loading config from /etc/ajenti/config.yml
21.10.2015 17:00  [master 12074]          core.py:75    WARN   Debug mode
21.10.2015 17:00  [master 12074]          core.py:88    INFO   Ajenti Core 2.0.71
21.10.2015 17:00  [master 12074]          core.py:89    INFO   Detected platform: debian / Ubuntu 14.04.3 LTS
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/local/bin
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/plat-x86_64-linux-gnu
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/lib-tk
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/lib-dynload
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/local/lib/python2.7/dist-packages
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/dist-packages
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/python2.7/dist-packages/PILcompat
21.10.2015 17:00  [master 12074]       plugins.py:63    DEBUG  Looking for plugins in /usr/lib/pymodules/python2.7
21.10.2015 17:00  [master 12074]       plugins.py:268   INFO   Discovered 12 plugins
21.10.2015 17:00  [master 12074]       plugins.py:316   DEBUG  Resolved load order for 12 plugins: ['core', 'passwd', 'plugins', 'dashboard', 'services', 'ace', 'terminal', 'packages', 'filesystem', 'settings', 'notepad', 'filemanager']
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "core"
21.10.2015 17:00  [master 12074]          jadi.py:129   DEBUG  Registering [aj.plugins.core.api.sidebar.SidebarItemProvider](interface)
21.10.2015 17:00  [master 12074]          jadi.py:63    DEBUG  Registering [aj.plugins.core.api.sidebar.Sidebar](service)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.main.Permissions](implementation of [aj.auth.PermissionProvider])
21.10.2015 17:00  [master 12074]          jadi.py:63    DEBUG  Registering [aj.plugins.core.api.navbox.Navbox](service)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.views.api.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.views.config.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.views.main.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.views.resource_server.ResourcesHandler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:63    DEBUG  Registering [aj.plugins.core.api.push.Push](service)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.views.push.PushSocket](implementation of [aj.api.http.SocketEndpoint])
21.10.2015 17:00  [master 12074]          jadi.py:63    DEBUG  Registering [aj.plugins.core.api.tasks.TasksService](service)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.core.views.tasks.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "passwd"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.passwd.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "plugins"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.plugins.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.plugins.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "dashboard"
21.10.2015 17:00  [master 12074]          jadi.py:129   DEBUG  Registering [aj.plugins.dashboard.api.Widget](interface)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.widgets.cpu.CPUWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.widgets.hostname.HostnameWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.widgets.loadavg.LoadAverageWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.widgets.memory.MemoryWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.dashboard.widgets.uptime.UptimeWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "services"
21.10.2015 17:00  [master 12074]          jadi.py:129   DEBUG  Registering [aj.plugins.services.api.ServiceManager](interface)
21.10.2015 17:00  [master 12074]        compat.py:19    DEBUG  Popen: ['which', 'systemctl']
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.services.managers.upstart_manager.UpstartServiceManager](implementation of [aj.plugins.services.api.ServiceManager])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.services.managers.sysv_manager.SysVServiceManager](implementation of [aj.plugins.services.api.ServiceManager])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.services.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.services.main.Permissions](implementation of [aj.auth.PermissionProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.services.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "ace"
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "terminal"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.terminal.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.terminal.main.Permissions](implementation of [aj.auth.PermissionProvider])
21.10.2015 17:00  [master 12074]          jadi.py:63    DEBUG  Registering [aj.plugins.terminal.manager.TerminalManager](service)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.terminal.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.terminal.views.Socket](implementation of [aj.api.http.SocketEndpoint])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "packages"
21.10.2015 17:00  [master 12074]          jadi.py:129   DEBUG  Registering [aj.plugins.packages.api.PackageManager](interface)
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.packages.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.packages.main.Permissions](implementation of [aj.auth.PermissionProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.packages.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.packages.managers.apt_manager.APTPackageManager](implementation of [aj.plugins.packages.api.PackageManager])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.packages.managers.yum_manager.YUMPackageManager](implementation of [aj.plugins.packages.api.PackageManager])
21.10.2015 17:00  [master 12074]      **init**.py:59    DEBUG  Registered VCS backend: git
21.10.2015 17:00  [master 12074]      **init**.py:59    DEBUG  Registered VCS backend: hg
21.10.2015 17:00  [master 12074]      **init**.py:59    DEBUG  Registered VCS backend: svn
21.10.2015 17:00  [master 12074]      **init**.py:59    DEBUG  Registered VCS backend: bzr
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.packages.managers.pip_manager.PIPPackageManager](implementation of [aj.plugins.packages.api.PackageManager])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "filesystem"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.filesystem.main.Permissions](implementation of [aj.auth.PermissionProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.filesystem.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "settings"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.settings.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.settings.views.Handler](implementation of [aj.api.http.HttpPlugin])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "notepad"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.notepad.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]       plugins.py:339   DEBUG  Importing plugin "filemanager"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.filemanager.main.ItemProvider](implementation of [aj.plugins.core.api.sidebar.SidebarItemProvider])
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "core"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "passwd"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "plugins"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "dashboard"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "services"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.services.widget.ServiceWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "ace"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "terminal"
21.10.2015 17:00  [master 12074]          jadi.py:157   DEBUG  Registering [aj.plugins.terminal.widget.ScriptWidget](implementation of [aj.plugins.dashboard.api.Widget])
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "packages"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "filesystem"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "settings"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "notepad"
21.10.2015 17:00  [master 12074]       plugins.py:349   DEBUG  Initializing plugin "filemanager"
21.10.2015 17:00  [master 12074]       plugins.py:336   INFO   Loaded 12 plugins
21.10.2015 17:00  [master 12074]          core.py:119   INFO   Binding to [0.0.0.0]:8000
21.10.2015 17:00  [master 12074]          gipc.py:271   DEBUG  Invoke target `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7f60b2680c10>>` in child process.
21.10.2015 17:00  [master 12074]          gipc.py:449   DEBUG  SIGCHLD watcher for 12085 started.
21.10.2015 17:00  [master 12074]          gipc.py:289   DEBUG  Invalidate <_GIPCWriter_162735 fd: 9> in parent.
21.10.2015 17:00  [master 12074]          gipc.py:583   DEBUG  Invalidating <_GIPCWriter_162735 fd: 9> ...
21.10.2015 17:00  [master 12074]          gipc.py:289   DEBUG  Invalidate <_GIPCReader_203e76 fd: 10> in parent.
21.10.2015 17:00  [master 12074]          gipc.py:583   DEBUG  Invalidating <_GIPCReader_203e76 fd: 10> ...
21.10.2015 17:00  [master 12074]          gate.py:46    DEBUG  Started child process 12085
21.10.2015 17:00  [...    12085]          gipc.py:308   DEBUG    _child start. target: `<bound method WorkerGate._target of <aj.gate.gate.WorkerGate object at 0x7f60b2680c10>>`
21.10.2015 17:00  [...    12085]          gipc.py:320   DEBUG    Delete current hub's threadpool.
21.10.2015 17:00  [...    12085]          gipc.py:329   DEBUG    Destroy hub and default loop.
21.10.2015 17:00  [...    12085]          gipc.py:334   DEBUG    Created new hub and default event loop.
21.10.2015 17:00  [...    12085]          gipc.py:341   DEBUG    Invalidate <_GIPCReader_114946 fd: 6> in child.
21.10.2015 17:00  [...    12085]          gipc.py:594   DEBUG    Legitimate <_GIPCReader_114946 fd: 6> for current process.
21.10.2015 17:00  [...    12085]          gipc.py:583   DEBUG    Invalidating <_GIPCReader_114946 fd: 6> ...
21.10.2015 17:00  [...    12085]          gipc.py:341   DEBUG    Invalidate <_GIPCWriter_3f62ea fd: 11> in child.
21.10.2015 17:00  [...    12085]          gipc.py:594   DEBUG    Legitimate <_GIPCWriter_3f62ea fd: 11> for current process.
21.10.2015 17:00  [...    12085]          gipc.py:583   DEBUG    Invalidating <_GIPCWriter_3f62ea fd: 11> ...
21.10.2015 17:00  [master 12074]          core.py:182   INFO   SSL enabled
21.10.2015 17:00  [...    12085]          gipc.py:594   DEBUG    Legitimate <_GIPCWriter_162735 fd: 9> for current process.
21.10.2015 17:00  [...    12085]          gipc.py:359   DEBUG    Handle `<_GIPCWriter_162735 fd: 9>` is now valid in child.
21.10.2015 17:00  [...    12085]          gipc.py:594   DEBUG    Legitimate <_GIPCReader_203e76 fd: 10> for current process.
21.10.2015 17:00  [...    12085]          gipc.py:359   DEBUG    Handle `<_GIPCReader_203e76 fd: 10>` is now valid in child.
21.10.2015 17:00  [rstrct 12085]          gate.py:105   INFO     New worker "restricted session" PID 12085, EUID 0, EGID 0
21.10.2015 17:00  [rstrct 12085]          gate.py:105   INFO     Worker 12085 is demoting to UID 65534 / GID 65534...
21.10.2015 17:00  [rstrct 12085]          gate.py:105   INFO     ...done, new EUID 65534 EGID 65534
21.10.2015 17:00  [rstrct 12085]          gate.py:105   DEBUG                        ... GET /
error: cannot open Packages database in /root/.rpmdb
21.10.2015 17:00  [rstrct 12085]          gate.py:105   ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/gate/worker.py", line 203, in handle_http_request
    content = HttpMiddlewareAggregator(stack + [self.handler]).handle(http_context)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 77, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 77, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python2.7/dist-packages/aj/routing.py", line 30, in handle
    for instance in HttpPlugin.all(self.context):
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 115, in _all
    return list(context.get_components(cls))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 37, in get_components
    yield self.get_component(comp)
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_packages/views.py", line 14, in __init__
    self.managers = dict((x.id, x) for x in PackageManager.all(self.context))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 115, in _all
    return list(context.get_components(cls))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 37, in get_components
    yield self.get_component(comp)
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_packages/managers/yum_manager.py", line 23, in __init__
    self.yum.doGenericSetup(cache=1)
  File "/usr/lib/python2.7/dist-packages/yum/**init**.py", line 232, in doGenericSetup
    self.conf.cache = cache
  File "/usr/lib/python2.7/dist-packages/yum/**init**.py", line 896, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 300, in _getConfig
    startupconf = config.readStartupConfig(fn, root)
  File "/usr/lib/python2.7/dist-packages/yum/config.py", line 880, in readStartupConfig
    startupconf.releasever = _getsysver(startupconf.installroot, startupconf.distroverpkg)
  File "/usr/lib/python2.7/dist-packages/yum/config.py", line 1025, in _getsysver
    raise Errors.YumBaseError("Error: " + str(e))
YumBaseError: Error: rpmdb open failed

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 52, in dispatch
    content = self.handler.handle(http_context)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 77, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python2.7/dist-packages/aj/gate/middleware.py", line 209, in handle
    raise WorkerError(resp.object)
WorkerError: {"exception": "YumBaseError()", "type": "http", "error": "Error: rpmdb open failed"}
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,lv;q=0.6',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'session=099b62463347544d0a14401f8c7a95434d5c5fe0; mp_df4919c7cb869910c1e188dbc2918807_mixpanel=%7B%22distinct_id%22%3A%20%2215018a250f93e7-06859ce99-1f2a130a-1fa400-15018a250fa353%22%2C%22version%22%3A%20%222.0.71%22%2C%22platform%22%3A%20%22debian%22%2C%22platformUnmapped%22%3A%20%22ubuntu%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D',
 'HTTP_HOST': '192.168.7.184:8000',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.95 Safari/537.36',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': 'x.x.x.x',
 'REMOTE_PORT': '33819',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'xxx',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'SSL': True,
 'SSL_CLIENT_CERTIFICATE': None,
 'SSL_CLIENT_USER': None,
 'SSL_CLIENT_VALID': False,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f60c28311e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f60b2632310>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with WorkerError

21.10.2015 17:00  [rstrct 12085]          gate.py:105   DEBUG                        ... GET /favicon.ico
error: cannot open Packages database in /root/.rpmdb
21.10.2015 17:00  [rstrct 12085]          gate.py:105   ERROR    Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/gate/worker.py", line 203, in handle_http_request
    content = HttpMiddlewareAggregator(stack + [self.handler]).handle(http_context)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 77, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 77, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python2.7/dist-packages/aj/routing.py", line 30, in handle
    for instance in HttpPlugin.all(self.context):
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 115, in _all
    return list(context.get_components(cls))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 37, in get_components
    yield self.get_component(comp)
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_packages/views.py", line 14, in __init__
    self.managers = dict((x.id, x) for x in PackageManager.all(self.context))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 115, in _all
    return list(context.get_components(cls))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 37, in get_components
    yield self.get_component(comp)
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_packages/managers/yum_manager.py", line 23, in __init__
    self.yum.doGenericSetup(cache=1)
  File "/usr/lib/python2.7/dist-packages/yum/**init**.py", line 232, in doGenericSetup
    self.conf.cache = cache
  File "/usr/lib/python2.7/dist-packages/yum/**init**.py", line 896, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 300, in _getConfig
    startupconf = config.readStartupConfig(fn, root)
  File "/usr/lib/python2.7/dist-packages/yum/config.py", line 880, in readStartupConfig
    startupconf.releasever = _getsysver(startupconf.installroot, startupconf.distroverpkg)
  File "/usr/lib/python2.7/dist-packages/yum/config.py", line 1025, in _getsysver
    raise Errors.YumBaseError("Error: " + str(e))
YumBaseError: Error: rpmdb open failed

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 52, in dispatch
    content = self.handler.handle(http_context)
  File "/usr/local/lib/python2.7/dist-packages/aj/http.py", line 77, in handle
    output = middleware.handle(context)
  File "/usr/local/lib/python2.7/dist-packages/aj/gate/middleware.py", line 209, in handle
    raise WorkerError(resp.object)
WorkerError: {"exception": "YumBaseError()", "type": "http", "error": "Error: rpmdb open failed"}
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '_/_',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,lv;q=0.6',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'session=099b62463347544d0a14401f8c7a95434d5c5fe0; mp_df4919c7cb869910c1e188dbc2918807_mixpanel=%7B%22distinct_id%22%3A%20%2215018a250f93e7-06859ce99-1f2a130a-1fa400-15018a250fa353%22%2C%22version%22%3A%20%222.0.71%22%2C%22platform%22%3A%20%22debian%22%2C%22platformUnmapped%22%3A%20%22ubuntu%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D',
 'HTTP_HOST': '192.168.7.184:8000',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.95 Safari/537.36',
 'PATH_INFO': '/favicon.ico',
 'QUERY_STRING': '',
 'REMOTE_ADDR': 'x.x.x.x',
 'REMOTE_PORT': '33834',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'xxxxx',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'SSL': True,
 'SSL_CLIENT_CERTIFICATE': None,
 'SSL_CLIENT_USER': None,
 'SSL_CLIENT_VALID': False,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f60c28311e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f60b26323d0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with WorkerError

**Comment by Eugeny** [comment]
Please try again with this plugin update:

`sudo pip install ajenti.plugin.packages==0.24`

**Comment by minotaurdsp** [comment]
Thanks
It helped a bit
But still in web dashboard i get 
YumBaseError  On Ubuntu Server "it is strange"

Also sudo elevate not working 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/views/api.py", line 148, in handle_api_sidebar
    'sidebar': Sidebar.get(self.context).build(),
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/api/sidebar.py", line 62, in build
    authorize('sidebar:view:%s' % item['url']).check()
  File "/usr/local/lib/python2.7/dist-packages/aj/auth.py", line 222, in check
    for p in permission_provider.provide()
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_core/main.py", line 62, in provide
    for item in provider.provide()
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_packages/main.py", line 20, in provide
    } for mgr in PackageManager.all(self.context)]
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 122, in _all
    return list(context.get_components(cls, ignore_exceptions=ignore_exceptions))
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 38, in get_components
    instance = self.get_component(comp)
  File "/usr/local/lib/python2.7/dist-packages/jadi/jadi.py", line 32, in get_component
    self.component_instances[fqdn] = cls(self)
  File "/usr/local/lib/python2.7/dist-packages/ajenti_plugin_packages/managers/yum_manager.py", line 23, in __init__
    self.yum.doGenericSetup(cache=1)
  File "/usr/lib/python2.7/dist-packages/yum/**init**.py", line 232, in doGenericSetup
    self.conf.cache = cache
  File "/usr/lib/python2.7/dist-packages/yum/**init**.py", line 896, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 300, in _getConfig
    startupconf = config.readStartupConfig(fn, root)
  File "/usr/lib/python2.7/dist-packages/yum/config.py", line 880, in readStartupConfig
    startupconf.releasever = _getsysver(startupconf.installroot, startupconf.distroverpkg)
  File "/usr/lib/python2.7/dist-packages/yum/config.py", line 1025, in _getsysver
    raise Errors.YumBaseError("Error: " + str(e))
YumBaseError: Error: rpmdb open failed

**Comment by Eugeny** [comment]
This is happening because there's a python-yum package installed on your system.
I've added another update to ignore that: `sudo pip install ajenti.plugin.packages==0.25`
