### ISSUE TITLE
Why is it such errors if ubuntu dont use  rpmdb database

### ISSUE THREAD

**Issue by minotaurdsp** [ajenti/ajenti#804]
it looks that ajenti confusing distribution 
error: cannot open Packages database in /root/.rpmdb
21.10.2015 17:47  [...    21207]  ERROR    Could not instantiate <class 'aj.plugins.packages.api.PackageManager'>: Error: rpmdb open failed

**Comment by Eugeny** [comment]
Please don't open multiple issues for a single bug
