### ISSUE TITLE
Ajenti-V: Mail TLS Disable Error

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#809]
Hello!

There is an issue with the latest update of courier. Even with TLS disabled under 'Mail' in Ajenti, the following line is added to /etc/courier/imapd-ssl when a change is made to the mail users:

IMAP_TLS_REQUIRED=1

This therefore forces the system into TLS mode, and because it is disabled, there is no certificate info available. It therefore throws out an error, and no users are able to login.

Thanks,
Rhys

**Comment by Xefir** [comment]
You're totally right. It's seems to be the same issue as https://github.com/Eugeny/ajenti-v/issues/197
We definitively have to fix this mess and revert the responsible PR https://github.com/Eugeny/ajenti-v/pull/193 (at minima the courier part)
