### ISSUE TITLE
FORCE HTTPS

### ISSUE THREAD

**Issue by noobscode** [ajenti/ajenti#825]
I have multiple sites running https, first of I have issues with redir non-https to https. What is the recomended way?

Secound, when I check the ssl box in "ports" I get an error. Like it cant listen on 443 on multiple websites at the same time

**Comment by jaredtbates** [comment]
I've been putting
`if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
}`
into the custom configuration area under advanced. I don't know about your other issue though... I'm able to bind multiple sites to the same port just fine. Are you using different domain names for each?
