### ISSUE TITLE
Imap login does not work because makeuserdb says /etc/authlib/userdb: MAY NOT HAVE GROUP OR WORLD PERMISSIONS!!

### ISSUE THREAD

**Issue by orglnte** [ajenti/ajenti#829]
As a fix, I added line in api.py before the call to makeuserdb:
os.chmod(self.courier_userdb, 0600)

Platform is 
CentOS release 6.7 (Final)
Version is
ajenti-v-0.2.53-1.noarch
ajenti-v-nginx-0.1.41-1.noarch
ajenti-v-mail-0.1.32-1.noarch
ajenti-1.2.22.23-1.noarch
ajenti-repo-1.0-1.noarch

**Comment by Eugeny** [comment]
added
