### ISSUE TITLE
Ajenti SSL certificate

### ISSUE THREAD

**Issue by Rikcon** [ajenti/ajenti#830]
Hello everyone, i have a problem with ajenti ssl certificate settings.
So, letsencrypt is finally here, so we can have as meny cetrificates as we want.
I generated a cert for panel.mydomain.com
Letsencrypt gave me some files:
cert.pem
chain.pem
fullchain.pem
privkey.pem

In the ajenti settings there is a certificate path, i tried every file path that letsencrypt gave me.
All i get is connection reset due to cert error.

Maybe someone knows how to make it work ?

**Comment by Eugeny** [comment]
Hi, you're supposed to use a combined PEM, that is, fullchain + privkey concatenated into one file.

**Comment by Rikcon** [comment]
Thank you, problem solved.
