### ISSUE TITLE
BIND9 plugin, wrong path to zone file

### ISSUE THREAD

**Issue by gdevdeiv** [ajenti/ajenti#831]
Hello!

I'm running Ajenti on Ubuntu 14.04 x64, and I've noticed that every time I create a DNS zone, it adds a wrong entry to the named.conf file, causing an error that will prevent the service from starting.

It basically does:

> zone "test.com" {
>         type master;
>         file "db.test.com";
> };

It should be "/etc/bind/db.test.com". I've been trying to come up with a solution, but I have nearly-zero Python coding skills, so I've been fixing that manually each time I created a zone.

Thanks,
David.

**Comment by kourindouhime** [comment]
I second that. Happened to me also.

**Comment by kourindouhime** [comment]
So the fix is just to write full path when filling zone file (e.g. /etc/bind/db.yourzone). Bug in https://github.com/Eugeny/reconfigure
