### ISSUE TITLE
Ajenti V installed, but no Mail option

### ISSUE THREAD

**Issue by emergingdzns** [ajenti/ajenti#837]
The Mail option is missing from the Ajenti control panel even though ajenti-v-mail is installed as well as courier and exim.

**Comment by emergingdzns** [comment]
Clearly Ajenti was not the right tool as it doesn't seem to be stable or complete. 11 days and no response from the dev team...

**Comment by Xefir** [comment]
Have you tried to restart ajenti service ?

`sudo service ajenti restart`

Can you put more log here please ?

Like that, it's hard to answer you =/

**Comment by emergingdzns** [comment]
Thanks @Xefir. Restarting the service didn't help, but I just logged into my Ajenti panel and saw that there was an update. I applied the update and now the FTP and Mail options appear.
