### ISSUE TITLE
CentOS 7.2  segmentation fault

### ISSUE THREAD

**Issue by ph4r5h4d** [ajenti/ajenti#846]
Installed Ajenti on the newest CentOS 7.2 and there was a problem lunching the panel from browser , then tried ajenti-panel -v and when i tried to lunch the panel via web browser there was a segmentation fault error and nothing showed up ( actually a connection failed message on browser) 
didn't dig up much on server 
BTW i was testing it on a CloudStack platform with sourcenat , i was also happened to check config file of Ajenti  and it was bound to 0.0.0.0 , i didn't try for putting public ip because i was trying to create a template from that instance and it would be useless to me .
Just letting Ajenti developers know that there may be a problem with the new update of CentOS 7
This was working fine with CentOS 7.1

**Comment by ph4r5h4d** [comment]
Just seen the https://github.com/ajenti/ajenti/issues/845 , i had the same error log but with 7.2 , this was totally ok on 7.1

**Comment by dsekelj** [comment]
I can confirm I have the same problem on CentOS 7.2.1511 upgraded from CentOS 7.1.1503. 

After some investigation with gdb I get this error when accessing the web font-end from the browser. 

Program received signal SIGSEGV, Segmentation fault.
0x00007fffeffe2480 in load_cert_chain_args.isra.16 () from /usr/lib64/python2.7/lib-dynload/_ssl.so

Not sure how to go further from here, but thought I should report what I found.

**Comment by SFKS** [comment]
Same problem here after updating to CentOS Linux release 7.2.1511 .

**Comment by ghost** [comment]
Same issue here, Ajenti doesn't work with HTTPS at all now, netstat doesn't even show it listening with SSL enabled in the config. abrt shows "python2.7 killed by SIGSEGV". Disabling SSL seems to solve the problem but is unacceptable.

**Comment by DrDLL** [comment]
+1 CentOS Linux 7.2.1511 after updating packets, Ajenti with SSL doesn't work. Disabling SSL solve problem

**Comment by Silarn** [comment]
I can also confirm this error.

I'll add that I'm able to bypass this using an apache reverse proxy on an SSL-enabled port. Apache handles the ssl and data transfer. Ajenti even recognizes that it's using SSL even though it's not running in SSL mode, which is nice.

I'm sure you can use similar techniques with nginx.

**Comment by Silarn** [comment]
Nevermind, I can't get past the login. It doesn't seem to be processing the request. Maybe this is just a configuration issue, but I couldn't figure out the problem.

**Comment by jbwhaley** [comment]
I'm having this issue too, and it's really driving me crazy trying to figure out a fix. Please let us know if any solutions become apparent.

**Comment by nosovk** [comment]
temporary fix is to disable ssl in ajenti config

**Comment by hplodur** [comment]
Same problem here. Ajenti crash after https address is requested. Temporary fix works. Any news regarding the problem? Is there a known cause?

**Comment by SFKS** [comment]
I moved to Debian + Vesta. Good luck.

2016-02-15 14:35 GMT+01:00 hplodur notifications@github.com:

**Comment by Xefir** [comment]
After a loooooong search, I found the guilty ! It's Python itself, not Ajenti !!!

On CentOS, the Python's versions is 2.7.5 and have a sslwrap.
But this wrap it bugged and crash all the time.

If you want to have Ajenti working, you have to do this modification : https://github.com/ajenti/ajenti/pull/882

**Comment by jbwhaley** [comment]
Any thoughts on @Xefir's hack?

**Comment by hplodur** [comment]
Thank you very much @Xefir it's working!

**Comment by jbwhaley** [comment]
It’s working for me too. Thanks!

I’m not terribly familiar with `sslwrap`, however; are we sure there are no security implications to this fix?

**Comment by Xefir** [comment]
This sslwrap is loaded either by gevent or by Python. It grab the Python code to put in Ajenti because it was scrap from 2.7.9 (see here : https://github.com/gevent/gevent/issues/477). So, in all case, this code is executed, but in that case, the internal function of Python is bugged, this is why I rewrite it by the same thing, like Eugeny did in the first time if the function is missing.

About the security concern, like I said, it's always executed, internaly ou externaly, so I don't think it change something, but like I say in my PR, I'm not a Python expert x)

**Comment by Nezteb** [comment]
This solution works, but any idea when it will make it into the automatic installer version? http://support.ajenti.org/topics/1122-installing-on-centosrhel/

Otherwise it has to be done manually, which is fine. I'm just curious.

**Comment by Xefir** [comment]
It's deploy now for all package manager normally ?

Do you try it ? It is not the case ?

**Comment by Nezteb** [comment]
Right before I posted my last comment I tried the installation link above and it was still the broken version with the old SSL wrap. I had to fix it manually. I will try it again tomorrow and report back.

**Comment by Nezteb** [comment]
So, yeah, the old SSL wrap is still present when using this:

> curl https://raw.githubusercontent.com/ajenti/ajenti/1.x/scripts/install-rhel7.sh | sh

And then `/usr/lib/python2.7/site-packages/ajenti/compat.py` still has `if not hasattr(_ssl, 'sslwrap') and not hasattr(gevent.ssl, 'SSLContext'):` on line 120.

Changing that one line and restarting ajenti works as expected.

**Comment by tonypartridge** [comment]
this is still an issue on Centos7 today.

**Comment by projectivemotion** [comment]
Ran into this issue on CentOS 7.2 

https://github.com/ajenti/ajenti/commit/9d09056c16fdcad5603fc3a0d7446865c5a21194 Fixes the problem.
