### ISSUE TITLE
Ajenti 2 Upgrade

### ISSUE THREAD

**Issue by MaximKiselev** [ajenti/ajenti#849]
http://habrahabr.ru/post/274397/ Привет, можно ли будет нормально обновиться до 2 версии? И перенести часть плагинов хотя бы?

> существующая аудитория проекта заживо меня распнет ввиду уменьшившегося функционала.

уже начинаем :-D. Ну и с праздниками) :+1: 

PS сделай поддержку для вопросов "Как поставить PHP" платной или MailList сделай (он удобней для вопросов такого уровня).

**Comment by Eugeny** [comment]
Увы, просто "обновиться" нельзя. Из-за смены принципа работы плагины написаны заново.

**Comment by MaximKiselev** [comment]
Ну в принципе, я так и думал. Хм, поддержка 1x версии вообще планируется? Хотя бы в плане пулл-реквестов и сборок пакетов?

**Comment by Eugeny** [comment]
Да. Буквально пару дней тому вышло обновление с фиксами.

**Comment by MaximKiselev** [comment]
Евгений, а где ветка 2, я ее найти не могу: ни на сайте ни на гите?

**Comment by Eugeny** [comment]
Это master в ajenti/ajenti. Версия 1 в ветке 1.х

**Comment by MaximKiselev** [comment]
Спасибо, думал отдельный репозиторий где то.
