### ISSUE TITLE
Too much RAM usage

### ISSUE THREAD

**Issue by ChillarAnand** [ajenti/ajenti#852]
Looks like ajenti is using too much memory

![ram](https://cloud.githubusercontent.com/assets/4463796/12114261/73ef467e-b3ce-11e5-9007-54c4cf41716e.png)

**Comment by DrDLL** [comment]
ajenti-panel    /usr/bin/python /usr/bin/ajenti-panel -d    12.2    198376 K    root

**Comment by janxb** [comment]
My ajenti with a LOT of plugins (including ajenti-v) is around 200MB of RAM, so i think this is normal..

**Comment by wario9k** [comment]
Hi,
i use Ajenti-v and have the same problem. The ram is fulled by ajenti-panel
 @ChillarAnand  have you fixed?


modify: i have 4 server and use ajenti-v in all server... but only one have this probelm. :(

**Comment by ChillarAnand** [comment]
@wario9k no

**Comment by wario9k** [comment]
@ChillarAnand  Sigh

**Comment by antanariva** [comment]
Look, i see this process eat memory more and more from hour to hour.
After reboot it was less 100M, after 13 hour - 243...
May be somebody resolve this problem already?
