### ISSUE TITLE
FontAwesome Icons missing in ajenti V

### ISSUE THREAD

**Issue by jonash0** [ajenti/ajenti#855]
FontAwesome Icons missing in ajenti V.

**Comment by jakoss** [comment]
All image assets are missing here too (ubuntu standard installation)

**Comment by tsonev** [comment]
Same here Ubuntu 15.10. Following is the console dump:

>  192.168.0.104/:9 The key "target-densitydpi" is not supported.
> (index):1 Failed to decode downloaded font: https://192.168.0.104:8105/ajenti:static/main/OpenSans.woff
> (index):1 OTS parsing error: invalid version tag
> (index):1 Failed to decode downloaded font: https://192.168.0.104:8105/ajenti:static/main/OpenSans-Bold.woff
> (index):1 OTS parsing error: invalid version tag
> (index):1 Failed to decode downloaded font: https://192.168.0.104:8105/ajenti:static/main/fontawesome.woff
> (index):1 OTS parsing error: invalid version tag
> (index):1 Failed to decode downloaded font: https://192.168.0.104:8105/ajenti:static/main/PS-Bold.woff
> (index):1 OTS parsing error: invalid version tag
> resources.js:10444 Welcome to Ajenti
> resources.js:10445 version 1.2.23.2

**Comment by Xefir** [comment]
How did you install Ajenti ?
By package manager, pip or manually via git ?

**Comment by jakoss** [comment]
Package manager (apt-get)

**Comment by tsonev** [comment]
apt-get too. It worked alright for some time and 2-3 months ago all font packages started throwing this error

**Comment by tsonev** [comment]
Ajenti works just fine only font packs are not loaded and in its place jumbled images are shown

**Comment by Xefir** [comment]
I think I found.
It's because you have outdated css (and js).

Ajenti works with less and coffee script that are compiled on the package you download through apt-get.
It seems that on some distribution, this step fails and CSS/JS isn't updated on distributed package.

The compilation is handled by compile_resources.py and require coffee and less to be installed.
I wait for the response of the #895 PR on this issue

**Comment by tsonev** [comment]
hm Im not sure thats it. It would seem that all media content(font packs and images) are not served correctly and result in 21B in response header data only. 
![image](https://cloud.githubusercontent.com/assets/5079047/13470249/fc69c53a-e0b3-11e5-9019-8f65965cdc86.png)

**Comment by tsonev** [comment]
ok if I try to directly open one of those 21B resources I get an Internal Server Error with status 200?! Where can I find an error log ?
![image](https://cloud.githubusercontent.com/assets/5079047/13470666/ec854282-e0b5-11e5-9867-8a4d844c7726.png)

**Comment by Xefir** [comment]
Interesting. The error log is on /var/log/ajenti/ajenti.log. I'm waiting for your input :)

**Comment by tsonev** [comment]
already checked it. Nothing there only information about last login by root from which IP. 

Interesting thing is that if I start ajenti with the system as daemon /usr/bin/python /usr/bin/ajenti-panel -d then images are not shown. If I kill the process and start it again from console then images are shown.

**Comment by Xefir** [comment]
I think, you got the point !

Actually, if your service manager messed up with ajenti, it don't delete the pid file. So for the service manager, ajenti was off whereas it was on.
So if you do service ajenti restart before killing all the python's processes associated with ajenti, ajenti has never been restarted properly.

The pid file is on /var/run/ajenti.pid, if you kill all ajenti's processes again, remove the pid file and start it normally from service manager, did it load properly ?

I think it was kind of this thing you have experienced all, I hope doing like the previous sentence will fix all this mess forever ^^

**Comment by tsonev** [comment]
Here is the result:
If I service ajenti stop - there is no /var/run/ajenti.pid file left
If I service ajenti start - there are no images
if I /usr/bin/python /usr/bin/ajenti-panel - there are images

**Comment by Xefir** [comment]
Okay, it's not that. I'll investigate further :(

**Comment by ghost** [comment]
Hello everyone. Any progress on that? Maybe some workaround?

**Comment by pedroetb** [comment]
Same problem, waiting for solution/workaround. Thanks!

**Comment by walkin-corpse** [comment]
Same sh*t! Nomatter if I start with service or with panel.

Upd: 
That's WHY: http://support.ajenti.org/topics/261-not-loading-images-and-fonts/#
