### ISSUE TITLE
Websites menu item gone after latest update

### ISSUE THREAD

**Issue by tadaskarpavicius** [ajenti/ajenti#864]
Hey, I just updated the Ajenti and after the Ajenti restarted the "Websites" menu item is no longer visible. Websites are working, but I can't manage them. 
Any ideas?
Yesterday everything was up to date. But I removed the ajenti-v-mail component. Maybe that has something to do with this?

**Comment by Xefir** [comment]
Because of this https://github.com/Eugeny/ajenti-v/pull/213

I push a fix here https://github.com/Eugeny/ajenti-v/pull/219 and I wait for the PR to be accepted

**Comment by tadaskarpavicius** [comment]
Thanks! Hopefully it will be accepted soon.
