### ISSUE TITLE
Security check returns: Check for SSL Weak Ciphers

### ISSUE THREAD

**Issue by mikestp27** [ajenti/ajenti#867]
It looks like ajenti connects with SSLv2 which is not secure.  Can this be changed in the configuration?   The websites hosted on the server are all ok.  It's the ajenti control panel that is weak...
Server is Ubuntu 14.04LTS (all patches applied)
When running a security check (openVAS), I get Check for SSL Weak Ciphers.

**Comment by Xefir** [comment]
Already fixed by #796. Can you close it ? :)
