### ISSUE TITLE
Maintenance mode disabled, still 503 Service Unavailable!

### ISSUE THREAD

**Issue by PontusTideman** [ajenti/ajenti#876]
Hi all!

Everything is up and running smooth, besides the small glitch with the Maintenance mode when that is disabled.

I´ve installed RainLoop with this guide: [https://www.digitalocean.com/community/tutorials/installing-the-rainloop-email-client-on-ajenti-v](url) but ain´t working proper. The subdomain that is used mail.mydomian.tld is throwing up a 503 Service Unavailable even thou it´s disabled!

Any tip?

**Comment by Xefir** [comment]
You have a misconfiguration on your nginx file.
If you make a mistake, nginx will not restart to prevent it to crash.

Please verify on the website list, in the bottom, if you don't have an error (all entry must have a ✔︎)

**Comment by PontusTideman** [comment]
It was the freaking Rainloop-site that was doing this error...

nginx: [emerg] location "/data" is outside location "[^/].php(/|$)" in /etc/nginx/conf.d/rainloop.conf:24
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by Xefir** [comment]
Is your problem fixed ? If so, could you please close the issue ? :)

**Comment by dessar-sega** [comment]
same problems

**Comment by aniket-modkar** [comment]
Please check /etc/nginx/conf.d directory there will be your_website_manage.conf file nano or vi that file and check the server name in that file. Server name should not contain that "example.com".
If "example.com" text is present there then remove that example.com and save your file the run this commands
service ajenti restart
service nginx restart

**Comment by ani2498** [comment]
Please check /etc/nginx/conf.d directory there will be your_website_manage.conf file nano or vi that file and check the server name in that file. Server name should not contain that "example.com".
If "example.com" text is present there then remove that example.com and save your file the run this commands
`service ajenti restart
``service nginx restart`
