### ISSUE TITLE
With latest Ubuntu 14.04LTS update, Ajenti crashes when saving changes

### ISSUE THREAD

**Issue by mikestp27** [ajenti/ajenti#879]
Getting a crash when changing settings under websites, emails, firewall, users and apache.  Everything was working great before.  This morning we updated Ubuntu 14.04LTS (previous update was a week ago).  Will try to backtrack what has changed in the Ubuntu updates for the week. 

Crash report from Ajenti is (after changing an email's password):

```
org.freedesktop.DBus.Error.ServiceUnknown: The name :1.0 was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 158, in handle_message
    self.ui.dispatch_event(update['uid'], update['event'], update['params'])
  File "/usr/lib/pymodules/python2.7/ajenti/ui/__init__.py", line 72, in dispatch_event
    self.root.dispatch_event(uid, event, params)
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 382, in dispatch_event
    if child.dispatch_event(uid, event, params):
  File "/usr/lib/pymodules/python2.7/ajenti/ui/element.py", line 388, in dispatch_event
    getattr(self, k)(**(params or {}))
  File "/var/lib/ajenti/plugins/vh-mail/main.py", line 169, in save
    self.manager.save()
  File "/var/lib/ajenti/plugins/vh-mail/api.py", line 356, in save
    self.backend.configure(self.config)
  File "/var/lib/ajenti/plugins/vh-mail/api.py", line 314, in configure
    EximRestartable.get().restart()
  File "/var/lib/ajenti/plugins/vh-mail/api.py", line 399, in restart
    default='exim',
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/services/api.py", line 29, in get_one
    s = mgr.get_one(name)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/services/api.py", line 45, in get_one
    for s in self.get_all():
  File "/usr/lib/pymodules/python2.7/ajenti/util.py", line 75, in wrapper
    val = fx(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ajenti/plugins/services/sm_upstart.py", line 54, in get_all
    jobs = self.upstart.GetAllJobs(dbus_interface="com.ubuntu.Upstart0_6")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.0 was not provided by any .service files
```

**Comment by Xefir** [comment]
Did you upgrade ajenti too ?
Did you restart the ajenti's service ?
You went from witch Ubuntu version before 14.04LTS ?

(I ask for this because Ubuntu, Debian, and lot's of distro change from sysinitv to systemd. Ajenti support both, but the choice between the two seem's to be done at the service's launch)

**Comment by mikestp27** [comment]
Thanks to VM snashots... Easy to go back in time and undo stuff. So I went back to a snapshot from a week ago; retested that it was working fine; applied the Ubuntu 14.04LTF updates of the week.  And then Ajenti starts crashing as described above.  
Here's the list of packages that were updated:

```
The following packages will be upgraded:
  base-files initscripts libc-bin libc-dev-bin libc6 libc6-dbg libc6-dev 
  libgcrypt11 libsmbclient libwbclient0 multiarch-support ntpdate 
  python-samba samba-common samba-common-bin samba-libs 
  smbclient sysv-rc sysvinit-utils
Do you want to continue? [Y/n] Y

```

I will not try to narrow it down....

**Comment by mikestp27** [comment]
Thank you Xefir for your reply.  I didn't upgrade from a previous version of Ubuntu.  It was just regular updates to Ubuntu 14.04.03LTS.  List of updates packages above.  Ajenti was already up to date.  And restarted it too.

**Comment by Xefir** [comment]
On 14.04.4LTS Desktop, Ajenti works perfectly (after install the usual gevent 1.1b4).

I'll try to reproduice your configuration. It's a desktop or server version of ubuntu ?
You went FROM 14.04.3 or TO 14.04.3 ? (the latest is 14.04.4)
What the base version and edition ?

Thank you

**Comment by mikestp27** [comment]
Hello Xefir, I though I had updated this issue but it looks like I forgot to click save...  I will re-post it shortly...

**Comment by mikestp27** [comment]
Here's the update.   I did several tests using snapshot images of the server going back and forth and re-trying the same steps.   It now looks like the problem is not related to anything in the modules updated.  It looks like a simple "sudo apt-get upgrade" is the issue.  
Here's the latest, simplest, repro-steps: 
1. reboot the machine to make sure we have a well known state
2. tries different thins in ajenti, everything in ajenti works fine 
3. in terminal, run "sudo apt-get upgrade"  -- even if nothing to upgrade
4a. in ajenti, saving some configuration settings will result in a crash like described in initial post
4b. in ajenti, trying to restart a service (tried apache, bind, firewall...) will result in a crash like described in initial post
5. At any time, in terminal, "sudo service xxx restart" works fine, no problems
6. in terminal, run "sudo service ajenti restart"
7. everything in ajenti works fine (saving config or restarting services)
I suppose the problem is not really when ajenti saves the settings as the settings appear to be saved properly; it looks like the crash happens when ajenti attempts to restart a service after the config change.  
So it looks like "sudo apt-get upgrade" makes ajenti unable to restart services; even if the upgrade did not change any module.
At this point, I'm not sure what to investigate next.  I have a work around: simply restart ajenti after any upgrade; it's a bit annoying but it works.

**Comment by Xefir** [comment]
I had well diagnose the problem.
Ajenti mistake the choice of the service manager.
Instead of systemd, it choose sysvinit, witch you have too.

Could you please paste me the log when you start ajenti, util `core.run(): SSL enabled:` ?
I would like to know how YOUR ubuntu load and choose the service manager.

(if personal infos reside in it, you can scrap them)

**Comment by mikestp27** [comment]
Hello Xefir.  Your diagnostic sounds logical.  When it crashes, it seems to be around where ajenti decides how to restart the service.   Here are the first few lines of the ajenti log after a reboot:

```
2016-02-23 22:26:39,693 INFO     registry.register_crypt_handler(): registered crypt handler 'sha512_crypt': <class 'passlib.handlers.sha2_crypt.sha$
2016-02-23 22:26:39,995 INFO     core.run(): Ajenti 1.2.23.3 running on platform: debian
2016-02-23 22:26:41,842 INFO     core.run(): Starting server on (u'127.0.0.1', 8000)
2016-02-23 22:34:27,277 INFO     users.check_password(): user root logged in through AjentiSyncProvider from 127.0.0.1
```

The lines that follow depends on what I do in Ajenti; but what I do in Ajenti seems irrelevant; it's the service restart that seems to cause the crash. 
Thank you for you help.

**Comment by Xefir** [comment]
I think about something, maybe you have some init script reside in your distro about post uninstall packages.
Did you try to do a `apt-get purge` to remove old files from uninstalled packages ?
If you do this command, don't type yes without reading what is does, this command is destructive ( like the files is permanently removed, not because it'll crash your system of course x) )
Restart ajenti service after and try again.

Because the log you post shows that Ajenti select the first manager witch is Upstart, and, as far as I know, it's the default manager on Ubuntu, so it's good ( systemd is for non LTS systems, begins with 15.04, i totally forgot this x) )

**Comment by mikestp27** [comment]
I tried `apt-get purge` and it does nothing (nothing to purge).  
After a `apt-get purge`, Ajenti is still able to restart services (even if I haven't restarted Ajenti).
If I do a `apt-get purge`, restart Ajenti and then do `apt-get upgrade` and try to restart a service in Ajenti, I get the error.
My system is running Ubuntu 14.04.04LTS - it was 14.04.03LTS when the issue was created.

**Comment by Xefir** [comment]
Okay, this was just an idea. I'll try to get all setup on VMs. If I succeed to reproduce your problem, I'll get you in touch :)

**Comment by mikestp27** [comment]
Hi Zefir, thank you for your help.  As I said in previous post, I have a work around (restart ajenti after `apt-get upgrade`).  I don't upgrade that often so it's not the end of the world.  You can focus on other issues first if you prefer.   Thank you.

**Comment by Xefir** [comment]
I don't succeed to reproduce your problem :( 

Just to be sure, can you do this (it'll install pip for listing python eggs installed) : 

```
python --version
sudo apt-get install python-pip
sudo pip list
```

Just to compare with my environment.

**Comment by mikestp27** [comment]
Good morning Xefir, here's the info you requested:

```
admin@server:/$ python --version
Python 2.7.6
admin@server:/$ sudo pip list
ajenti (1.2.23.4)
apt-xapian-index (0.45)
argparse (1.2.1)
authres (0.602)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
distro-info (0.12)
euca2ools (3.0.1)
gevent (1.0)
gevent-socketio (0.3.6)
gevent-websocket (0.9.3)
greenlet (0.4.2)
html5lib (0.999)
ipaddr (2.1.10)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
lockfile (0.8)
lxml (3.3.3)
Mako (0.9.1)
MarkupSafe (0.18)
meld3 (0.6.10)
oauth (1.0.1)
PAM (0.4.2)
passlib (1.5.3)
Pillow (2.3.0)
pip (1.5.4)
prettytable (0.7.2)
psutil (1.2.1)
pydns (2.3.6)
pygobject (3.12.0)
pyinotify (0.9.4)
pyOpenSSL (0.13)
pyserial (2.6)
pyspf (2.0.8)
python-apt (0.9.3.5ubuntu2)
python-catcher (0.1.7)
python-daemon (1.5.5)
python-debian (0.1.21-nmu2ubuntu2)
python-exconsole (0.1.5)
python-ldap (2.4.10)
PyYAML (3.10)
pyzor (0.5.0)
reconfigure (0.1.75)
requestbuilder (0.1.0-beta1)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
ssh-import-id (3.21)
supervisor (3.0b2)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
virtualenv (1.11.4)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)

```

**Comment by oguzhanaslan** [comment]
+1

**Comment by kroese** [comment]
+1

**Comment by Nevensky** [comment]
+1
