### ISSUE TITLE
https really slow

### ISSUE THREAD

**Issue by nathank1989** [ajenti/ajenti#881]
So I saw one or two other threads dated about 1-2 years ago about HTTPS being painfully slow. I have followed all the steps here:
https://github.com/ajenti/ajenti/issues/725
and 
http://support.ajenti.org/topics/511-https-loading-very-slow/

Debian Jessie 8 
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
Python 2.7
Gevent 1.1rc4
Greenlet 0.4.9
Apache Server version: Apache/2.4.10 (Debian)
Server built:   Nov 28 2015 14:05:48
Server's Module Magic Number: 20120211:37
Server loaded:  APR 1.5.1, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit

If I disable SSL in config.json it works, but this is not ideal for WAN connections.

**Comment by Xefir** [comment]
> Gevent 1.1rc4

Please downgrade to 1.1b4 or 1.1b3.
It's the only versions of gevent witch works with current ajenti.

**Comment by nathank1989** [comment]
I'm a little new so how would I downgrade? :) :+1:

**Comment by Xefir** [comment]
`sudo easy_install -U gevent==1.1b4`

Don't forget to have all the package needed for compiling stuff, like build-essential, python-dev and python-pip (for easy_install command).

**Comment by nathank1989** [comment]
BRO! If I knew you in person, I'd buy you a case of brews or an 8th of green. I have spend 6+ hours on google trying to find a solution and this was it.
THANK YOU!
