### ISSUE TITLE
Mail did not work after upgrade

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#889]
After I upgrade the system last night I saw today in the morning that the mail was not working, I could not send email through roundcube webmail or access the mail through Outlook. I even run "service exim4 restart" but it did not work, I had to go to Ajenti Panel, and at the Mail section click "Apply changes" without changing anything, than it worked. This problem happen on other upgrades as well, not only this one. It seems like some kind of configuration needs to be re-written by ajenti. My system is  Ubuntu 14.04.4 LTS

**Comment by Xefir** [comment]
Seems the same problem than #879.
Can you confirm ?

**Comment by ghost** [comment]
No, I did not get any crash when clicked "Apply changes" at the mail page like the other user, clicking "Apply changes" on mail page fixed the issue with email. I got the following error messages on Exim4 log.

When using outlook:
`2016-02-26 08:48:58 login authenticator failed for (MY_PC_NAME_HERE) [MY_IP_HERE]: 435 Unable to authenticate at present (set_id=MY_EMAIL_HERE): failed to connect to socket /var/run/courier/authda$
2016-02-26 08:48:58 TLS error on connection from (MY_PC_NAME_HERE) [MY_IP_HERE] (recv): A TLS packet with unexpected length was received.
2016-02-26 08:48:58 TLS error on connection from (MY_PC_NAME_HERE) [MY_IP_HERE] (send): The specified session has been invalidated for some reason.`

When using Roundcube:
`2016-02-26 09:15:44 login authenticator failed for (webmail.MY_DOMAIN_HERE) [2a01:7e01::f03c:91ff:fec8:e9b0]: 435 Unable to authenticate at present (set_id=MY_EMAIL_HERE): failed to connect to socket /var/r$`

**Comment by Xefir** [comment]
If you do a `service exim4 restart` now, after clicking on Apply that fix your problem, is that works ?

Maybe an exim's upgrade rewrite the /etc/exim4/exim4.conf that generate Ajenti.
It's important to always say 'no' when upgrades ask you to changes defaults config files managed by ajenti :)

**Comment by ghost** [comment]
I can not try that since it is a production server and it is in use now. But maybe with Ajenti there was a exim4 upgrade as well, I will take more look in the details if this occurs again and report back.
