### ISSUE TITLE
Ajenti crashes after update

### ISSUE THREAD

**Issue by Terion23** [ajenti/ajenti#893]
Hey,

after ich updated my ajenti today it doesnt work anymore. When I try to start/restart it I get this message:

service ajenti restart
Stopping Ajenti:
[FAIL] not running ... failed!
Starting Ajenti:
28.02.2016 19:38 INFO  Using config file /etc/ajenti/config.json
Traceback (most recent call last):
  File "/usr/bin/ajenti-panel", line 109, in <module>
    ajenti.config.load()
  File "/usr/lib/pymodules/python2.7/reconfigure/configs/base.py", line 42, in load
    (six.PY2 and isinstance(self.content, str)):
AttributeError: 'module' object has no attribute 'PY2'
[FAIL] failed ... failed!

Hope anyone can help me.
Thanks!

**Comment by Xefir** [comment]
Please see #891

**Comment by Xefir** [comment]
The problem has been fixed.

Could you test and close this issue if it's resolved ? Thank you :)
