### ISSUE TITLE
Enabling SRS by default for forwarding email addresses

### ISSUE THREAD

**Issue by barhun** [ajenti/ajenti#897]
Hi,

I thought it would be better if SRS were enabled by default for forwarding email addresses 'cause it helps avoid SPF check errors which desperately lead to delivery failures or delays. I have had two addresses both of which forward to various Gmail accounts and they frequently bounce back only for this reason.

I assume manuel configuration gets overwritten by ajenti's therefore many users will demand support for SRS and like having it enabled by default.

https://github.com/Exim/exim/wiki/SRS

**Comment by Xefir** [comment]
Like the documentation state : “SRS support is Experimental“
Not sure if we have to enable a non-stable function into ajenti =/

BUT ! You can enable yourself if you want :)
Go to Mail > Advanced
And put this into the custom config field (first field of the MTA's config) : 

```
EXPERIMENTAL_SRS=yes
```

That's all :)
