### ISSUE TITLE
SSL protocol error when connecting to https://server:8000

### ISSUE THREAD

**Issue by khromov** [ajenti/ajenti#899]
Installed on fresh Debian Jessie using the one-liner here:
http://support.ajenti.org/topics/1116-installing-on-debian/

Can't get into the control panel at all. Here is the error from Firefox:
![phail](https://cloud.githubusercontent.com/assets/1207507/13939231/7d0acd82-efd3-11e5-9a24-4f99720b3be7.png)

Curl gives:

``` bash
root@ajenti:~# curl https://ajenti.XXX.com:8000
curl: (35) Unknown SSL protocol error in connection to ajenti.XXX.com:8000
```

No idea where to go from here, suggestions?

**Comment by Xefir** [comment]
Did you try the usual gevent downgrade trick ? https://github.com/ajenti/ajenti/issues/702

On Jessie, Ajenti requiere a particular version of gevent (1.1b3 or 1.1b4).
Install it like this : `sudo easy_install -U gevent==1.1b4`

You have to have the `python-dev` package installed

**Comment by Eugeny** [comment]
The fixed `gevent-socketio` package (compatible with the new `gevent` versions) is now available in the Ajenti repo. You should be able to just update it, or install manually from http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb

**Comment by nkCreation** [comment]
Hi, sorry to comment on a closed topic but I cannot find an other one that describes the problem as good as this one does.

I'm facing the same issue : fresh install of Debian 9, ajenti etc... I also install your package 0.3.7.99 for gevent but still unable to access via https ! (Can force it in chrome but... Always say Not secure).

Does someone has a magic trick to make it works ?

Thank you so much.
