### ISSUE TITLE
Logwatch and exim4 - keep_environment message

### ISSUE THREAD

**Issue by fakedfaker** [ajenti/ajenti#906]
I get this messages from logwatch every day:

> /etc/cron.daily/exim4-base:
> LOG: MAIN
> Warning: purging the environment.
> Suggested action: use keep_environment.

and this:

> ****\* BAD FORMAT (Possible data corruption or Exim bug) *****
>   Suggested action: use keep_environment.
> 
>  **Unmatched Entries**
>  2016-04-04 00:00:08 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:05:07 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:10:07 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:15:07 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:20:07 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:25:07 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:30:07 Warning: purging the environment.: 2 Time(s)
>  2016-04-04 00:35:07 Warning: purging the environment.: 2 Time(s)
>  ....

did not find how to fix this messages..
Maybe anybody else got this and knows how to edit the config files to fix this.

**Comment by Xefir** [comment]
Already answered on ajenti-v repository : https://github.com/Eugeny/ajenti-v/issues/226

**Comment by fakedfaker** [comment]
Thx for the fast answer.. I searched for this, but did not find anything.
I will use this!

**Comment by dschensen** [comment]
#https://github.com/Eugeny/ajenti-v/issues/226
