### ISSUE TITLE
file manager access to home directory based on users

### ISSUE THREAD

**Issue by Iman-Snowleaf** [ajenti/ajenti#910]
I want to create multiple users with specific access to their home directory.

Currently, whenever I create a new ajenti user (which is synced with OS Users), it can access to the whole file system.

How can I limit their access to a specific directory like /home/user?

There is an option within the Configure > Plugins section of the root user which will limit the access on all users's file managers, but it cannot be used for specifying directories for each users.

**Comment by ruslanstarikov** [comment]
bump
