### ISSUE TITLE
Ajenti does not display anything after login

### ISSUE THREAD

**Issue by chrisbanes** [ajenti/ajenti#912]
Fresh install on Ubuntu 16.04. Login works but after that I don't see anything. Tried over HTTP and HTTPS, same result.

![screen shot 2016-04-23 at 10 19 52](https://cloud.githubusercontent.com/assets/227486/14766979/bd3e40e2-0a12-11e6-9b69-b475a10ef74b.png)

**Comment by joereynolds** [comment]
Happens to me as well. Like you, I've also disabled SSL (for the time being)

**Comment by Jonathan-Rosewood** [comment]
Solution - https://github.com/ajenti/ajenti/issues/903#issuecomment-215569332

**Comment by serh007** [comment]
how it fix?

**Comment by sorbing** [comment]
Also not display anything after login(

**Comment by sorbing** [comment]
I find answer. It is necessary to replace the numeric parameter to a string:

```
sudo gedit /usr/lib/python2.7/dist-packages/socketio/handler.py
```

Replace: `("Access-Control-Max-Age", 3600),` on `("Access-Control-Max-Age", "3600"),`
See: http://onedev.net/post/503
