### ISSUE TITLE
SSL works on all sites, one configured

### ISSUE THREAD

**Issue by edoniti** [ajenti/ajenti#918]
I have configured my main domain to have SSL certificate, now all web sites when I add HTTPS load and have wrong SSL since the domain of certificate is another domain, when I agree in the browser with the wrong certificate the main domain content loads. It would be good for other domains to not work at all with HTTPS since in the ports tab there is not any HTTPS port on them.

**Comment by rhnorskov** [comment]
I have this issue as well, was a solution ever found?
