### ISSUE TITLE
Install script not working on Debian 8.4

### ISSUE THREAD

**Issue by Rafficer** [ajenti/ajenti#925]
I can't get Ajenti to run on Debian 8.4. When I use the install script it tells me everything was successful but when i try to open the site with `https://myip:8000` it tells me that the connection was unexpectedly closed (Chrome). Doing a manual install does not work either for me. It was a clean install and nothing else was running on the server.
I changed my VPS to Ubuntu and there everything works fine.

How can i solve this and make it run on Debian Jessie?

**Comment by NHDriver4** [comment]
Rafficer, this seems to be an SSL issue. I've had no luck getting Ajenti to work on Debian 8.4 other than to disable SSL in /etc/ajenti/config.json

**Comment by Rafficer** [comment]
You're right. It works for me with SSL disabled as well. Hopefully it will get fixed soon as it is way too unsecure that way. Thanks a lot for your help.

**Comment by phonique** [comment]
Try using gevent 1.1b4:
`easy_install -U gevent==1.1b4`
There's an additional discussion over at [support.ajenti.org](http://support.ajenti.org/topics/666-cannot-access-ajenti-on-port-8000/).

NB: This might have to do with the change in WSGIHandler, see [here](https://github.com/gevent/gevent/releases/tag/v1.1b5)

> "gevent.pywsgi.WSGIServer (WSGIHandler) does a better job detecting and reporting potential encoding errors for headers and the status line during start_response as recommended by the WSGI specification. In addition, under Python 2, unnecessary encodings and decodings (often a trip through the ASCII encoding) are avoided for conforming applications. This is an enhancement of an already documented and partially enforced constraint: _**beginning in 1.1a1, under Python 2, u'abc' would typically previously have been allowed, but u'\u1f4a3' would not; now, neither will be allowed**_, more closely matching the specification, improving debugability and performance and allowing for better error handling both by the application and by gevent (previously, certain encoding errors could result in gevent writing invalid/malformed HTTP responses)."  [emphasis added]

**Comment by iamra** [comment]
@phonique recommendation worked for me, I had to first install `apt-get install python-dev` otherwise I was getting a fatal error. Debian 8.5

**Comment by Eugeny** [comment]
The fixed `gevent-socketio` package (compatible with the new `gevent` versions) is now available in the Ajenti repo. You should be able to just update it, or install manually from http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
