### ISSUE TITLE
sudo: 1 incorrect password attempt

### ISSUE THREAD

**Issue by agusputra** [ajenti/ajenti#933]
I install ajenti core (ajenti 2.1.15) on Ubuntu 14.04. And always get  `sudo: 1 incorrect password attempt` when try to elevate my credential to root.

**Comment by scrolls-mckenzie** [comment]
Same issue here.

I added my used into the sudoer group and still cant elevate

**Comment by scrolls-mckenzie** [comment]
I've been trying multiple options to get a fix for this issue. I created a new user and have assigned them to both sudo and root groups. 
I have been running in debug mode to see what the issue is and it fails here.

`17.06.2016 01:00  [rstrct 10967]          gate.py:110   DEBUG    Popen: ['sudo', '-S', '-u', u'ROOTUSER', '--', 'sh', '-c', 'sudo -k; sudo -S echo']`
`17.06.2016 01:01  [master 10958]    middleware.py:244   DEBUG  4.404s   65.0 bytes   200 POST /api/core/auth`

I have edited out my actual Root Username and replaced with ROOTUSER for the purpose of posting. 
I have also sent an email to the dev team and am waiting a response

**Comment by mbround18** [comment]
I just ran into this issue

**Comment by MostHated** [comment]
No resolution for this? Just installed on a fresh ubuntu 14.04 and am getting this. It keeps putting me back to the login screen now, and then adds on to the url. 
https://ipaddress:8000/view/login/sudo:administrator//view/dashboard

auth.log keeps showing : 

`Aug 25 11:48:55 LinuxWeb sudo: pam_unix(sudo:auth): authentication failure; logname= uid=65534 euid=0 tty= ruser=nobody rhost=  user=nobody

Aug 25 11:48:57 LinuxWeb sudo: pam_unix(sudo:auth): conversation failed

Aug 25 11:48:57 LinuxWeb sudo: pam_unix(sudo:auth): auth could not identify password for [nobody]

Aug 25 11:48:57 LinuxWeb sudo:   nobody : user NOT in sudoers ; TTY=unknown ; PWD=/ ; USER=administrator ; COMMAND=/bin/sh -c sudo -k; sudo -S echo
`

**Comment by Menci** [comment]
Same issue but I don't know how to view the log.

**Comment by MostHated** [comment]
I just ended up saying 'screw it' and went back to using Virtualmin, as it has never given me an issue. : /

**Comment by cdprf** [comment]
same as all 👎

**Comment by hitech95** [comment]
+1

**Comment by windhamwong** [comment]
I understand that Ajesnti is made for convenience and new people who just start learning Linux. I would recommend people participated in this thread to read the User and Group chapter of Linux and also some security on authentication as well.

In this case, it appears that Ajenti is running the server with nobody permission. the sudo feature is not correctly switching to your logged account before going for sudo, and this is the major issue you cannot log onto the server. (Please check /var/log/auth.log or your auth log according to linux distro) @scrolls-mckenzie made the workaround, however, it will seriously harming the server and putting the server in a dangerous situation.

I am here only because I would like to test out a Webmin alternative, but the sudo issue seems impact a lot. The config of Ajenti is way too simple as well, I hope the developers would fix these issues in the near future.

**Comment by arsfeld** [comment]
I've been getting the same issue and it seems the root cause comes a bit earlier. I'm getting these when clicking in Elevate:

```
26.12.2016 18:25  [master 30018]    virtsocket.py:472   DEBUG  heartbeat timed out, killing socket
26.12.2016 18:25  [master 30018]    virtsocket.py:230   DEBUG  Calling disconnect() on sessid='35509029489' client_queue[2] server_queue[1] hits=1
26.12.2016 18:25  [master 30018]    middleware.py:64    DEBUG  Socket 140040072083088 disconnected
26.12.2016 18:25  [master 30018]    virtsocket.py:243   DEBUG  Removing sessid='35509029489' client_queue[2] server_queue[1] hits=1 from server sockets
```

So when elevate is finally called, there's no user currently logged in, thus the `nobody` issue in `sudo` that occur later.

**Comment by LeoMartinDev** [comment]
same here

**Comment by scrolls-mckenzie** [comment]
Hello all. 

The issues I had where on a already running server. I have recently tried again on a semi-fresh (no management software prior) server with success. If your using the ec2 than that is where I had my original issues. I was able to get a working version running on a physical dev server. After evaluating the product, I have now gone back to Webmin for my own reasons. 

@windhamwong is correct that my way of debugging left some large security risks in the server. This would never be recommended for any production grade deployment. As I stated above, I had more success on a physical machine that I administer than virtual machines. However, I will not be attempting to install on a virtual machine as it does not meet my requirements as a package.

**Comment by crimsdings** [comment]
same issue on a fresh ubuntu server 16.10 ...

Jan 20 09:54:30 server sudo:   nobody : user NOT in sudoers ; TTY=unknown ; PWD=/ ; USER=myuser ; COMMAND=/bin/ls

adding nobody to sudo group sudo adduser nobody sudo makes no sense, user also has no password .. how is this feature supposed to work ? or is it actually supposed to work ?

**Comment by sylvanaar** [comment]
Try editing  /etc/ajenti/config.yml

There you should add a top-level option "restricted_user", try setting it to a user who has sudo access

**Comment by muotaz** [comment]
thanks,  @sylvanaar that got it working

**Comment by lucasmontec** [comment]
Cannot get it to work using this. Where should I put the config?

**Comment by crimsdings** [comment]
for people who come here to look for a solution: @lucasmontec :
`sudo vim /etc/ajenti/config.yml`
(or whatever text editor you prefer)
add:
`restricted_user: yourusername` 
at the bottom of the file obviously save and exit
`sudo service ajenti restart`

now elevate works on my
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

**Comment by Eelviny** [comment]
Quick question: I've got one restricted user, but how do I add multiple?

**Comment by OdinWynd** [comment]
Still having this issue on Ubuntu 14.04

**Comment by vpuhoff** [comment]
Для тех кто столкнется с этим. Можно если ничего другого не поможет проверить есть ли пользователь root и если есть то входить под ним.

**Comment by garrettcadams** [comment]
im not getting the restricted_user trick to work where in the file do i place it does anyone have a screen shot

**Comment by gap579137** [comment]
GarrettC what you should be able to do is place that line of code at the bottom of the file. I have attached a screencap of what mine looks like. Where it says replaceME, put your user name that you log in with.

So if you log in to the CP with user1 then put user1 where I have replaceME

Once you have done that press the `:` key (shift ;) and type `wq` and that will save the file.

Then from your command line type: `sudo service ajenti restart`

Log out of your control panel and log back in and try to go to an elevated required page. It will as you to authenticate again and it should work. 


![cap](https://user-images.githubusercontent.com/30596626/30240242-1b9faec2-9532-11e7-9475-9c6a56c61eff.PNG)

If this doesn't work. Let me know and I will see if I can help further. Us Garretts have to stick together LOL

GarrettP

**Comment by sojab0on** [comment]
I added the line to the bottom of the file and restarted the ajenti service but now the site isnt even accessable on localhost

what can i do

**Comment by jpdrsn** [comment]
> 
> 
> for people who come here to look for a solution: @lucasmontec :
> `sudo vim /etc/ajenti/config.yml`
> (or whatever text editor you prefer)
> add:
> `restricted_user: yourusername`
> at the bottom of the file obviously save and exit
> `sudo service ajenti restart`
> 
> now elevate works on my
> Distributor ID: Ubuntu
> Description: Ubuntu 16.10
> Release: 16.10
> Codename: yakkety

This should be in the "getting started" documentation. Spent an hour to find this options. Or at least have it in the default config commented out.
