### ISSUE TITLE
Bug: Login Issues

### ISSUE THREAD

**Issue by c0fe** [ajenti/ajenti#934]
​​There seems to be an issue when you initially install Ajenti. For example, I have Debian 8 fresh install on the machine and just installed Ajenti. But when I navigate to https URL with port 8000 so it was encrypted I get this error: ​http://imgur.com/AG4dBjb​

But when I edited the configuration and removed ssl, I am able to login:

​http://imgur.com/y1cLgu7​

Why does this happen? How to fix?

**Comment by Xefir** [comment]
This is a problem with gevent.
This problem has been argued many many many times in others issues.

You have to install a specific version of gevent to get Ajenti working properly.
To do this run : 
`sudo pip install gevent==1.1b4`

**Comment by Eugeny** [comment]
The fixed `gevent-socketio` package (compatible with the new `gevent` versions) is now available in the Ajenti repo. You should be able to just update it, or install manually from http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
