### ISSUE TITLE
egg info error

### ISSUE THREAD

**Issue by edelin3** [ajenti/ajenti#936]
root@macus:~# sudo pip install ajenti-panel ajenti.plugin.dashboard ajenti.plugin.settings ajenti.plugin.plugins
Collecting ajenti-panel
  Using cached ajenti-panel-2.1.15.tar.gz
Collecting ajenti.plugin.dashboard
  Using cached ajenti.plugin.dashboard-0.34.tar.gz
Collecting ajenti.plugin.settings
  Using cached ajenti.plugin.settings-0.21.tar.gz
Collecting ajenti.plugin.plugins
  Using cached ajenti.plugin.plugins-0.39.tar.gz
Collecting aj==2.1.15 (from ajenti-panel)
  Using cached aj-2.1.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_qdyqdp0/aj/setup.py", line 12, in <module>
        __requires.append('gevent>=1')
    AttributeError: 'filter' object has no attribute 'append'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_qdyqdp0/aj/

**Comment by medhamza911** [comment]
@edelin3 did you find any solution to it ?

**Comment by medhamza911** [comment]
sorry i installed from here http://docs.ajenti.org/en/latest/man/install.html
it didn't work
so i found simple one here http://support.ajenti.org/topics/1121-installing-on-ubuntu/

**Comment by heX16** [comment]
thanks!
I setup to "Orange Pi Zero (orangepi)" with this instruction: http://support.ajenti.org/topics/1121-installing-on-ubuntu/

**Comment by eirnym** [comment]
Manual installation is still broken and installing via package system is not acceptable for me. Please fix a bug

**Comment by eirnym** [comment]
```
Collecting aj==2.1.24 (from ajenti-panel)
  Using cached https://files.pythonhosted.org/packages/3c/eb/32f9e8c1c28294bbcaef86a37e68a901e8d0c2218894e488fb149c1649a0/aj-2.1.24.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5b/fxg9wb6d3n31xcktqftx5x7c0000gn/T/pip-install-8pnhb6wu/aj/setup.py", line 11, in <module>
        __requires.append('gevent>=1')
    AttributeError: 'filter' object has no attribute 'append'
```

**Comment by eirnym** [comment]
Is this issue was fixed?

**Comment by kiarn** [comment]
Hello @eirnym 

I have installed `Ajenti` on many server the lsat 2 years using `pip` and I didn't encounter any problem.
Can you please test again ?

**Comment by eirnym** [comment]
I wondering more why the issue wasn't closed after all these years of development. Probably there's more such issues in your backlog awaiting to be closed :)

**Comment by kiarn** [comment]
I came later to help the project, and wasn't aware of this issue, otherwise I would have answered sooner.
We are currently sorting all issues to get a better overview, and that's how we can see what's still on.

But for this one I think we can surely close :)
