### ISSUE TITLE
 Signature by key XXX uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#937]
Hi

`http://repo.ajenti.org/debian/dists/main/InRelease: Signature by key XXX+ uses weak digest algorithm (SHA1)`

This is a security issue, and should be corrected immediately. 
A new key is probably needed.

**Comment by julianxhokaxhiu** [comment]
I second this, having the same issue too

**Comment by clueo8** [comment]
third; has there been any updates to support SHA2 on the ajenti side?

**Comment by pozemka** [comment]
Count me in. This message bothers me every time. This is security issue.

**Comment by bulgariamitko** [comment]
will this be fixed?

**Comment by Eugeny** [comment]
Should work now.
