### ISSUE TITLE
systemd (systemctl) used for a while by now

### ISSUE THREAD

**Issue by rautamiekka** [ajenti/ajenti#938]
I don't know about other distros, but since Ubuntu 15.04 Upstart (`start`/`service`) has been replaced by `systemd` (`systemctl`) so Ajenti won't and can't boot.

Tested on Ubuntu 16.04 LTS x64, Upstart can't be installed without deleting other packages.

**Comment by kiarn** [comment]
Hello @rautamiekka 

Do you speak from `Ajenti v1` or `Ajenti v2` ?

**Comment by rautamiekka** [comment]
This ticket was made in 2016, which is 4y before the release of v2, at least on GitHub. I haven't kept any kinda eye on the project since I've always done everything by myself and IIRC there was something bigger that prevented even considering it at the time.

Hell, I absolutely forgot about the project until the bot commented.

**Comment by kiarn** [comment]
I think I also have some forgotten tickets or pull requests on other projects, it happens.
`Ajenti v2` already use `systemctl` and `Ajenti v1` has reached its end of life.

So I think this issue could be closed.
