### ISSUE TITLE
[Question] Ajenti with Nginx+PHP7+MySQL(MariaDB)

### ISSUE THREAD

**Issue by saitoh183** [ajenti/ajenti#940]
Hi,

I was looking over the product and i find it looks good and sleek. But i already have Ngnix 1.10.0(/etc/nginx/ ... /usr/share/nginx/html), MariaDB server/client 10.1 and php7.0. Can i migrate my conf files of nginx and websites with minimal efforts or will i be forced to remove my current setup in favor of Ajenti/Ajenti-v

**Comment by janxb** [comment]
You can keep a lot of your custom configs, because ajenti-v has a field "custom configuration" in settings.
But initially you will have to delete all config files (ajenti-v does this for you) and start fresh.

**Comment by saitoh183** [comment]
and does Ajenti work with php7

**Comment by janxb** [comment]
You can have dual stacked php5.6 and php7.0. Just install the needed packages from the ajenti repo.

<pre>
# apt-cache search ajenti-v-php         
                                                                        
  ajenti-v-php-fpm - PHP support for Ajenti V (via PHP-FPM)                                                                
  ajenti-v-php5.6-fpm - PHP5.6 support for Ajenti V (via PHP-FPM / ppa:ondrej/php)                                         
  ajenti-v-php7.0-fpm - PHP support for Ajenti V (via PHP-FPM / ppa:ondrej/php)  
</pre>

**Comment by saitoh183** [comment]
i guess i will try this on a test machine because i did give it a try on my production 15.04 and it was a disaster...i couldnt even get phpvirtualbox to work...currently i have everything working with nginx/php7.0/mariaDB. i dont mind removing nginx in favor of Ajenti version but i have to figure out how the website gui translates to the conf file so i can properly import my website configs.

Would stacking php5.6 with 7.0 cause issues for things like phpvirtualbox, phpmyadmin?...im still new to linux and php

**Comment by Ardakilic** [comment]
I'm ruiing with PHP7, mariadb just fine. I've just added repositories, for PHP7 to run I did a simple edit

https://github.com/Eugeny/ajenti-v/pull/213#issuecomment-218722433

Still works just as fine :)

**Comment by noogen** [comment]
Not sure if dual stack is necessary unless you have other software that required older PHP too as 5.6 is set to go out of support at the end of this year.  phpMyAdmin latest version works fine in php7 for me.  WordPress latest also works fine on php7, though many WP plugins are not. I would rather see additional support for php7.1 too though.

Having said that, I tested dual stack on Ubuntu 16.04 fine.  You can fine my docker example here: https://github.com/niiknow/ajenti-udock

**Comment by wrrr** [comment]
I installed latest Ajenti and Ajenti -V on 16.04. MariaDb is not working out of the box although the MySql in left column is fine with the defaults and schema I restarted everything but no MySql tab shows when adding a website for a db. Any insight on how that may have worked for you would be appreciated.

**Comment by noogen** [comment]
Did you already have MariaDB installed before Ajenti?   You need to provide a privileged mysql/mariadb login in tab:  Configure -> Plugin -> MySQL

The default credential: localhost, root and empty password.  This is if you're running ajenti as root.  Bad, I know, but it's a docker image.

See the MySQL tab of my docker demo here:  https://cloud1.noogen.net:9000/
Login: root
Pass: admin
- Accept the self-signed SSL.   

This is the image: https://hub.docker.com/r/niiknow/ajenti-udock/
As previously mentioned, triple stacks (5.6, 7.0, 7.1) and also running phpMyAdmin installed on port 9001: http://cloud1.noogen.net:9001/
