### ISSUE TITLE
Problem installing ajenti plugin

### ISSUE THREAD

**Issue by RasoulAM** [ajenti/ajenti#942]
I am trying to write a plugin for ajenti. I tried install a demo plugin for practice. I got this file from git...
https://github.com/ajenti/demo-plugins
and tried to install the bower plugin based on the suggestion in the ajenti website. (The link is below)
http://docs.ajenti.org/en/latest/dev/intro.html
I took all the steps in the link above. But I had trouble in the last stage.
I ran this command in the terminal :
...:~/Downloads/demo-plugins$ sudo ajenti-dev-multitool --run-dev
I keep getting this message:

option --autologin not recognized
Usage: %s [options]
Options:
    -c, --config <file> - Use given config file instead of default
    -v                  - Debug/verbose logging
    -d, --daemon        - Run in background (daemon mode)
    -h, --help          - This help
    --set-platform <id> - Override OS detection

I should point out that ajenti-dev-multitool has no option "autologin". The error message doesn't make any sense.

**Comment by rtroncosogar** [comment]
It's a problem with you ajenti version, for sure you've installed an old version, following a deprecated tutorial.

I suggest to run this command to update ajenti

`pip install --upgrade aj ajenti-panel`

**Comment by coolternet** [comment]
`root@debian:/etc/init.d# pip install --upgrade aj ajenti-panel
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.`
