### ISSUE TITLE
Remove python-ldap dependency; can't install ajenti

### ISSUE THREAD

**Issue by Datamance** [ajenti/ajenti#945]
Even when trying python 2 pip install I get this:

```
Collecting python-ldap
  Downloading python-ldap-2.4.26.tar.gz (124kB)
    100% |████████████████████████████████| 133kB 3.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-zcdeslux/python-ldap/setup.py", line 53
        print name + ': ' + cfg.get('_ldap', name)
                 ^
    SyntaxError: invalid syntax
```

The setup breaks because of the bad print statement.

**Comment by mightydok** [comment]
@Datamance think you use python3, can u paste output for command?

>  python -V

In python3 print became a function, more info: https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function

**Comment by krisavi** [comment]
In python3 the package is named ldap3
I am getting issues already at pip install phase
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (setup.py) ... error
and long long error here.
