### ISSUE TITLE
504 gateway error

### ISSUE THREAD

**Issue by agreements** [ajenti/ajenti#954]
After i woke up this morning i keep getting the 504 error gateway timeout. 
Could anyone assist me with this?
Really new to ubuntu ´(14.04) but i did manage to get it working for 5 days with no problems.

**Comment by agreements** [comment]
And now i get 502 errors also.

this is my php.ini file for the specific domain:
open_basedir = none;
try_files $uri =404;
fastcgi_split_path_info ^(.+.php)(/.+)$;
client_max_body_size 100M;
upload_max_filesize = 100M
max_input_time = 1000
max_execution_time = 2000
max_input_vars = 10000;

And my advance settings:

# This order might seem weird - this is attempted to match last if rules below fail.

location / {
    try_files $uri $uri/ /index.php?$args;
}

# Add trailing slash to */wp-admin requests.

rewrite /wp-admin$ $scheme://$host$uri/ permanent;

# Directives to send expires headers and turn off 404 error logging.

location ~\* ^.+.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
       access_log off; log_not_found off; expires max;
}

location = /favicon.ico {
    log_not_found off;
    access_log off;
}
location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
}

**Comment by wrrr** [comment]
You have an NGINX webserver (I assume) and appear to be complicating things that are boilerplate and  you can add directives/files for WordPress to your file structure that are pointed to using Ajenti (as in advanced tab and creating fastcgi in the content tab).

I would read this useful [guide](https://smyl.es/how-to-setup-a-wordpress-php-site-with-nginx-php5-fpm-using-ajenti-v/).
