### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by sv1jsb** [ajenti/ajenti#96]
Installed from ajenti repo on ubuntu 13.04.
Ajenti version 0.99.33.

At login screen I enter "root" and "admin"
as user and password.
After clicking login, the cogs are briefly displayed,
but I am getting the login screen again.

It seems like the credentials are correct but then something goes wrong
(permissions?) and get redirected back to the login screen.

No logs are recorded.
I have done several "service ajenti restart" with the same outcome.

Andreas.

**Comment by shahbaz-dev1** [comment]
I am still having the issue. removed all cache changed the password from terminal but no luck. Can you please guide me
