### ISSUE TITLE
Ajenti panel won't load after install using pip

### ISSUE THREAD

**Issue by a-goodarzi** [ajenti/ajenti#965]
Hello.
I use [this link](http://docs.ajenti.org/en/latest/man/install.html) to install and develop plugins for ajenti.
after installing i navigate to https://localhost:8000 but the browser just loading and nothing happened.
here is my "service ajenti status" : 

> numb@numb-ThinkPad:~$ sudo service ajenti status
> ● ajenti.service - Ajenti panel
>    Loaded: loaded (/lib/systemd/system/ajenti.service; disabled; vendor preset: enabled)
>    Active: active (running) since شنبه 2016-10-15 17:26:14 IRST; 3min 10s ago
>   Process: 2521 ExecStart=/usr/bin/python /usr/local/bin/ajenti-panel -d (code=exited, status=0/SUCCESS)
>  Main PID: 2536 (/usr/bin/python)
>     Tasks: 3 (limit: 4915)
>    Memory: 54.6M
>       CPU: 2.036s
>    CGroup: /system.slice/ajenti.service
>            ├─2536 /usr/bin/python /usr/local/bin/ajenti-panel -d
>            └─2551 /usr/local/bin/ajenti-panel worker [restricted session]
> Oct. 15 17:26:14 numb-ThinkPad systemd[1]: Starting Ajenti panel...
> Oct. 15 17:26:14 numb-ThinkPad systemd[1]: ajenti.service: PID file /var/run/ajenti.pid not readable (yet?) after start: No such file or directory
> Oct. 15 17:26:14 numb-ThinkPad systemd[1]: Started Ajenti panel.

and this is my "ajenti.log" :

> numb@numb-ThinkPad:~$ cat /var/log/ajenti/ajenti.log 
> 2016-10-15 16:52:16,855 INFO     core.run(): Ajenti 1.2.23.8 running on platform: debian
> 2016-10-15 16:52:16,888 INFO     sm_upstart.verify(): Disabling Upstart service manager: org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu.Upstart was not provided by any .service files
> 2016-10-15 16:52:17,215 INFO     core.run(): Starting server on (u'0.0.0.0', 8000)
> <socket fileno=13 sock=127.0.0.1:8000 peer=127.0.0.1:45774>: Invalid HTTP method: '\x16\x03\x01\x00\xc0\x01\x00\x00\xbc\x03\x03\xd5\xfb\xb1#\x93bn\x11`j#U|Y\xe5H_wF\xf0c\x06F\xdc\xbc(\xb9Y\xb6\xfb\xc9\x02\x00\x00\x1e\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0\n'
> <socket fileno=13 sock=127.0.0.1:8000 peer=127.0.0.1:45788>: Invalid HTTP method: '\x16\x03\x01\x00\xc0\x01\x00\x00\xbc\x03\x03\x13p\xb1O\x85\xa3\xa7\x12\x9b\x80p\xfe\xc4P\xbe\x89}3\x8d\xf78\x98\x8f?\xf8\xe8\x02j\xa8\xc7\xe7J\x00\x00\x1e\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0\n'
> <socket fileno=13 sock=127.0.0.1:8000 peer=127.0.0.1:46126>: Invalid http version: "\x16\x03\x01\x00\xc0\x01\x00\x00\xbc\x03\x03\x7f\x18h3F {'n(Q\xe7\x16\x17\xf4U\t\xdf:5\xf8\xfd\xdc\x12%\xd1n_'\xc0\x03\x94\x00\x00\x1e\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0\n"
> <socket fileno=13 sock=127.0.0.1:8000 peer=127.0.0.1:46144>: Invalid HTTP method: '\x16\x03\x01\x00\xc0\x01\x00\x00\xbc\x03\x03\xdb5\xeeI\2\xfamr\xe6\xf7\x00Q\x1f\x89F\xcb\x87>_\xc6\x8c\xdf\x8d\xee"\x19\xfc(\x90\x08\xd9\x00\x00\x1e\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0\n'
> <socket fileno=13 sock=127.0.0.1:8000 peer=127.0.0.1:46508>: Invalid HTTP method: '\x16\x03\x01\x00\xc0\x01\x00\x00\xbc\x03\x03\xa7\x9c}\xb4\xda\x86\x8c\xde\xf6\xaa\x13{\xea\xa9\xc3"g\xfc\xc9\x12[\xf2\x97\x18j\xef}\xbc\x84\xbb\x90\xd7\x00\x00\x1e\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0\n'
> 2016-10-15 17:26:14,833 INFO    : Loading config from /etc/ajenti/config.yml
> 2016-10-15 17:26:14,836 INFO    : Ajenti Core 2.1.15
> 2016-10-15 17:26:14,836 INFO    : Detected platform: debian / Ubuntu 16.10
> 2016-10-15 17:26:14,909 INFO    : Discovered 12 plugins
> 2016-10-15 17:26:15,169 INFO    : Loaded 12 plugins
> 2016-10-15 17:26:15,169 INFO    : Binding to [0.0.0.0]:8000
> 2016-10-15 17:26:15,173 INFO    : SSL enabled
> 2016-10-15 17:26:15,176 INFO    : New worker "restricted session" PID 2551, EUID 0, EGID 0
> 2016-10-15 17:26:15,176 INFO    : Worker 2551 is demoting to UID 65534 / GID 65534...
> 2016-10-15 17:26:15,177 INFO    : ...done, new EUID 65534 EGID 65534

but the Browser still trying to load it :(.
Thanks

**Comment by djmacloud** [comment]
I'm having this same problema in ubuntu 16.04

I mean, mine isn't even locating the service.

My installation got no problems but still I have no service or ajenti directory in /etc/init.d

root@ubuntu:~# service ajenti status
● ajenti.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

root@ubuntu:~# cd /etc/init.d/

root@ubuntu:/etc/init.d# ls
acpid                   hostname.sh            ondemand        single
apparmor                hwclock.sh             plymouth        skeleton
apport                  irqbalance             plymouth-log    ssh
atd                     keyboard-setup         pppd-dns        thermald
bootmisc.sh             killprocs              procps          udev
cgmanager               kmod                   rc              ufw
cgproxy                 lvm2                   rc.local        umountfs
checkfs.sh              lvm2-lvmetad           rcS             umountnfs.sh
checkroot-bootclean.sh  lvm2-lvmpolld          README          umountroot
checkroot.sh            mountall-bootclean.sh  reboot          unattended-upgrades
console-setup           mountall.sh            resolvconf      urandom
cron                    mountdevsubfs.sh       rsync           uuidd
dbus                    mountkernfs.sh         rsyslog         x11-common
dns-clean               mountnfs-bootclean.sh  S97-setup.sh
grub-common             mountnfs.sh            screen-cleanup
halt                    networking             sendsigs

**Comment by ValkiryXDA** [comment]
Try this worked for me.

check to make sure ajenti panel init.d script is actually pointing to where ajenti is actually installed. I had this issue on ubuntu, ajenti was actually located in /usr/local/bin/ajenti-panel. 

method:
sudo service ajenti-panel start
sudo service ajenti-panel status 
#Check the out put of the status and see where it fails 
#Locate where ajenti is actually is by "whereis ajenti-panel"
nano /etc/init.d/ajenti
-Find the line:
NAME=Ajenti
DAEMON=/usr/bin/ajenti-panel  <--- Edit this line to where ajenti-panel actual is
sudo systemctl daemon-reload
sudo service ajenti-panel start 

And hopefully now you should have access to your ajenti panel.

**Comment by a-goodarzi** [comment]
It seems that Ajenti won't develop anymore.
I will close the issue
