### ISSUE TITLE
SSL self-signed certificate generator dont work in debian

### ISSUE THREAD

**Issue by Dont-ask-for-it** [ajenti/ajenti#967]
Generating an SSL self-signed certificate generator in Ajenti admin panel and select Use SSL will prevent you showing the webpage (neither https or http will work). Path to .pem have been verified. 

Something is broken.

Tried on Ajenti with AjentiV Nginx on Debian 8 64 bit.

**Comment by mightydok** [comment]
@beauvafr can u create bug report, paste ur ajenti version and logs?
