### ISSUE TITLE
[idea] New Issues Label

### ISSUE THREAD

**Issue by elacheche** [ajenti/ajenti#968]
Hey!

Why don't add an other label that tell if an issue can be fixed by a new contributor, that way people who like to contribute (like myself) will know where to start..

**Comment by mightydok** [comment]
Agreed. Need some issue management.

**Comment by elacheche** [comment]
@mightydok Should we tag someone to react to this! :/

**Comment by mightydok** [comment]
I think we need @Eugeny help
