### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by kingonoverall** [ajenti/ajenti#971]
on user elevate 
https://localhost:8000/view/login/sudo:xxxxxxxxxxxxx//view/dashboard

all.js:13428 

Possibly  unhandled rejection: {"data":"","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/core/tasks/request-update","headers":{"Accept":"application/json, text/plain, */*"},"cached":false},"statusText":""}

**Comment by Eugeny** [comment]
Fixed. See #972 for the solution
