### ISSUE TITLE
Reconnecting / Refreshing Every 10 Seconds after Login into Panel

### ISSUE THREAD

**Issue by luckyrajiv** [ajenti/ajenti#973]
After logging into the Ajenti Panel.

Panel keeps reconnecting / refreshing itself every few seconds. 

Anyone Please Help.

**Comment by Rooting21** [comment]
i have this problem

**Comment by mbrinson** [comment]
I have this problem as well.  In my case, I have to restart the ajenti process from console every time this happens.  Ajenti just stops and I have to restart.

**Comment by noogen** [comment]
On ubuntu 16.04 LTS, mine tend to crash as well and won't come back until I manually login and restart it.  As a workaround, I remove it from systemd/service and use supervisord with autorestart=true.
