### ISSUE TITLE
HTTP-Status-Code 401 on sidebar request (before login)

### ISSUE THREAD

**Issue by zapalukus** [ajenti/ajenti#974]
Hi Eugene
I tried to install ajenti on a freshly set up Debian Jessie Server.
Unfortunately the Login Page freezes on a 401 Error when making a XHR-Request to "sidebar". He is constantly retrying and freezes the browser. This is what the Browser console says:
> uncaught exception: Possibly unhandled rejection: {"data":"","status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/core/sidebar","headers":{"Accept":"application/json, text/plain, */*"},"cached":false},"statusText":""}

The error occurs on both: the SSL and the non-SSL login page.
I also tried multiple versions of gevent.
I hope this is no big issue.
Thank you for your hard work to create such a great Control Panel.
Best regards
Lukas

**Comment by Serverfrog** [comment]
Maybe same problem as on #974

**Comment by Eugeny** [comment]
Duplicate. See #972 for the solution
