### ISSUE TITLE
Implement TOTP based Two Factor Authentication for Google Authenticator or Authy

### ISSUE THREAD

**Issue by saidul** [ajenti/ajenti#975]
Hi there,
I've started working on implementing TOTP based two factor authentication. As raised here http://support.ajenti.org/topics/443-two-factor-authentication/ and here http://support.ajenti.org/topics/373-two-factor-authentication-with-u2fother-providers/

Mozilla Persona will be discontinued from November 30th, 2016. It will be nice to have other 2FA provider. My initial target is to implement **TOTP** (Time based One Time Password) which is supported by Google Authenticator, Authy, 1Password and many other provider.

Here are my progress on this:
- Users will be presented with a token input box if 2FA is enabled for this user. User will need to enter a temporary generated password from his app (Google Authenticator / Authy) which is generally valid for 30 seconds.
<img width="291" alt="token_after_login" src="https://cloud.githubusercontent.com/assets/357908/20088192/c3340766-a5a8-11e6-99e9-fe44c2d203ef.png">

- 2FA configuration is placed in password section. Help me if you have better idea 😃 
<img width="679" alt="2fa_enable" src="https://cloud.githubusercontent.com/assets/357908/20088202/ce1b2272-a5a8-11e6-9790-f8b178fdeb09.png">

- This dialog will be displayed once when enabling 2FA. I think instead of TOTP Uri, We can take first generated password from the app to verify if its scanned properly.
<img width="410" alt="configure" src="https://cloud.githubusercontent.com/assets/357908/20088204/d3ab840c-a5a8-11e6-9f2e-b25cfee48d86.png">

Currently I'm stuck on saving TOTP secret. I'm trying to store it like this:
```python
data = {
     'type': "TOTP",
     'secret': secret
}

username = self.context.session.identity
ajenti.config.tree.users[username]['otp_config'] = data
ajenti.config.save()
dialog.visible = False
```

I get following error when I try to save. Can anyone give some hint?
```
'UserData' object does not support item assignment
```

**Comment by Eugeny** [comment]
Hi @saidul,

You're getting this error because `config.tree.users[...]` is not a dict but rather a `reconfigure.items.BoundData` instance. You will need to add the new fields to this spec: https://github.com/Eugeny/reconfigure/blob/master/reconfigure/items/ajenti.py#L54

**Comment by saidul** [comment]
@Eugeny Thank you
