### ISSUE TITLE
Package installers not working

### ISSUE THREAD

**Issue by bernieblume** [ajenti/ajenti#982]
Tried installing under debian 8.5, followed installation guide on ajenti.org. Was asked to enable Flash (???) which I confirmed. After that, white screen.

I thought I try CentOS. There, "yum install ajenti" fails:
```
--> Finished Dependency Resolution
Error: Package: ajenti-1.2.22.13-1.noarch (ajenti)
           Requires: python-daemon
Error: Package: ajenti-1.2.22.13-1.noarch (ajenti)
           Requires: python-psutil >= 0.6.0
Error: Package: ajenti-1.2.22.13-1.noarch (ajenti)
           Requires: python-passlib
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
Was Ajenti deserted some time ago?

**Comment by ksl1231** [comment]
remove epel repo first(yum -y remove epel-release), and reinstall epel again(yum -y install epel-release)

**Comment by matinkadri** [comment]
> remove epel repo first(yum -y remove epel-release), and reinstall epel again(yum -y install epel-release)

this has resolved the issue for me. thanks!
