### ISSUE TITLE
no mysld_safe in centos 7

### ISSUE THREAD

**Issue by chromerobv** [ajenti/ajenti#985]
i have mysql-server installed on centos 7. there is no mysqld_safe anymore, so ajenti fail on dependencies.

**Comment by timint** [comment]
+1 using CentOS 7.4

**Comment by mahmoud-eskandari** [comment]
I have this problem too!
I can't change OS!

Can i remove`mysqld_safe` in Ajenti mysql plugin by a trick?

**Comment by varun-naharia** [comment]
Is there any solution for this ?
