### ISSUE TITLE
ajenti-v-nodejs not found

### ISSUE THREAD

**Issue by timonsk** [ajenti/ajenti#986]
Hi all,
Unfortunately I can't find ajenti-v-nodejs to install from PPA for my Ubuntu Server 16 also not found git repo. Could please anybody help me to find it ?
Thanks!

**Comment by noogen** [comment]
It's here: https://github.com/Eugeny/ajenti-v/tree/master/vh-nodejs
I install it fine for 16.04.   Here's my script for installing on 16.04: https://github.com/niiknow/ajenti-udock/blob/master/udock/ajenti-install.sh

**Comment by noogen** [comment]
I've been actively messing around with docker build for Ajenti in the last couple of days.  I do find that, from time to time and especially at night, the Ajenti repo go offline.  Maybe it goes into maintenance?   If this happen, I just take a break and try again in a couple of hours.
