### ISSUE TITLE
Failed to start LSB: Ajenti - on Centos 7 Release 7.3.1611

### ISSUE THREAD

**Issue by sekayasin** [ajenti/ajenti#992]
Hello there, 
any help with ajenti installation on centos 7.3.1611

# ~ systemctl status ajenti
● ajenti.service - LSB: Ajenti
   Loaded: loaded (/etc/rc.d/init.d/ajenti; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-12-14 13:34:25 UTC; 1min 8s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 8974 ExecStart=/etc/rc.d/init.d/ajenti start (code=exited, status=1/FAILURE)

**Comment by zeroheure** [comment]
You should get an eye in the logs to see what happened. 
See /var/log/ajenti/ajenti.log
or try ajenti-panel -v and copy the output

**Comment by sestosensocom** [comment]
sekayasin have you find a solution?

**Comment by ohkeenan** [comment]
Correct me if I'm wrong: this is a problem which surfaced after upgrading CentOS/RHEL from version 6 to 7? If yes it is because the init daemon has changed from Upstart/SysV to SystemD. I've not been able to install Ajenti myself on a CentOS7/RHEL7 distro but am willing to try to help you.
