### ISSUE TITLE
Sync time from Internet - Error

### ISSUE THREAD

**Issue by praveenbm5** [ajenti/ajenti#995]
When I try to use the feature "Sync time from Internet" from DateTime plugin. It shows error bubble and Synchronizing bubble after that. Confusing.

**Comment by Kashyap12** [comment]
HI @praveenbm5 can I take this up?

**Comment by praveenbm5** [comment]
It's because datetime plugins has dependency on ntpdate. Install ntpdate and then use the latest datetime plugins.
